const u8 gCardDescription_4StarredLadybugofDoom[] = _("FLIP: Destroy all Level 4\nmonsters your opponent\ncontrols.");
const u8 gCardDescription_7ColoredFish[] = _("A rare rainbow fish that has\nnever been caught by mortal\nman.");
const u8 gCardDescription_AirknightParshath[] = _("If this card attacks a Defense\nPosition monster, inflict\npiercing battle damage. If\nthis card inflicts battle\ndamage to your opponent: Draw\n1 card.");
const u8 gCardDescription_AquaMadoor[] = _("A wizard of the waters that\nconjures a liquid wall to\ncrush any enemies that oppose\nhim.");
const u8 gCardDescription_AsuraPriest[] = _("Cannot be Special Summoned.\nDuring the End Phase of the\nturn this card is Normal\nSummoned or flipped face-up:\nReturn it to the hand. This\ncard can attack all monsters\nyour opponent controls once\neach.");
const u8 gCardDescription_BanisheroftheLight[] = _("Any card sent to the Graveyard\nis banished instead.");
const u8 gCardDescription_BattleOx[] = _("A monster with tremendous\npower, it destroys enemies\nwith a swing of its axe.");
const u8 gCardDescription_BazootheSoulEater[] = _("Once per turn: You can banish\nup to 3 monsters from your\nGraveyard; this card gains 300\nATK for each, until the end of\nyour opponent's turn.");
const u8 gCardDescription_Bickuribox[] = _("Crass Clown + Dream Clown");
const u8 gCardDescription_BlackSkullDragon[] = _("Summoned Skull + Red-Eyes\nBlack Dragon(This card is\nalways treated as an Archfiend\ncard.)");
const u8 gCardDescription_BlueEyesWhiteDragon[] = _("This legendary dragon is a\npowerful engine of\ndestruction. Virtually\ninvincible, very few have\nfaced this awesome creature\nand lived to tell the tale.");
const u8 gCardDescription_BusterBlader[] = _("Gains 500 ATK for each Dragon\nmonster your opponent controls\nor is in their GY.");
const u8 gCardDescription_CalloftheHaunted[] = _("Activate this card by\ntargeting 1 monster in your\nGY; Special Summon that target\nin Attack Position. When this\ncard leaves the field, destroy\nthat monster. When that\nmonster is destroyed, destroy\nthis card.");
const u8 gCardDescription_CannonSoldier[] = _("You can Tribute 1 monster;\ninflict 500 damage to your\nopponent.");
const u8 gCardDescription_Ceasefire[] = _("If a face-down Defense\nPosition monster or an Effect\nMonster is on the field:\nChange all face-down Defense\nPosition monsters on the field\nto face-up Defense Position\n(Flip monsters' effects are\nnot activated at this time),\nalso inflict 500 damage to\nyour opponent for each Effect\nMonster on the field.");
const u8 gCardDescription_ChangeofHeart[] = _("Target 1 monster your opponent\ncontrols; take control of it\nuntil the End Phase.");
const u8 gCardDescription_Confiscation[] = _("Pay 1000 Life Points. Look at\nyour opponent's hand, select 1\ncard in it and discard that\ncard.");
const u8 gCardDescription_CrassClown[] = _("When this card is changed from\nDefense Position to Attack\nPosition, return 1 monster on\nyour opponent's side of the\nfield to the owner's hand.");
const u8 gCardDescription_CreatureSwap[] = _("Each player chooses 1 monster\nthey control and switches\ncontrol of those monsters with\neach other. Those monsters\ncannot change their battle\npositions for the rest of this\nturn.");
const u8 gCardDescription_CyberJar[] = _("FLIP: Destroy all monsters on\nthe field, then both players\nreveal the top 5 cards from\ntheir Decks, then Special\nSummon all revealed Level 4 or\nlower monsters in face-up\nAttack Position or face-down\nDefense Position, also add any\nremaining cards to their hand.\n(If either player has less\nthan 5 cards in their Deck,\nreveal as many as possible.)");
const u8 gCardDescription_DarkBaltertheTerrible[] = _("Possessed Dark Soul + Frontier\nWisemanA Fusion Summon of this\nmonster can only be conducted\nwith the above Fusion Material\nMonsters. When a Normal Spell\nCard is activated, negate the\neffect by paying 1000 Life\nPoints. The effect of an\nEffect Monster that this\nmonster destroys as a result\nof battle is negated.");
const u8 gCardDescription_DarkElf[] = _("This card requires a cost of\n1000 of your own Life Points\nto attack.");
const u8 gCardDescription_DarkHole[] = _("Destroy all monsters on the\nfield.");
const u8 gCardDescription_DarkMagician[] = _("The ultimate wizard in terms\nof attack and defense.");
const u8 gCardDescription_DarkNecrofear[] = _("Cannot be Normal Summoned/Set.\nMust first be Special Summoned\n(from your hand) by banishing\n3 Fiend monsters from your GY.\nDuring the End Phase, if this\ncard is in your GY because it\nwas destroyed in your Monster\nZone by an opponent's card and\nsent there this turn: Target 1\nface-up monster your opponent\ncontrols; equip this card to\nthat target. While this card\nis equipped to a monster by\nthis effect, take control of\nthat monster.");
const u8 gCardDescription_DelinquentDuo[] = _("Pay 1000 LP; your opponent\ndiscards 1 random card, and if\nthey have any other cards in\ntheir hand, discard 1 more\ncard of their choice.");
const u8 gCardDescription_DreamClown[] = _("When this card is changed from\nAttack Position to face-up\nDefense Position, select 1\nmonster your opponent controls\nand destroy it.");
const u8 gCardDescription_DustTornado[] = _("Target 1 Spell/Trap your\nopponent controls; destroy\nthat target, then you can Set\n1 Spell/Trap from your hand.");
const u8 gCardDescription_Exchange[] = _("Both players reveal their\nhands and add 1 card from each\nother's hand to their hand.");
const u8 gCardDescription_ExiledForce[] = _("You can Tribute this card to\ntarget 1 monster on the field;\ndestroy that target.");
const u8 gCardDescription_ExodiatheForbiddenOne[] = _("If you have Right Leg of the\nForbidden One, Left Leg of the\nForbidden One, Right Arm of\nthe Forbidden One and Left Arm\nof the Forbidden One in\naddition to this card in your\nhand, you win the Duel.");
const u8 gCardDescription_FiberJar[] = _("FLIP: Each player shuffles all\ncards from their hand, field,\nand Graveyard into the Deck,\nthen draws 5 cards.");
const u8 gCardDescription_Fissure[] = _("Destroy the 1 face-up monster\nyour opponent controls that\nhas the lowest ATK (your\nchoice, if tied).");
const u8 gCardDescription_FlameSwordsman[] = _("Flame Manipulator + Masaki the\nLegendary Swordsman");
const u8 gCardDescription_GaiatheDragonChampion[] = _("Gaia The Fierce Knight + Curse\nof Dragon");
const u8 gCardDescription_GaiaTheFierceKnight[] = _("A knight whose horse travels\nfaster than the wind. His\nbattle-charge is a force to be\nreckoned with.");
const u8 gCardDescription_GeminiElf[] = _("Elf twins that alternate their\nattacks.");
const u8 gCardDescription_GiantGerm[] = _("When this card is destroyed by\nbattle and sent to the\nGraveyard: Inflict 500 damage\nto your opponent, then you can\nSpecial Summon any number of\nGiant Germs from your Deck in\nface-up Attack Position.");
const u8 gCardDescription_GiantRat[] = _("When this card is destroyed by\nbattle and sent to the\nGraveyard: You can Special\nSummon 1 EARTH monster with\n1500 or less ATK from your\nDeck, in Attack Position.");
const u8 gCardDescription_GiantSoldierofStone[] = _("A giant warrior made of stone.\nA punch from this creature has\nearth-shaking results.");
const u8 gCardDescription_GiantTrunade[] = _("Return all Spell and Trap\nCards on the field to the\nhand.");
const u8 gCardDescription_GigaTechWolf[] = _("An iron wolf with razor-sharp\nfangs that can penetrate any\narmor.");
const u8 gCardDescription_GoblinAttackForce[] = _("If this card attacks, it is\nchanged to Defense Position at\nthe end of the Battle Phase,\nand its battle position cannot\nbe changed until the End Phase\nof your next turn.");
const u8 gCardDescription_GracefulCharity[] = _("Draw 3 cards, then discard 2\ncards.");
const u8 gCardDescription_HarpiesFeatherDuster[] = _("Destroy all Spell and Trap\nCards your opponent controls.");
const u8 gCardDescription_HeavyStorm[] = _("Destroy all Spell and Trap\nCards on the field.");
const u8 gCardDescription_ImperialOrder[] = _("Negate all Spell effects on\nthe field. Once per turn,\nduring the Standby Phase, you\nmust pay 700 LP (this is not\noptional), or this card is\ndestroyed.");
const u8 gCardDescription_InjectionFairyLily[] = _("If this card attacks or is\nattacked, during damage\ncalculation (in either\nplayer's turn): You can pay\n2000 LP once per battle; this\ncard gains 3000 ATK during\nthat damage calculation only.");
const u8 gCardDescription_JarofGreed[] = _("Draw 1 card.");
const u8 gCardDescription_Jinzo[] = _("Trap Cards, and their effects\non the field, cannot be\nactivated. Negate all Trap\neffects on the field.");
const u8 gCardDescription_JiraiGumo[] = _("When this card declares an\nattack: Toss a coin and call\nit. If you call it wrong, lose\nhalf your Life Points.");
const u8 gCardDescription_JudgeMan[] = _("This club-wielding warrior\nbattles to the end and will\nnever surrender.");
const u8 gCardDescription_JustDesserts[] = _("Inflict 500 damage to your\nopponent for each monster they\ncontrol.");
const u8 gCardDescription_Kuriboh[] = _("During damage calculation, if\nyour opponent's monster\nattacks (Quick Effect): You\ncan discard this card; you\ntake no battle damage from\nthat battle.");
const u8 gCardDescription_KycootheGhostDestroyer[] = _("When this card inflicts battle\ndamage to your opponent: You\ncan target up to 2 monsters in\ntheir Graveyard; banish those\ntargets. Your opponent cannot\nbanish cards from either\nplayer's Graveyard.");
const u8 gCardDescription_LaJinntheMysticalGenieoftheLamp[] = _("A genie of the lamp that is at\nthe beck and call of its\nmaster.");
const u8 gCardDescription_LabyrinthTank[] = _("Giga-Tech Wolf + Cannon\nSoldier");
const u8 gCardDescription_LastWill[] = _("If a monster on your side of\nthe field was sent to your\nGraveyard this turn, you can\nSpecial Summon 1 monster with\nan ATK of 1500 points or less\nfrom your Deck once during\nthis turn. Then shuffle your\nDeck.");
const u8 gCardDescription_LeftArmoftheForbiddenOne[] = _("A forbidden left arm sealed by\nmagic. Whosoever breaks this\nseal will know infinite power.");
const u8 gCardDescription_LeftLegoftheForbiddenOne[] = _("A forbidden left leg sealed by\nmagic. Whosoever breaks this\nseal will know infinite power.");
const u8 gCardDescription_MagicCylinder[] = _("When an opponent's monster\ndeclares an attack: Target the\nattacking monster; negate the\nattack, and if you do, inflict\ndamage to your opponent equal\nto its ATK.");
const u8 gCardDescription_MagicJammer[] = _("When a Spell Card is\nactivated: Discard 1 card;\nnegate the activation, and if\nyou do, destroy it.");
const u8 gCardDescription_MagicianofFaith[] = _("FLIP: Target 1 Spell in your\nGY; add that target to your\nhand.");
const u8 gCardDescription_ManEaterBug[] = _("FLIP: Target 1 monster on the\nfield; destroy it.");
const u8 gCardDescription_MaskofDarkness[] = _("FLIP: Target 1 Trap in your\nGY; add that target to your\nhand.");
const u8 gCardDescription_MaskedSorcerer[] = _("When this card inflicts Battle\nDamage to your opponent's Life\nPoints, draw 1 card from your\nDeck.");
const u8 gCardDescription_Mechanicalchaser[] = _("A hunter that relentlessly\npursues its target by order of\nthe Machine King.");
const u8 gCardDescription_MirrorForce[] = _("When an opponent's monster\ndeclares an attack: Destroy\nall your opponent's Attack\nPosition monsters.");
const u8 gCardDescription_MonsterReborn[] = _("Target 1 monster in either GY;\nSpecial Summon it.");
const u8 gCardDescription_MorphingJar[] = _("FLIP: Both players discard as\nmany cards as possible from\ntheir hands, then each player\ndraws 5 cards.");
const u8 gCardDescription_MukaMuka[] = _("This card gains 300 ATK and\nDEF for each card in your\nhand.");
const u8 gCardDescription_MysticTomato[] = _("When this card is destroyed by\nbattle and sent to the GY: You\ncan Special Summon 1 DARK\nmonster with 1500 or less ATK\nfrom your Deck, in face-up\nAttack Position.");
const u8 gCardDescription_MysticalElf[] = _("A delicate elf that lacks\noffense, but has a terrific\ndefense backed by mystical\npower.");
const u8 gCardDescription_NeotheMagicSwordsman[] = _("A dimensional drifter who not\nonly practices sorcery, but is\nalso a sword and martial arts\nmaster.");
const u8 gCardDescription_NimbleMomonga[] = _("When this card is destroyed by\nbattle and sent to the\nGraveyard: Gain 1000 Life\nPoints, then you can Special\nSummon any number of Nimble\nMomongas from your Deck in\nface-down Defense Position.");
const u8 gCardDescription_NoblemanofCrossout[] = _("Target 1 face-down monster on\nthe field; destroy that\ntarget, and if you do, banish\nit, then, if it was a Flip\nmonster, each player reveals\ntheir Main Deck, then banishes\nall cards from it with that\nmonster's name.");
const u8 gCardDescription_Ookazi[] = _("Inflict 800 damage to your\nopponent.");
const u8 gCardDescription_PainfulChoice[] = _("Select 5 cards from your Deck\nand show them to your\nopponent. Your opponent\nselects 1 card among them. Add\nthat card to your hand and\ndiscard the remaining cards to\nthe Graveyard.");
const u8 gCardDescription_PenguinKnight[] = _("When this card is sent\ndirectly from your Deck to the\nGraveyard by an effect of a\ncard controlled by your\nopponent, unite your Graveyard\ncards and your own Deck,\nshuffle them and form a new\nDeck.");
const u8 gCardDescription_Polymerization[] = _("Fusion Summon 1 Fusion Monster\nfrom your Extra Deck, using\nmonsters from your hand or\nfield as Fusion Material.");
const u8 gCardDescription_PotofGreed[] = _("Draw 2 cards.");
const u8 gCardDescription_PrematureBurial[] = _("Activate this card by paying\n800 LP, then target 1 monster\nin your Graveyard; Special\nSummon that target in Attack\nPosition and equip it with\nthis card. When this card is\ndestroyed, destroy the\nequipped monster.");
const u8 gCardDescription_Raigeki[] = _("Destroy all monsters your\nopponent controls.");
const u8 gCardDescription_RedEyesBlackDragon[] = _("A ferocious dragon with a\ndeadly attack.");
const u8 gCardDescription_Reinforcements[] = _("Target 1 face-up monster on\nthe field; it gains 500 ATK\nuntil the end of this turn.");
const u8 gCardDescription_RightArmoftheForbiddenOne[] = _("A forbidden right arm sealed\nby magic. Whosoever breaks\nthis seal will know infinite\npower.");
const u8 gCardDescription_RightLegoftheForbiddenOne[] = _("A forbidden right leg sealed\nby magic. Whosoever breaks\nthis seal will know infinite\npower.");
const u8 gCardDescription_RobbinGoblin[] = _("Each time a monster you\ncontrol inflicts Battle Damage\nto your opponent, your\nopponent discards 1 random\ncard.");
const u8 gCardDescription_RushRecklessly[] = _("Target 1 face-up monster on\nthe field; it gains 700 ATK\nuntil the end of this turn.");
const u8 gCardDescription_RyuSenshi[] = _("Warrior Dai Grepher + Spirit\nRyuA Fusion Summon of this\ncard can only be done with the\nabove Fusion Materials. When a\nNormal Trap Card is activated\n(Quick Effect): You can pay\n1000 LP; negate that effect.\nThis card must be face-up on\nthe field to activate and to\nresolve this effect. Negate\nthe effects of any Spell Card\nthat targets this card and\ndestroy it.");
const u8 gCardDescription_Sangan[] = _("If this card is sent from the\nfield to the GY: Add 1 monster\nwith 1500 or less ATK from\nyour Deck to your hand, but\nyou cannot activate cards, or\nthe effects of cards, with\nthat name for the rest of this\nturn. You can only use this\neffect of Sangan once per\nturn.");
const u8 gCardDescription_SevenToolsoftheBandit[] = _("When a Trap Card is activated:\nPay 1000 LP; negate the\nactivation, and if you do,\ndestroy it.");
const u8 gCardDescription_SinisterSerpent[] = _("During your Standby Phase, if\nthis card is in your GY: You\ncan add it to your hand, also\nbanish 1 Sinister Serpent from\nyour GY during your opponent's\nnext End Phase. You can only\nuse this effect of Sinister\nSerpent once per turn.");
const u8 gCardDescription_SkullKnight[] = _("Tainted Wisdom + Ancient Brain");
const u8 gCardDescription_SkullLair[] = _("Remove from play any number of\nMonster Cards in your\nGraveyard to destroy 1 face-up\nmonster on the field whose\nLevel is equal to the number\nof the cards you removed from\nplay.");
const u8 gCardDescription_SnatchSteal[] = _("Equip only to a monster your\nopponent controls. Take\ncontrol of the equipped\nmonster. During each of your\nopponent's Standby Phases:\nThey gain 1000 Life Points.");
const u8 gCardDescription_SolemnJudgment[] = _("When a monster(s) would be\nSummoned, OR a Spell/Trap Card\nis activated: Pay half your\nLP; negate the Summon or\nactivation, and if you do,\ndestroy that card.");
const u8 gCardDescription_SolemnWishes[] = _("Increase your Life Points by\n500 points each time you draw\na card (or cards).");
const u8 gCardDescription_SoulExchange[] = _("Target 1 monster your opponent\ncontrols; this turn, if you\nTribute a monster, you must\nTribute that target, as if you\ncontrolled it. You cannot\nconduct your Battle Phase the\nturn you activate this card.");
const u8 gCardDescription_SpearDragon[] = _("During battle between this\nattacking card and a Defense\nPosition monster whose DEF is\nlower than the ATK of this\ncard, inflict the difference\nas Battle Damage to your\nopponent. If this card\nattacks, it is changed to\nDefense Position at the end of\nthe Damage Step.");
const u8 gCardDescription_StJoan[] = _("The Forgiving Maiden +\nDarklord Marie");
const u8 gCardDescription_SummonedSkull[] = _("A fiend with dark powers for\nconfusing the enemy. Among the\nFiend-Type monsters, this\nmonster boasts considerable\nforce.(This card is always\ntreated as an Archfiend card.)");
const u8 gCardDescription_SwordsofRevealingLight[] = _("After this card's activation,\nit remains on the field, but\nyou must destroy it during the\nEnd Phase of your opponent's\n3rd turn. When this card is\nactivated: If your opponent\ncontrols a face-down monster,\nflip all monsters they control\nface-up. While this card is\nface-up on the field, your\nopponent's monsters cannot\ndeclare an attack.");
const u8 gCardDescription_TheFiendMegacyber[] = _("If your opponent controls at\nleast 2 more monsters than you\ndo, you can Special Summon\nthis card (from your hand).");
const u8 gCardDescription_TheForcefulSentry[] = _("Look at your opponent's hand.\nSelect 1 card among them and\nreturn it to his/her Deck. The\nDeck is then shuffled.");
const u8 gCardDescription_TheLastWarriorfromAnotherPlanet[] = _("Zombyra the Dark +\nMaryokutaiIf this card is\nSpecial Summoned: Destroy all\nother monsters you control.\nNeither player can Summon\nmonsters.");
const u8 gCardDescription_ThousandEyesRestrict[] = _("Relinquished + Thousand-Eyes\nIdolOther monsters on the\nfield cannot change their\nbattle positions or attack.\nOnce per turn: You can target\n1 monster your opponent\ncontrols; equip that target to\nthis card (max. 1). This\ncard's ATK/DEF become equal to\nthat equipped monster's. If\nthis card would be destroyed\nby battle, destroy that\nequipped monster instead.");
const u8 gCardDescription_ThunderDragon[] = _("You can discard this card; add\nup to 2 Thunder Dragon from\nyour Deck to your hand.");
const u8 gCardDescription_TimeSeal[] = _("Skip the Draw Phase of your\nopponent's next turn.");
const u8 gCardDescription_TorrentialTribute[] = _("When a monster(s) is Summoned:\nDestroy all monsters on the\nfield.");
const u8 gCardDescription_TrapHole[] = _("When your opponent Normal or\nFlip Summons 1 monster with\n1000 or more ATK: Target that\nmonster; destroy that target.");
const u8 gCardDescription_TributetotheDoomed[] = _("Discard 1 card, then target 1\nmonster on the field; destroy\nit.");
const u8 gCardDescription_TwinHeadedThunderDragon[] = _("Thunder Dragon + Thunder\nDragon");
const u8 gCardDescription_UltimateOffering[] = _("During your Main Phase or your\nopponent's Battle Phase: You\ncan pay 500 Life Points;\nimmediately after this effect\nresolves, Normal Summon/Set 1\nmonster.");
const u8 gCardDescription_UnitedWeStand[] = _("The equipped monster gains 800\nATK/DEF for each face-up\nmonster you control.");
const u8 gCardDescription_UpstartGoblin[] = _("Draw 1 card, then your\nopponent gains 1000 LP.");
const u8 gCardDescription_Waboku[] = _("You take no battle damage from\nyour opponent's monsters this\nturn. Your monsters cannot be\ndestroyed by battle this turn.");
const u8 gCardDescription_WallofIllusion[] = _("If this card is attacked by a\nmonster, after damage\ncalculation: Return that\nmonster to the hand.");
const u8 gCardDescription_WhiteMagicalHat[] = _("When this card inflicts Battle\nDamage to your opponent's Life\nPoints, your opponent discards\n1 card randomly from his/her\nhand.");
const u8 gCardDescription_WitchoftheBlackForest[] = _("If this card is sent from the\nfield to the GY: Add 1 monster\nwith 1500 or less DEF from\nyour Deck to your hand, but\nyou cannot activate cards, or\nthe effects of cards, with\nthat name for the rest of this\nturn. You can only use this\neffect of Witch of the Black\nForest once per turn.");
const u8 gCardDescription_YataGarasu[] = _("This card cannot be Special\nSummoned. This card returns to\nits owner's hand during the\nEnd Phase of the turn it is\nNormal Summoned or flipped\nface-up. When this card\ninflicts Battle Damage to your\nopponent, they skip their next\nDraw Phase.");
const u8 gCardDescription_ZombyratheDark[] = _("This card cannot attack your\nopponent directly. If this\ncard destroys a monster by\nbattle: This card loses 200\nATK.");

    [ITEM_4_STARRED_LADYBUG_OF_DOOM] = 1,
    [ITEM_7_COLORED_FISH] = 2,
    [ITEM_AIRKNIGHT_PARSHATH] = 3,
    [ITEM_AQUA_MADOOR] = 4,
    [ITEM_ASURA_PRIEST] = 5,
    [ITEM_BANISHER_OF_THE_LIGHT] = 6,
    [ITEM_BATTLE_OX] = 7,
    [ITEM_BAZOO_THE_SOUL_EATER] = 8,
    [ITEM_BICKURIBOX] = 9,
    [ITEM_BLACK_SKULL_DRAGON] = 10,
    [ITEM_BLUE_EYES_WHITE_DRAGON] = 11,
    [ITEM_BUSTER_BLADER] = 12,
    [ITEM_CALL_OF_THE_HAUNTED] = 13,
    [ITEM_CANNON_SOLDIER] = 14,
    [ITEM_CEASEFIRE] = 15,
    [ITEM_CHANGE_OF_HEART] = 16,
    [ITEM_CONFISCATION] = 17,
    [ITEM_CRASS_CLOWN] = 18,
    [ITEM_CREATURE_SWAP] = 19,
    [ITEM_CYBER_JAR] = 20,
    [ITEM_DARK_BALTER_THE_TERRIBLE] = 21,
    [ITEM_DARK_ELF] = 22,
    [ITEM_DARK_HOLE] = 23,
    [ITEM_DARK_MAGICIAN] = 24,
    [ITEM_DARK_NECROFEAR] = 25,
    [ITEM_DELINQUENT_DUO] = 26,
    [ITEM_DREAM_CLOWN] = 27,
    [ITEM_DUST_TORNADO] = 28,
    [ITEM_EXCHANGE] = 29,
    [ITEM_EXILED_FORCE] = 30,
    [ITEM_EXODIA_THE_FORBIDDEN_ONE] = 31,
    [ITEM_FIBER_JAR] = 32,
    [ITEM_FISSURE] = 33,
    [ITEM_FLAME_SWORDSMAN] = 34,
    [ITEM_GAIA_THE_DRAGON_CHAMPION] = 35,
    [ITEM_GAIA_THE_FIERCE_KNIGHT] = 36,
    [ITEM_GEMINI_ELF] = 37,
    [ITEM_GIANT_GERM] = 38,
    [ITEM_GIANT_RAT] = 39,
    [ITEM_GIANT_SOLDIER_OF_STONE] = 40,
    [ITEM_GIANT_TRUNADE] = 41,
    [ITEM_GIGA_TECH_WOLF] = 42,
    [ITEM_GOBLIN_ATTACK_FORCE] = 43,
    [ITEM_GRACEFUL_CHARITY] = 44,
    [ITEM_HARPIE_S_FEATHER_DUSTER] = 45,
    [ITEM_HEAVY_STORM] = 46,
    [ITEM_IMPERIAL_ORDER] = 47,
    [ITEM_INJECTION_FAIRY_LILY] = 48,
    [ITEM_JAR_OF_GREED] = 49,
    [ITEM_JINZO] = 50,
    [ITEM_JIRAI_GUMO] = 51,
    [ITEM_JUDGE_MAN] = 52,
    [ITEM_JUST_DESSERTS] = 53,
    [ITEM_KURIBOH] = 54,
    [ITEM_KYCOO_THE_GHOST_DESTROYER] = 55,
    [ITEM_LA_JINN_THE_MYSTICAL_GENIE_OF_THE_LAMP] = 56,
    [ITEM_LABYRINTH_TANK] = 57,
    [ITEM_LAST_WILL] = 58,
    [ITEM_LEFT_ARM_OF_THE_FORBIDDEN_ONE] = 59,
    [ITEM_LEFT_LEG_OF_THE_FORBIDDEN_ONE] = 60,
    [ITEM_MAGIC_CYLINDER] = 61,
    [ITEM_MAGIC_JAMMER] = 62,
    [ITEM_MAGICIAN_OF_FAITH] = 63,
    [ITEM_MAN_EATER_BUG] = 64,
    [ITEM_MASK_OF_DARKNESS] = 65,
    [ITEM_MASKED_SORCERER] = 66,
    [ITEM_MECHANICALCHASER] = 67,
    [ITEM_MIRROR_FORCE] = 68,
    [ITEM_MONSTER_REBORN] = 69,
    [ITEM_MORPHING_JAR] = 70,
    [ITEM_MUKA_MUKA] = 71,
    [ITEM_MYSTIC_TOMATO] = 72,
    [ITEM_MYSTICAL_ELF] = 73,
    [ITEM_NEO_THE_MAGIC_SWORDSMAN] = 74,
    [ITEM_NIMBLE_MOMONGA] = 75,
    [ITEM_NOBLEMAN_OF_CROSSOUT] = 76,
    [ITEM_OOKAZI] = 77,
    [ITEM_PAINFUL_CHOICE] = 78,
    [ITEM_PENGUIN_KNIGHT] = 79,
    [ITEM_POLYMERIZATION] = 80,
    [ITEM_POT_OF_GREED] = 81,
    [ITEM_PREMATURE_BURIAL] = 82,
    [ITEM_RAIGEKI] = 83,
    [ITEM_RED_EYES_BLACK_DRAGON] = 84,
    [ITEM_REINFORCEMENTS] = 85,
    [ITEM_RIGHT_ARM_OF_THE_FORBIDDEN_ONE] = 86,
    [ITEM_RIGHT_LEG_OF_THE_FORBIDDEN_ONE] = 87,
    [ITEM_ROBBIN_GOBLIN] = 88,
    [ITEM_RUSH_RECKLESSLY] = 89,
    [ITEM_RYU_SENSHI] = 90,
    [ITEM_SANGAN] = 91,
    [ITEM_SEVEN_TOOLS_OF_THE_BANDIT] = 92,
    [ITEM_SINISTER_SERPENT] = 93,
    [ITEM_SKULL_KNIGHT] = 94,
    [ITEM_SKULL_LAIR] = 95,
    [ITEM_SNATCH_STEAL] = 96,
    [ITEM_SOLEMN_JUDGMENT] = 97,
    [ITEM_SOLEMN_WISHES] = 98,
    [ITEM_SOUL_EXCHANGE] = 99,
    [ITEM_SPEAR_DRAGON] = 100,
    [ITEM_ST_JOAN] = 101,
    [ITEM_SUMMONED_SKULL] = 102,
    [ITEM_SWORDS_OF_REVEALING_LIGHT] = 103,
    [ITEM_THE_FIEND_MEGACYBER] = 104,
    [ITEM_THE_FORCEFUL_SENTRY] = 105,
    [ITEM_THE_LAST_WARRIOR_FROM_ANOTHER_PLANET] = 106,
    [ITEM_THOUSAND_EYES_RESTRICT] = 107,
    [ITEM_THUNDER_DRAGON] = 108,
    [ITEM_TIME_SEAL] = 109,
    [ITEM_TORRENTIAL_TRIBUTE] = 110,
    [ITEM_TRAP_HOLE] = 111,
    [ITEM_TRIBUTE_TO_THE_DOOMED] = 112,
    [ITEM_TWIN_HEADED_THUNDER_DRAGON] = 113,
    [ITEM_ULTIMATE_OFFERING] = 114,
    [ITEM_UNITED_WE_STAND] = 115,
    [ITEM_UPSTART_GOBLIN] = 116,
    [ITEM_WABOKU] = 117,
    [ITEM_WALL_OF_ILLUSION] = 118,
    [ITEM_WHITE_MAGICAL_HAT] = 119,
    [ITEM_WITCH_OF_THE_BLACK_FOREST] = 120,
    [ITEM_YATA_GARASU] = 121,
    [ITEM_ZOMBYRA_THE_DARK] = 122,
