#ifndef GUARD_CONSTANTS_MUGSHOTS_H
#define GUARD_CONSTANTS_MUGSHOTS_H

//Add your mugshot constants here
#define MUGSHOT_WINGULL_ANGRY 0
#define MUGSHOT_BEAUTIFLY_NORMAL 1
#define MUGSHOT_DUSTOX_NORMAL 2
#define MUGSHOT_SEADRA_NORMAL 3

#endif