#ifndef GUARD_CONSTANTS_YGO_H
#define GUARD_CONSTANTS_YGO_H

#define CARD_NONE 0
#define CARD_DARK_MAGICIAN 1
#define CARD_BLUE_EYES_WHITE_DRAGON 2
#define NUM_CARDS 2

#define EFFECT_NONE 0

#define TYPE_NORMAL 0

#define ATTRIBUTE_NONE 0
#define ATTRIBUTE_DARK 1
#define ATTRIBUTE_LIGHT 2

#define RACE_SPELLCASTER 0
#define RACE_DRAGON 0

#endif  // GUARD_CONSTANTS_YGO_H
