#ifndef GUARD_CONSTANTS_YGO_H
#define GUARD_CONSTANTS_YGO_H

#define CARD_NONE 0
#define CARD_BLUE_EYES_WHITE_DRAGON 1
#define CARD_DARK_MAGICIAN 2
#define CARD_RED_EYES_BLACK_DRAGON 3
#define NUM_CARDS 3

#define EFFECT_NONE 0

#define TYPE_NORMAL 0

#define ATTRIBUTE_NONE 0
#define ATTRIBUTE_DARK 1
#define ATTRIBUTE_LIGHT 2

#define RACE_SPELLCASTER 0
#define RACE_DRAGON 1

#define ARCHETYPE_NONE 0
#define ARCHETYPE_DARK_MAGICIAN 1
#define ARCHETYPE_BLUE_EYES 2

#endif  // GUARD_CONSTANTS_YGO_H
