gText_Birch_Welcome::
	.string "Hello, and welcome to Radiant Orange!\p"
	.string "I am Champion Drake of the Orange\n"
	.string "Islands Orange League.\p"
	.string "You are Ash, who is deciding to go\n"
	.string "on an adventure to the Orange Islands.\p"
	.string "You have accepted a job as a part time\n"
	.string "research aide for Professor Ivy as well.\p"
	.string "You've got your hands full!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is my Dragonite.{PAUSE 96}\p"
	.string "When you climb to the top, you will get\n"
	.string "to meet him!\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Along the way, you will come across\n"
	.string "Team Rocket, being up to no good.\p"
	.string "Giovanni has captured Lugia and is\n"
	.string "using it to create thunderstorms to\p"
	.string "divert sailors to their offshore bases\n"
	.string "in the Orange Islands to collect\p"
	.string "supplies.\p"
	.string "You will be tasked with clearing out\n"
	.string "those bases and restoring order to the\p"
	.string "Orange Islands by releasing Lugia from\n"
	.string "Giovanni's control.\p"
	.string "You're a busy guy, so you like to juggle\n"
	.string "impossible tasks. As well as taking the\p"
	.string "Orange League challenge, you made it\n"
	.string "your personal goal to compete in the\p"
	.string "Battle Tower challenges in the newly\n"
	.string "renovated Battle Frontier.\p"
	.string "After earning each gym badge, you are\n"
	.string "determined to at least make the top 16\p"
	.string "in each level of Battle Tower\n"
	.string "competition, starting at level 10 and\p"
	.string "working your way up to level 50.\p"
	.string "You're a real competitor!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
