

InsideOfTruck_EventScript_Clerk_YugiKaiba::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_YUGI_KAIBA
	message gText_YugiKaibaClerk
	waitmessage
	pokemart InsideOfTruck_PokemartYugiKaiba
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartYugiKaiba:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Critter::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_CRITTER
	message gText_CritterClerk
	waitmessage
	pokemart InsideOfTruck_PokemartCritter
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartCritter:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Treasure::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_TREASURE
	message gText_TreasureClerk
	waitmessage
	pokemart InsideOfTruck_PokemartTreasure
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartTreasure:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Imperial::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_IMPERIAL
	message gText_ImperialClerk
	waitmessage
	pokemart InsideOfTruck_PokemartImperial
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartImperial:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Android::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_ANDROID
	message gText_AndroidClerk
	waitmessage
	pokemart InsideOfTruck_PokemartAndroid
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartAndroid:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_JoeyPegasus::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_JOEY_PEGASUS
	message gText_JoeyPegasusClerk
	waitmessage
	pokemart InsideOfTruck_PokemartJoeyPegasus
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartJoeyPegasus:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Fiber::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_FIBER
	message gText_FiberClerk
	waitmessage
	pokemart InsideOfTruck_PokemartFiber
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartFiber:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Yata::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_YATA
	message gText_YataClerk
	waitmessage
	pokemart InsideOfTruck_PokemartYata
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartYata:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Scientist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_SCIENTIST
	message gText_ScientistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartScientist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartScientist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Vampire::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_VAMPIRE
	message gText_VampireClerk
	waitmessage
	pokemart InsideOfTruck_PokemartVampire
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartVampire:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Chaos::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_CHAOS
	message gText_ChaosClerk
	waitmessage
	pokemart InsideOfTruck_PokemartChaos
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartChaos:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Warrior::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_WARRIOR
	message gText_WarriorClerk
	waitmessage
	pokemart InsideOfTruck_PokemartWarrior
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartWarrior:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Goat::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_GOAT
	message gText_GoatClerk
	waitmessage
	pokemart InsideOfTruck_PokemartGoat
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartGoat:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Cyber::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_CYBER
	message gText_CyberClerk
	waitmessage
	pokemart InsideOfTruck_PokemartCyber
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartCyber:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Reaper::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_REAPER
	message gText_ReaperClerk
	waitmessage
	pokemart InsideOfTruck_PokemartReaper
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartReaper:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_ChaosReturn::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_CHAOS_RETURN
	message gText_ChaosReturnClerk
	waitmessage
	pokemart InsideOfTruck_PokemartChaosReturn
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartChaosReturn:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Demise::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_DEMISE
	message gText_DemiseClerk
	waitmessage
	pokemart InsideOfTruck_PokemartDemise
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartDemise:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Trooper::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_TROOPER
	message gText_TrooperClerk
	waitmessage
	pokemart InsideOfTruck_PokemartTrooper
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartTrooper:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Zombie::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_ZOMBIE
	message gText_ZombieClerk
	waitmessage
	pokemart InsideOfTruck_PokemartZombie
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartZombie:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_PerfectCircle::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_PERFECT_CIRCLE
	message gText_PerfectCircleClerk
	waitmessage
	pokemart InsideOfTruck_PokemartPerfectCircle
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartPerfectCircle:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_DADReturn::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_DAD_RETURN
	message gText_DADReturnClerk
	waitmessage
	pokemart InsideOfTruck_PokemartDADReturn
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartDADReturn:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Gladiator::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_GLADIATOR
	message gText_GladiatorClerk
	waitmessage
	pokemart InsideOfTruck_PokemartGladiator
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartGladiator:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_TeleDAD::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_TELEDAD
	message gText_TeleDADClerk
	waitmessage
	pokemart InsideOfTruck_PokemartTeleDAD
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartTeleDAD:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Cat::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_CAT
	message gText_CatClerk
	waitmessage
	pokemart InsideOfTruck_PokemartCat
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartCat:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Edison::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_EDISON
	message gText_EdisonClerk
	waitmessage
	pokemart InsideOfTruck_PokemartEdison
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartEdison:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Frog::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_FROG
	message gText_FrogClerk
	waitmessage
	pokemart InsideOfTruck_PokemartFrog
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartFrog:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Starstrike::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_STARSTRIKE
	message gText_StarstrikeClerk
	waitmessage
	pokemart InsideOfTruck_PokemartStarstrike
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartStarstrike:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Tengu::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_TENGU
	message gText_TenguClerk
	waitmessage
	pokemart InsideOfTruck_PokemartTengu
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartTengu:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_DinoRabbit::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_DINO_RABBIT
	message gText_DinoRabbitClerk
	waitmessage
	pokemart InsideOfTruck_PokemartDinoRabbit
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartDinoRabbit:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_WindUp::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_WIND_UP
	message gText_WindUpClerk
	waitmessage
	pokemart InsideOfTruck_PokemartWindUp
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartWindUp:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Miami::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_MIAMI
	message gText_MiamiClerk
	waitmessage
	pokemart InsideOfTruck_PokemartMiami
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartMiami:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Meadowlands::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_MEADOWLANDS
	message gText_MeadowlandsClerk
	waitmessage
	pokemart InsideOfTruck_PokemartMeadowlands
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartMeadowlands:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_BabyRuler::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_BABY_RULER
	message gText_BabyRulerClerk
	waitmessage
	pokemart InsideOfTruck_PokemartBabyRuler
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartBabyRuler:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_RavineRuler::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_RAVINE_RULER
	message gText_RavineRulerClerk
	waitmessage
	pokemart InsideOfTruck_PokemartRavineRuler
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartRavineRuler:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_FireWater::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_FIRE_WATER
	message gText_FireWaterClerk
	waitmessage
	pokemart InsideOfTruck_PokemartFireWater
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartFireWater:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_HAT::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_HAT
	message gText_HATClerk
	waitmessage
	pokemart InsideOfTruck_PokemartHAT
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartHAT:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_Vegas::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, FORMAT_VEGAS
	message gText_VegasClerk
	waitmessage
	pokemart InsideOfTruck_PokemartVegas
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartVegas:
	pokemartlistend

InsideOfTruck_Text_YugiKaiba:
	.string "Yugi-Kaiba$"

InsideOfTruck_Text_Critter:
	.string "Critter$"

InsideOfTruck_Text_Treasure:
	.string "Treasure$"

InsideOfTruck_Text_Imperial:
	.string "Imperial$"

InsideOfTruck_Text_Android:
	.string "Android$"

InsideOfTruck_Text_JoeyPegasus:
	.string "Joey-Pegasus$"

InsideOfTruck_Text_Fiber:
	.string "Fiber$"

InsideOfTruck_Text_Yata:
	.string "Yata$"

InsideOfTruck_Text_Scientist:
	.string "Scientist$"

InsideOfTruck_Text_Vampire:
	.string "Vampire$"

InsideOfTruck_Text_Chaos:
	.string "Chaos$"

InsideOfTruck_Text_Warrior:
	.string "Warrior$"

InsideOfTruck_Text_Goat:
	.string "Goat$"

InsideOfTruck_Text_Cyber:
	.string "Cyber$"

InsideOfTruck_Text_Reaper:
	.string "Reaper$"

InsideOfTruck_Text_ChaosReturn:
	.string "Chaos Return$"

InsideOfTruck_Text_Demise:
	.string "Demise$"

InsideOfTruck_Text_Trooper:
	.string "Trooper$"

InsideOfTruck_Text_Zombie:
	.string "Zombie$"

InsideOfTruck_Text_PerfectCircle:
	.string "Perfect Circle$"

InsideOfTruck_Text_DADReturn:
	.string "DAD Return$"

InsideOfTruck_Text_Gladiator:
	.string "Gladiator$"

InsideOfTruck_Text_TeleDAD:
	.string "TeleDAD$"

InsideOfTruck_Text_Cat:
	.string "Cat$"

InsideOfTruck_Text_Edison:
	.string "Edison$"

InsideOfTruck_Text_Frog:
	.string "Frog$"

InsideOfTruck_Text_Starstrike:
	.string "Starstrike$"

InsideOfTruck_Text_Tengu:
	.string "Tengu$"

InsideOfTruck_Text_DinoRabbit:
	.string "Dino Rabbit$"

InsideOfTruck_Text_WindUp:
	.string "Wind-Up$"

InsideOfTruck_Text_Miami:
	.string "Miami$"

InsideOfTruck_Text_Meadowlands:
	.string "Meadowlands$"

InsideOfTruck_Text_BabyRuler:
	.string "Baby Ruler$"

InsideOfTruck_Text_RavineRuler:
	.string "Ravine Ruler$"

InsideOfTruck_Text_FireWater:
	.string "Fire-Water$"

InsideOfTruck_Text_HAT:
	.string "HAT$"

InsideOfTruck_Text_Vegas:
	.string "Vegas$"



InsideOfTruck_Text_YugiKaibaBanlist:
	.string "Yugi-Kaiba banlist$"

InsideOfTruck_Text_CritterBanlist:
	.string "Critter banlist$"

InsideOfTruck_Text_TreasureBanlist:
	.string "Treasure banlist$"

InsideOfTruck_Text_ImperialBanlist:
	.string "Imperial banlist$"

InsideOfTruck_Text_AndroidBanlist:
	.string "Android banlist$"

InsideOfTruck_Text_JoeyPegasusBanlist:
	.string "Joey-Pegasus banlist$"

InsideOfTruck_Text_FiberBanlist:
	.string "Fiber banlist$"

InsideOfTruck_Text_YataBanlist:
	.string "Yata banlist$"

InsideOfTruck_Text_ScientistBanlist:
	.string "Scientist banlist$"

InsideOfTruck_Text_VampireBanlist:
	.string "Vampire banlist$"

InsideOfTruck_Text_ChaosBanlist:
	.string "Chaos banlist$"

InsideOfTruck_Text_WarriorBanlist:
	.string "Warrior banlist$"

InsideOfTruck_Text_GoatBanlist:
	.string "Goat banlist$"

InsideOfTruck_Text_CyberBanlist:
	.string "Cyber banlist$"

InsideOfTruck_Text_ReaperBanlist:
	.string "Reaper banlist$"

InsideOfTruck_Text_ChaosReturnBanlist:
	.string "Chaos Return banlist$"

InsideOfTruck_Text_DemiseBanlist:
	.string "Demise banlist$"

InsideOfTruck_Text_TrooperBanlist:
	.string "Trooper banlist$"

InsideOfTruck_Text_ZombieBanlist:
	.string "Zombie banlist$"

InsideOfTruck_Text_PerfectCircleBanlist:
	.string "Perfect Circle banlist$"

InsideOfTruck_Text_DADReturnBanlist:
	.string "DAD Return banlist$"

InsideOfTruck_Text_GladiatorBanlist:
	.string "Gladiator banlist$"

InsideOfTruck_Text_TeleDADBanlist:
	.string "TeleDAD banlist$"

InsideOfTruck_Text_CatBanlist:
	.string "Cat banlist$"

InsideOfTruck_Text_EdisonBanlist:
	.string "Edison banlist$"

InsideOfTruck_Text_FrogBanlist:
	.string "Frog banlist$"

InsideOfTruck_Text_StarstrikeBanlist:
	.string "Starstrike banlist$"

InsideOfTruck_Text_TenguBanlist:
	.string "Tengu banlist$"

InsideOfTruck_Text_DinoRabbitBanlist:
	.string "Dino Rabbit banlist$"

InsideOfTruck_Text_WindUpBanlist:
	.string "Wind-Up banlist$"

InsideOfTruck_Text_MiamiBanlist:
	.string "Miami banlist$"

InsideOfTruck_Text_MeadowlandsBanlist:
	.string "Meadowlands banlist$"

InsideOfTruck_Text_BabyRulerBanlist:
	.string "Baby Ruler banlist$"

InsideOfTruck_Text_RavineRulerBanlist:
	.string "Ravine Ruler banlist$"

InsideOfTruck_Text_FireWaterBanlist:
	.string "Fire-Water banlist$"

InsideOfTruck_Text_HATBanlist:
	.string "HAT banlist$"

InsideOfTruck_Text_VegasBanlist:
	.string "Vegas banlist$"

gText_YugiKaibaClerk::
	.string "Welcome!\p"
	.string "I'm the YugiKaiba clerk.\n"
	.string "How may I serve you?$"

gText_CritterClerk::
	.string "Welcome!\p"
	.string "I'm the Critter clerk.\n"
	.string "How may I serve you?$"

gText_TreasureClerk::
	.string "Welcome!\p"
	.string "I'm the Treasure clerk.\n"
	.string "How may I serve you?$"

gText_ImperialClerk::
	.string "Welcome!\p"
	.string "I'm the Imperial clerk.\n"
	.string "How may I serve you?$"

gText_AndroidClerk::
	.string "Welcome!\p"
	.string "I'm the Android clerk.\n"
	.string "How may I serve you?$"

gText_JoeyPegasusClerk::
	.string "Welcome!\p"
	.string "I'm the JoeyPegasus clerk.\n"
	.string "How may I serve you?$"

gText_FiberClerk::
	.string "Welcome!\p"
	.string "I'm the Fiber clerk.\n"
	.string "How may I serve you?$"

gText_YataClerk::
	.string "Welcome!\p"
	.string "I'm the Yata clerk.\n"
	.string "How may I serve you?$"

gText_ScientistClerk::
	.string "Welcome!\p"
	.string "I'm the Scientist clerk.\n"
	.string "How may I serve you?$"

gText_VampireClerk::
	.string "Welcome!\p"
	.string "I'm the Vampire clerk.\n"
	.string "How may I serve you?$"

gText_ChaosClerk::
	.string "Welcome!\p"
	.string "I'm the Chaos clerk.\n"
	.string "How may I serve you?$"

gText_WarriorClerk::
	.string "Welcome!\p"
	.string "I'm the Warrior clerk.\n"
	.string "How may I serve you?$"

gText_GoatClerk::
	.string "Welcome!\p"
	.string "I'm the Goat clerk.\n"
	.string "How may I serve you?$"

gText_CyberClerk::
	.string "Welcome!\p"
	.string "I'm the Cyber clerk.\n"
	.string "How may I serve you?$"

gText_ReaperClerk::
	.string "Welcome!\p"
	.string "I'm the Reaper clerk.\n"
	.string "How may I serve you?$"

gText_ChaosReturnClerk::
	.string "Welcome!\p"
	.string "I'm the ChaosReturn clerk.\n"
	.string "How may I serve you?$"

gText_DemiseClerk::
	.string "Welcome!\p"
	.string "I'm the Demise clerk.\n"
	.string "How may I serve you?$"

gText_TrooperClerk::
	.string "Welcome!\p"
	.string "I'm the Trooper clerk.\n"
	.string "How may I serve you?$"

gText_ZombieClerk::
	.string "Welcome!\p"
	.string "I'm the Zombie clerk.\n"
	.string "How may I serve you?$"

gText_PerfectCircleClerk::
	.string "Welcome!\p"
	.string "I'm the PerfectCircle clerk.\n"
	.string "How may I serve you?$"

gText_DADReturnClerk::
	.string "Welcome!\p"
	.string "I'm the DADReturn clerk.\n"
	.string "How may I serve you?$"

gText_GladiatorClerk::
	.string "Welcome!\p"
	.string "I'm the Gladiator clerk.\n"
	.string "How may I serve you?$"

gText_TeleDADClerk::
	.string "Welcome!\p"
	.string "I'm the TeleDAD clerk.\n"
	.string "How may I serve you?$"

gText_CatClerk::
	.string "Welcome!\p"
	.string "I'm the Cat clerk.\n"
	.string "How may I serve you?$"

gText_EdisonClerk::
	.string "Welcome!\p"
	.string "I'm the Edison clerk.\n"
	.string "How may I serve you?$"

gText_FrogClerk::
	.string "Welcome!\p"
	.string "I'm the Frog clerk.\n"
	.string "How may I serve you?$"

gText_StarstrikeClerk::
	.string "Welcome!\p"
	.string "I'm the Starstrike clerk.\n"
	.string "How may I serve you?$"

gText_TenguClerk::
	.string "Welcome!\p"
	.string "I'm the Tengu clerk.\n"
	.string "How may I serve you?$"

gText_DinoRabbitClerk::
	.string "Welcome!\p"
	.string "I'm the DinoRabbit clerk.\n"
	.string "How may I serve you?$"

gText_WindUpClerk::
	.string "Welcome!\p"
	.string "I'm the WindUp clerk.\n"
	.string "How may I serve you?$"

gText_MiamiClerk::
	.string "Welcome!\p"
	.string "I'm the Miami clerk.\n"
	.string "How may I serve you?$"

gText_MeadowlandsClerk::
	.string "Welcome!\p"
	.string "I'm the Meadowlands clerk.\n"
	.string "How may I serve you?$"

gText_BabyRulerClerk::
	.string "Welcome!\p"
	.string "I'm the BabyRuler clerk.\n"
	.string "How may I serve you?$"

gText_RavineRulerClerk::
	.string "Welcome!\p"
	.string "I'm the RavineRuler clerk.\n"
	.string "How may I serve you?$"

gText_FireWaterClerk::
	.string "Welcome!\p"
	.string "I'm the FireWater clerk.\n"
	.string "How may I serve you?$"

gText_HATClerk::
	.string "Welcome!\p"
	.string "I'm the HAT clerk.\n"
	.string "How may I serve you?$"

gText_VegasClerk::
	.string "Welcome!\p"
	.string "I'm the Vegas clerk.\n"
	.string "How may I serve you?$"

gText_YugiKaibaBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the YugiKaiba banlist clerk.\n"
	.string "How may I serve you?$"

gText_CritterBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Critter banlist clerk.\n"
	.string "How may I serve you?$"

gText_TreasureBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Treasure banlist clerk.\n"
	.string "How may I serve you?$"

gText_ImperialBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Imperial banlist clerk.\n"
	.string "How may I serve you?$"

gText_AndroidBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Android banlist clerk.\n"
	.string "How may I serve you?$"

gText_JoeyPegasusBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the JoeyPegasus banlist clerk.\n"
	.string "How may I serve you?$"

gText_FiberBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Fiber banlist clerk.\n"
	.string "How may I serve you?$"

gText_YataBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Yata banlist clerk.\n"
	.string "How may I serve you?$"

gText_ScientistBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Scientist banlist clerk.\n"
	.string "How may I serve you?$"

gText_VampireBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Vampire banlist clerk.\n"
	.string "How may I serve you?$"

gText_ChaosBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Chaos banlist clerk.\n"
	.string "How may I serve you?$"

gText_WarriorBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Warrior banlist clerk.\n"
	.string "How may I serve you?$"

gText_GoatBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Goat banlist clerk.\n"
	.string "How may I serve you?$"

gText_CyberBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Cyber banlist clerk.\n"
	.string "How may I serve you?$"

gText_ReaperBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Reaper banlist clerk.\n"
	.string "How may I serve you?$"

gText_ChaosReturnBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the ChaosReturn banlist clerk.\n"
	.string "How may I serve you?$"

gText_DemiseBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Demise banlist clerk.\n"
	.string "How may I serve you?$"

gText_TrooperBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Trooper banlist clerk.\n"
	.string "How may I serve you?$"

gText_ZombieBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Zombie banlist clerk.\n"
	.string "How may I serve you?$"

gText_PerfectCircleBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the PerfectCircle banlist clerk.\n"
	.string "How may I serve you?$"

gText_DADReturnBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the DADReturn banlist clerk.\n"
	.string "How may I serve you?$"

gText_GladiatorBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Gladiator banlist clerk.\n"
	.string "How may I serve you?$"

gText_TeleDADBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the TeleDAD banlist clerk.\n"
	.string "How may I serve you?$"

gText_CatBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Cat banlist clerk.\n"
	.string "How may I serve you?$"

gText_EdisonBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Edison banlist clerk.\n"
	.string "How may I serve you?$"

gText_FrogBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Frog banlist clerk.\n"
	.string "How may I serve you?$"

gText_StarstrikeBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Starstrike banlist clerk.\n"
	.string "How may I serve you?$"

gText_TenguBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Tengu banlist clerk.\n"
	.string "How may I serve you?$"

gText_DinoRabbitBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the DinoRabbit banlist clerk.\n"
	.string "How may I serve you?$"

gText_WindUpBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the WindUp banlist clerk.\n"
	.string "How may I serve you?$"

gText_MiamiBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Miami banlist clerk.\n"
	.string "How may I serve you?$"

gText_MeadowlandsBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Meadowlands banlist clerk.\n"
	.string "How may I serve you?$"

gText_BabyRulerBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the BabyRuler banlist clerk.\n"
	.string "How may I serve you?$"

gText_RavineRulerBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the RavineRuler banlist clerk.\n"
	.string "How may I serve you?$"

gText_FireWaterBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the FireWater banlist clerk.\n"
	.string "How may I serve you?$"

gText_HATBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the HAT banlist clerk.\n"
	.string "How may I serve you?$"

gText_VegasBanlistClerk::
	.string "Welcome!\p"
	.string "I'm the Vegas banlist clerk.\n"
	.string "How may I serve you?$"

InsideOfTruck_EventScript_Clerk_YugiKaibaBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_YUGI_KAIBA
	message gText_YugiKaibaBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartYugiKaibaBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartYugiKaibaBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_CritterBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_CRITTER
	message gText_CritterBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartCritterBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartCritterBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_TreasureBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_TREASURE
	message gText_TreasureBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartTreasureBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartTreasureBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_ImperialBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_IMPERIAL
	message gText_ImperialBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartImperialBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartImperialBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_AndroidBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_ANDROID
	message gText_AndroidBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartAndroidBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartAndroidBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_JoeyPegasusBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_JOEY_PEGASUS
	message gText_JoeyPegasusBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartJoeyPegasusBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartJoeyPegasusBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_FiberBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_FIBER
	message gText_FiberBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartFiberBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartFiberBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_YataBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_YATA
	message gText_YataBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartYataBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartYataBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_ScientistBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_SCIENTIST
	message gText_ScientistBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartScientistBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartScientistBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_VampireBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_VAMPIRE
	message gText_VampireBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartVampireBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartVampireBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_ChaosBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_CHAOS
	message gText_ChaosBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartChaosBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartChaosBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_WarriorBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_WARRIOR
	message gText_WarriorBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartWarriorBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartWarriorBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_GoatBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_GOAT
	message gText_GoatBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartGoatBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartGoatBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_CyberBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_CYBER
	message gText_CyberBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartCyberBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartCyberBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_ReaperBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_REAPER
	message gText_ReaperBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartReaperBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartReaperBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_ChaosReturnBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_CHAOS_RETURN
	message gText_ChaosReturnBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartChaosReturnBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartChaosReturnBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_DemiseBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_DEMISE
	message gText_DemiseBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartDemiseBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartDemiseBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_TrooperBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_TROOPER
	message gText_TrooperBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartTrooperBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartTrooperBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_ZombieBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_ZOMBIE
	message gText_ZombieBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartZombieBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartZombieBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_PerfectCircleBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_PERFECT_CIRCLE
	message gText_PerfectCircleBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartPerfectCircleBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartPerfectCircleBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_DADReturnBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_DAD_RETURN
	message gText_DADReturnBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartDADReturnBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartDADReturnBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_GladiatorBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_GLADIATOR
	message gText_GladiatorBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartGladiatorBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartGladiatorBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_TeleDADBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_TELEDAD
	message gText_TeleDADBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartTeleDADBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartTeleDADBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_CatBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_CAT
	message gText_CatBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartCatBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartCatBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_EdisonBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_EDISON
	message gText_EdisonBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartEdisonBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartEdisonBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_FrogBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_FROG
	message gText_FrogBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartFrogBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartFrogBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_StarstrikeBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_STARSTRIKE
	message gText_StarstrikeBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartStarstrikeBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartStarstrikeBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_TenguBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_TENGU
	message gText_TenguBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartTenguBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartTenguBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_DinoRabbitBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_DINO_RABBIT
	message gText_DinoRabbitBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartDinoRabbitBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartDinoRabbitBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_WindUpBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_WIND_UP
	message gText_WindUpBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartWindUpBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartWindUpBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_MiamiBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_MIAMI
	message gText_MiamiBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartMiamiBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartMiamiBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_MeadowlandsBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_MEADOWLANDS
	message gText_MeadowlandsBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartMeadowlandsBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartMeadowlandsBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_BabyRulerBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_BABY_RULER
	message gText_BabyRulerBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartBabyRulerBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartBabyRulerBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_RavineRulerBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_RAVINE_RULER
	message gText_RavineRulerBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartRavineRulerBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartRavineRulerBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_FireWaterBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_FIRE_WATER
	message gText_FireWaterBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartFireWaterBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartFireWaterBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_HATBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_HAT
	message gText_HATBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartHATBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartHATBanlist:
	pokemartlistend

InsideOfTruck_EventScript_Clerk_VegasBanlist::
	lock
	faceplayer
	setvar VAR_YGO_SHOP, BANLIST_VEGAS
	message gText_VegasBanlistClerk
	waitmessage
	pokemart InsideOfTruck_PokemartVegasBanlist
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	setvar VAR_YGO_SHOP, 0
	release
	end

	.align 2
InsideOfTruck_PokemartVegasBanlist:
	pokemartlistend

	pokemartlistend

