	[BLUE_EYES_WHITE_DRAGON] =
	{
		.name = gCardName_BlueEyesWhiteDragon,
		.nameShort = gCardNameShort_BlueEyesWhiteDragon,
		.description = gCardDescription_BlueEyesWhiteDragon,
		.pic = gCardPicLarge_BlueEyesWhiteDragon_Big,
		.pal = gCardPalLarge_BlueEyesWhiteDragon,
		.iconSquare = gCardIconSquare_BlueEyesWhiteDragon,
		.iconLarge = gCardIconLarge_BlueEyesWhiteDragon,
		.iconSmall = gCardIconSmall_BlueEyesWhiteDragon,
		.effects = {EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE},
		.password = 89631139,
		.type = TYPE_NORMAL,
		.attribute = ATTRIBUTE_LIGHT,
		.level = 8,
		.atk = 300,
		.def = 250,
		.race = RACE_DRAGON,
		.archetypesSeries = {ARCHETYPE_NONE, ARCHETYPE_NONE, ARCHETYPE_NONE},
		.id = 0,
	},
	[DARK_MAGICIAN] =
	{
		.name = gCardName_DarkMagician,
		.nameShort = gCardNameShort_DarkMagician,
		.description = gCardDescription_DarkMagician,
		.pic = gCardPicLarge_DarkMagician_Big,
		.pal = gCardPalLarge_DarkMagician,
		.iconSquare = gCardIconSquare_DarkMagician,
		.iconLarge = gCardIconLarge_DarkMagician,
		.iconSmall = gCardIconSmall_DarkMagician,
		.effects = {EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE},
		.password = 46986414,
		.type = TYPE_NORMAL,
		.attribute = ATTRIBUTE_DARK,
		.level = 7,
		.atk = 250,
		.def = 210,
		.race = RACE_SPELLCASTER,
		.archetypesSeries = {ARCHETYPE_NONE, ARCHETYPE_NONE, ARCHETYPE_NONE},
		.id = 0,
	},
	[RED_EYES_BLACK_DRAGON] =
	{
		.name = gCardName_RedEyesBlackDragon,
		.nameShort = gCardNameShort_RedEyesBlackDragon,
		.description = gCardDescription_RedEyesBlackDragon,
		.pic = gCardPicLarge_RedEyesBlackDragon_Big,
		.pal = gCardPalLarge_RedEyesBlackDragon,
		.iconSquare = gCardIconSquare_RedEyesBlackDragon,
		.iconLarge = gCardIconLarge_RedEyesBlackDragon,
		.iconSmall = gCardIconSmall_RedEyesBlackDragon,
		.effects = {EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE},
		.password = 74677422,
		.type = TYPE_NORMAL,
		.attribute = ATTRIBUTE_DARK,
		.level = 7,
		.atk = 240,
		.def = 200,
		.race = RACE_DRAGON,
		.archetypesSeries = {ARCHETYPE_NONE, ARCHETYPE_NONE, ARCHETYPE_NONE},
		.id = 0,
	},
