const u8 gCardName_Relinquished[] = _("Relinquished");
const u8 gCardNameShort_Relinquished[] = _("Relinquished");
const u8 gCardNameShortBag_Relinquished[] = _("Relinquished");

	[CARD_RELINQUISHED] =
	{
		.name = gCardName_Relinquished,
		.nameShort = gCardNameShort_Relinquished,
		.nameShortBag = gCardNameShortBag_Relinquished,
		.description = gCardDescription_Relinquished,
		.descriptionLines = 17,
		.password = _("64631466"),
		.pic = gCardPicLarge_Relinquished_Big,
		.pal = gCardPalLarge_Relinquished,
		.iconSquare = gCardIconSquare_Relinquished,
		.iconLarge = gCardIconLarge_Relinquished,
		.iconSmall = gCardIconSmall_Relinquished,
		.effects = {EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE, EFFECT_NONE},
		.type = TYPE_RITUAL_EFFECT_MONSTER,
		.attribute = ATTRIBUTE_DARK,
		.level = 1,
		.atk = 0,
		.def = 0,
		.race = RACE_SPELLCASTER,
		.id = 4737,
		.archetypesSeries = {ARCHETYPE_SERIES_NONE, ARCHETYPE_SERIES_NONE, ARCHETYPE_SERIES_NONE},
		.priceChaos = 30,
		.priceGoat = 14,
		.priceDemise = 33,
		.priceCustom = 0,
		.priceVendor1 = 0,
		.priceVendor2 = 0,
		.priceVendor3 = 0,
		.priceVendor4 = 0,
	},
