	[ITEM_PACK_YUGI_KAIBA] =
    {
        .name = _("Yugi-Kaiba"),
        .itemId = ITEM_PACK_YUGI_KAIBA,
        .price = 0,
        .description = sYugiKaibaDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_CRITTER] =
    {
        .name = _("Critter"),
        .itemId = ITEM_PACK_CRITTER,
        .price = 0,
        .description = sCritterDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_TREASURE] =
    {
        .name = _("Treasure"),
        .itemId = ITEM_PACK_TREASURE,
        .price = 0,
        .description = sTreasureDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_IMPERIAL] =
    {
        .name = _("Imperial"),
        .itemId = ITEM_PACK_IMPERIAL,
        .price = 0,
        .description = sImperialDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_ANDROID] =
    {
        .name = _("Android"),
        .itemId = ITEM_PACK_ANDROID,
        .price = 0,
        .description = sAndroidDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_JOEY_PEGASUS] =
    {
        .name = _("Joey-Pegasus"),
        .itemId = ITEM_PACK_JOEY_PEGASUS,
        .price = 0,
        .description = sJoeyPegasusDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_FIBER] =
    {
        .name = _("Fiber"),
        .itemId = ITEM_PACK_FIBER,
        .price = 0,
        .description = sFiberDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_YATA] =
    {
        .name = _("Yata"),
        .itemId = ITEM_PACK_YATA,
        .price = 0,
        .description = sYataDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_SCIENTIST] =
    {
        .name = _("Scientist"),
        .itemId = ITEM_PACK_SCIENTIST,
        .price = 0,
        .description = sScientistDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_VAMPIRE] =
    {
        .name = _("Vampire"),
        .itemId = ITEM_PACK_VAMPIRE,
        .price = 0,
        .description = sVampireDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_CHAOS] =
    {
        .name = _("Chaos"),
        .itemId = ITEM_PACK_CHAOS,
        .price = 0,
        .description = sChaosDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_WARRIOR] =
    {
        .name = _("Warrior"),
        .itemId = ITEM_PACK_WARRIOR,
        .price = 0,
        .description = sWarriorDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_GOAT] =
    {
        .name = _("Goat"),
        .itemId = ITEM_PACK_GOAT,
        .price = 0,
        .description = sGoatDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_CYBER] =
    {
        .name = _("Cyber"),
        .itemId = ITEM_PACK_CYBER,
        .price = 0,
        .description = sCyberDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_REAPER] =
    {
        .name = _("Reaper"),
        .itemId = ITEM_PACK_REAPER,
        .price = 0,
        .description = sReaperDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_CHAOS_RETURN] =
    {
        .name = _("Chaos Return"),
        .itemId = ITEM_PACK_CHAOS_RETURN,
        .price = 0,
        .description = sChaosReturnDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_DEMISE] =
    {
        .name = _("Demise"),
        .itemId = ITEM_PACK_DEMISE,
        .price = 0,
        .description = sDemiseDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_TROOPER] =
    {
        .name = _("Trooper"),
        .itemId = ITEM_PACK_TROOPER,
        .price = 0,
        .description = sTrooperDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_ZOMBIE] =
    {
        .name = _("Zombie"),
        .itemId = ITEM_PACK_ZOMBIE,
        .price = 0,
        .description = sZombieDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_PERFECT_CIRCLE] =
    {
        .name = _("Perfect Circl"),
        .itemId = ITEM_PACK_PERFECT_CIRCLE,
        .price = 0,
        .description = sPerfectCircleDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_DAD_RETURN] =
    {
        .name = _("DAD Return"),
        .itemId = ITEM_PACK_DAD_RETURN,
        .price = 0,
        .description = sDADReturnDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_GLADIATOR] =
    {
        .name = _("Gladiator"),
        .itemId = ITEM_PACK_GLADIATOR,
        .price = 0,
        .description = sGladiatorDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_TELEDAD] =
    {
        .name = _("TeleDAD"),
        .itemId = ITEM_PACK_TELEDAD,
        .price = 0,
        .description = sTeleDADDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_CAT] =
    {
        .name = _("Cat"),
        .itemId = ITEM_PACK_CAT,
        .price = 0,
        .description = sCatDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_EDISON] =
    {
        .name = _("Edison"),
        .itemId = ITEM_PACK_EDISON,
        .price = 0,
        .description = sEdisonDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_FROG] =
    {
        .name = _("Frog"),
        .itemId = ITEM_PACK_FROG,
        .price = 0,
        .description = sFrogDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_STARSTRIKE] =
    {
        .name = _("Starstrike"),
        .itemId = ITEM_PACK_STARSTRIKE,
        .price = 0,
        .description = sStarstrikeDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_TENGU] =
    {
        .name = _("Tengu"),
        .itemId = ITEM_PACK_TENGU,
        .price = 0,
        .description = sTenguDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_DINO_RABBIT] =
    {
        .name = _("Dino Rabbit"),
        .itemId = ITEM_PACK_DINO_RABBIT,
        .price = 0,
        .description = sDinoRabbitDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_WIND_UP] =
    {
        .name = _("Wind-Up"),
        .itemId = ITEM_PACK_WIND_UP,
        .price = 0,
        .description = sWindUpDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_MIAMI] =
    {
        .name = _("Miami"),
        .itemId = ITEM_PACK_MIAMI,
        .price = 0,
        .description = sMiamiDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_MEADOWLANDS] =
    {
        .name = _("Meadowlands"),
        .itemId = ITEM_PACK_MEADOWLANDS,
        .price = 0,
        .description = sMeadowlandsDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_BABY_RULER] =
    {
        .name = _("Baby Ruler"),
        .itemId = ITEM_PACK_BABY_RULER,
        .price = 0,
        .description = sBabyRulerDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_RAVINE_RULER] =
    {
        .name = _("Ravine Ruler"),
        .itemId = ITEM_PACK_RAVINE_RULER,
        .price = 0,
        .description = sRavineRulerDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_FIRE_WATER] =
    {
        .name = _("Fire-Water"),
        .itemId = ITEM_PACK_FIRE_WATER,
        .price = 0,
        .description = sFireWaterDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_HAT] =
    {
        .name = _("HAT"),
        .itemId = ITEM_PACK_HAT,
        .price = 0,
        .description = sHATDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },

	[ITEM_PACK_VEGAS] =
    {
        .name = _("Vegas"),
        .itemId = ITEM_PACK_VEGAS,
        .price = 0,
        .description = sVegasDesc,
        .pocket = POCKET_ITEMS,
        .type = ITEM_USE_FIELD,
        .fieldUseFunc = ItemUseOutOfBattle_Pack,
    },



const u16 PackIdMapping[] = 
{
	[ITEM_PACK_2_PLAYER_STARTER_DECK__YUYA___DECLAN] = 0,
	[ITEM_PACK_2_PLAYER_STARTER_SET] = 1,
	[ITEM_PACK_2013_COLLECTIBLE_TINS_WAVE_1] = 2,
	[ITEM_PACK_2013_COLLECTIBLE_TINS_WAVE_2] = 3,
	[ITEM_PACK_2014_MEGA_TIN_MEGA_PACK] = 4,
	[ITEM_PACK_2014_MEGA_TINS] = 5,
	[ITEM_PACK_2015_MEGA_TIN_MEGA_PACK] = 6,
	[ITEM_PACK_2015_MEGA_TINS] = 7,
	[ITEM_PACK_2016_MEGA_TIN_MEGA_PACK] = 8,
	[ITEM_PACK_2016_MEGA_TINS] = 9,
	[ITEM_PACK_2017_MEGA_TIN_MEGA_PACK] = 10,
	[ITEM_PACK_2017_MEGA_TINS] = 11,
	[ITEM_PACK_2018_MEGA_TIN_MEGA_PACK] = 12,
	[ITEM_PACK_2018_MEGA_TINS] = 13,
	[ITEM_PACK_2019_GOLD_SARCOPHAGUS_TIN] = 14,
	[ITEM_PACK_2019_GOLD_SARCOPHAGUS_TIN_MEGA_PACK] = 15,
	[ITEM_PACK_2020_TIN_OF_LOST_MEMORIES] = 16,
	[ITEM_PACK_2020_TIN_OF_LOST_MEMORIES_MEGA_PACK] = 17,
	[ITEM_PACK_2021_TIN_OF_ANCIENT_BATTLES] = 18,
	[ITEM_PACK_2022_TIN_OF_THE_PHARAOH_S_GODS] = 19,
	[ITEM_PACK_25TH_ANNIVERSARY_RARITY_COLLECTION] = 20,
	[ITEM_PACK_25TH_ANNIVERSARY_RARITY_COLLECTION_II] = 21,
	[ITEM_PACK_25TH_ANNIVERSARY_TIN__DUELING_HEROES] = 22,
	[ITEM_PACK_25TH_ANNIVERSARY_TIN__DUELING_HEROES_MEGA_PACK] = 23,
	[ITEM_PACK_25TH_ANNIVERSARY_TIN__DUELING_MIRRORS] = 24,
	[ITEM_PACK_25TH_ANNIVERSARY_ULTIMATE_KAIBA_SET] = 25,
	[ITEM_PACK_ABSOLUTE_POWERFORCE] = 26,
	[ITEM_PACK_ABSOLUTE_POWERFORCE_SNEAK_PEEK_PARTICIPATION_CARD] = 27,
	[ITEM_PACK_ABSOLUTE_POWERFORCE__SPECIAL_EDITION] = 28,
	[ITEM_PACK_ABYSS_RISING] = 29,
	[ITEM_PACK_ABYSS_RISING_SNEAK_PEEK_PARTICIPATION_CARD] = 30,
	[ITEM_PACK_ABYSS_RISING__SPECIAL_EDITION] = 31,
	[ITEM_PACK_ADVANCED_DEMO_DECK_EXTRA_PACK] = 32,
	[ITEM_PACK_AGE_OF_OVERLORD] = 33,
	[ITEM_PACK_ALLIANCE_INSIGHT] = 34,
	[ITEM_PACK_AMAZING_DEFENDERS] = 35,
	[ITEM_PACK_ANCIENT_GUARDIANS] = 36,
	[ITEM_PACK_ANCIENT_PROPHECY] = 37,
	[ITEM_PACK_ANCIENT_PROPHECY_SNEAK_PEEK_PARTICIPATION_CARD] = 38,
	[ITEM_PACK_ANCIENT_PROPHECY__SPECIAL_EDITION] = 39,
	[ITEM_PACK_ANCIENT_SANCTUARY] = 40,
	[ITEM_PACK_ANNIVERSARY_PACK] = 41,
	[ITEM_PACK_ASTRAL_PACK_EIGHT] = 42,
	[ITEM_PACK_ASTRAL_PACK_FIVE] = 43,
	[ITEM_PACK_ASTRAL_PACK_FOUR] = 44,
	[ITEM_PACK_ASTRAL_PACK_ONE] = 45,
	[ITEM_PACK_ASTRAL_PACK_SEVEN] = 46,
	[ITEM_PACK_ASTRAL_PACK_SIX] = 47,
	[ITEM_PACK_ASTRAL_PACK_THREE] = 48,
	[ITEM_PACK_ASTRAL_PACK_TWO] = 49,
	[ITEM_PACK_BATTLE_PACK_2__WAR_OF_THE_GIANTS] = 50,
	[ITEM_PACK_BATTLE_PACK_3__MONSTER_LEAGUE] = 51,
	[ITEM_PACK_BATTLE_PACK_TOURNAMENT_PRIZE_CARDS] = 52,
	[ITEM_PACK_BATTLE_PACK__EPIC_DAWN] = 53,
	[ITEM_PACK_BATTLE_OF_CHAOS] = 54,
	[ITEM_PACK_BATTLES_OF_LEGEND__ARMAGEDDON] = 55,
	[ITEM_PACK_BATTLES_OF_LEGEND__CHAPTER_1] = 56,
	[ITEM_PACK_BATTLES_OF_LEGEND__CRYSTAL_REVENGE] = 57,
	[ITEM_PACK_BATTLES_OF_LEGEND__HERO_S_REVENGE] = 58,
	[ITEM_PACK_BATTLES_OF_LEGEND__LIGHT_S_REVENGE] = 59,
	[ITEM_PACK_BATTLES_OF_LEGEND__MONSTER_MAYHEM] = 60,
	[ITEM_PACK_BATTLES_OF_LEGEND__MONSTROUS_REVENGE] = 61,
	[ITEM_PACK_BATTLES_OF_LEGEND__RELENTLESS_REVENGE] = 62,
	[ITEM_PACK_BATTLES_OF_LEGEND__TERMINAL_REVENGE] = 63,
	[ITEM_PACK_BLAZING_VORTEX] = 64,
	[ITEM_PACK_BLAZING_VORTEX_PREMIERE__PROMOTIONAL_CARD] = 65,
	[ITEM_PACK_BLUE_EYES_ALTERNATIVE_WHITE_DRAGON_SWEEPSTAKES] = 66,
	[ITEM_PACK_BOOSTER_PACK_COLLECTORS_TINS_2002] = 67,
	[ITEM_PACK_BREAKERS_OF_SHADOW] = 68,
	[ITEM_PACK_BREAKERS_OF_SHADOW_SNEAK_PEEK_PARTICIPATION_CARD] = 69,
	[ITEM_PACK_BREAKERS_OF_SHADOW__SPECIAL_EDITION] = 70,
	[ITEM_PACK_BROTHERS_OF_LEGEND] = 71,
	[ITEM_PACK_BURST_OF_DESTINY] = 72,
	[ITEM_PACK_CHAMPION_PACK__GAME_EIGHT] = 73,
	[ITEM_PACK_CHAMPION_PACK__GAME_FIVE] = 74,
	[ITEM_PACK_CHAMPION_PACK__GAME_FOUR] = 75,
	[ITEM_PACK_CHAMPION_PACK__GAME_ONE] = 76,
	[ITEM_PACK_CHAMPION_PACK__GAME_SEVEN] = 77,
	[ITEM_PACK_CHAMPION_PACK__GAME_SIX] = 78,
	[ITEM_PACK_CHAMPION_PACK__GAME_THREE] = 79,
	[ITEM_PACK_CHAMPION_PACK__GAME_TWO] = 80,
	[ITEM_PACK_CHAOS_IMPACT] = 81,
	[ITEM_PACK_CHAOS_IMPACT_SNEAK_PEEK_PARTICIPATION_CARD] = 82,
	[ITEM_PACK_CHAOS_IMPACT_SPECIAL_EDITION] = 83,
	[ITEM_PACK_CIRCUIT_BREAK] = 84,
	[ITEM_PACK_CIRCUIT_BREAK_SNEAK_PEEK_PARTICIPATION_CARD] = 85,
	[ITEM_PACK_CIRCUIT_BREAK_SPECIAL_EDITION] = 86,
	[ITEM_PACK_CLASH_OF_REBELLIONS] = 87,
	[ITEM_PACK_CLASH_OF_REBELLIONS_SNEAK_PEEK_PARTICIPATION_CARD] = 88,
	[ITEM_PACK_CLASH_OF_REBELLIONS__SPECIAL_EDITION] = 89,
	[ITEM_PACK_CODE_OF_THE_DUELIST] = 90,
	[ITEM_PACK_CODE_OF_THE_DUELIST_SNEAK_PEEK_PARTICIPATION_CARD] = 91,
	[ITEM_PACK_CODE_OF_THE_DUELIST_SPECIAL_EDITION] = 92,
	[ITEM_PACK_COLLECTIBLE_TINS_2003] = 93,
	[ITEM_PACK_COLLECTIBLE_TINS_2004] = 94,
	[ITEM_PACK_COLLECTIBLE_TINS_2005] = 95,
	[ITEM_PACK_COLLECTIBLE_TINS_2006_WAVE_1] = 96,
	[ITEM_PACK_COLLECTIBLE_TINS_2006_WAVE_2] = 97,
	[ITEM_PACK_COLLECTIBLE_TINS_2007_WAVE_1] = 98,
	[ITEM_PACK_COLLECTIBLE_TINS_2007_WAVE_2] = 99,
	[ITEM_PACK_COLLECTIBLE_TINS_2008_WAVE_1] = 100,
	[ITEM_PACK_COLLECTIBLE_TINS_2008_WAVE_2] = 101,
	[ITEM_PACK_COLLECTIBLE_TINS_2009_WAVE_1] = 102,
	[ITEM_PACK_COLLECTIBLE_TINS_2009_WAVE_2] = 103,
	[ITEM_PACK_COLLECTIBLE_TINS_2010_WAVE_1] = 104,
	[ITEM_PACK_COLLECTIBLE_TINS_2010_WAVE_2] = 105,
	[ITEM_PACK_COLLECTIBLE_TINS_2011_WAVE_1] = 106,
	[ITEM_PACK_COLLECTIBLE_TINS_2011_WAVE_2] = 107,
	[ITEM_PACK_COLLECTIBLE_TINS_2012_WAVE_1] = 108,
	[ITEM_PACK_COLLECTIBLE_TINS_2012_WAVE_2] = 109,
	[ITEM_PACK_COLLECTIBLE_TINS_2012_WAVE_2_5] = 110,
	[ITEM_PACK_COLLECTIBLE_TINS_EXCLUSIVE_2008] = 111,
	[ITEM_PACK_COLLECTIBLE_TINS_EXCLUSIVE_2009] = 112,
	[ITEM_PACK_COSMO_BLAZER] = 113,
	[ITEM_PACK_COSMO_BLAZER_SNEAK_PEEK_PARTICIPATION_CARD] = 114,
	[ITEM_PACK_COSMO_BLAZER__SPECIAL_EDITION] = 115,
	[ITEM_PACK_CRIMSON_CRISIS] = 116,
	[ITEM_PACK_CRIMSON_CRISIS_SNEAK_PEEK_PARTICIPATION_CARD] = 117,
	[ITEM_PACK_CRIMSON_CRISIS__SPECIAL_EDITION] = 118,
	[ITEM_PACK_CROSSED_SOULS] = 119,
	[ITEM_PACK_CROSSED_SOULS_SNEAK_PEEK_PARTICIPATION_CARD] = 120,
	[ITEM_PACK_CROSSED_SOULS__ADVANCE_EDITION] = 121,
	[ITEM_PACK_CROSSOVER_BREAKERS] = 122,
	[ITEM_PACK_CROSSROADS_OF_CHAOS] = 123,
	[ITEM_PACK_CROSSROADS_OF_CHAOS_SNEAK_PEEK_PARTICIPATION_CARD] = 124,
	[ITEM_PACK_CROSSROADS_OF_CHAOS__SPECIAL_EDITION] = 125,
	[ITEM_PACK_CYBER_DRAGON_REVOLUTION_STRUCTURE_DECK] = 126,
	[ITEM_PACK_CYBERDARK_IMPACT] = 127,
	[ITEM_PACK_CYBERDARK_IMPACT_SNEAK_PEEK_PARTICIPATION_CARD] = 128,
	[ITEM_PACK_CYBERNETIC_HORIZON] = 129,
	[ITEM_PACK_CYBERNETIC_HORIZON_SNEAK_PEEK_PARTICIPATION_CARD] = 130,
	[ITEM_PACK_CYBERNETIC_HORIZON_SPECIAL_EDITION] = 131,
	[ITEM_PACK_CYBERNETIC_REVOLUTION] = 132,
	[ITEM_PACK_CYBERNETIC_REVOLUTION_SNEAK_PEEK_PARTICIPATION_CARD] = 133,
	[ITEM_PACK_CYBERSTORM_ACCESS] = 134,
	[ITEM_PACK_DARK_BEGINNING_1] = 135,
	[ITEM_PACK_DARK_BEGINNING_2] = 136,
	[ITEM_PACK_DARK_CRISIS] = 137,
	[ITEM_PACK_DARK_LEGENDS] = 138,
	[ITEM_PACK_DARK_LEGION_STARTER_DECK] = 139,
	[ITEM_PACK_DARK_NEOSTORM] = 140,
	[ITEM_PACK_DARK_NEOSTORM_SNEAK_PEEK_PARTICIPATION_CARD] = 141,
	[ITEM_PACK_DARK_NEOSTORM_SPECIAL_EDITION] = 142,
	[ITEM_PACK_DARK_REVELATION_VOLUME_1] = 143,
	[ITEM_PACK_DARK_REVELATION_VOLUME_2] = 144,
	[ITEM_PACK_DARK_REVELATION_VOLUME_3] = 145,
	[ITEM_PACK_DARK_REVELATION_VOLUME_4] = 146,
	[ITEM_PACK_DARK_SAVIORS] = 147,
	[ITEM_PACK_DARKWING_BLAST] = 148,
	[ITEM_PACK_DAWN_OF_MAJESTY] = 149,
	[ITEM_PACK_DAWN_OF_MAJESTY_PREMIERE__PROMOTIONAL_CARD] = 150,
	[ITEM_PACK_DEMO_DECK_2015] = 151,
	[ITEM_PACK_DEMO_DECK_2016] = 152,
	[ITEM_PACK_DEMO_PACK] = 153,
	[ITEM_PACK_DESTINY_SOLDIERS] = 154,
	[ITEM_PACK_DIMENSION_FORCE] = 155,
	[ITEM_PACK_DIMENSION_OF_CHAOS] = 156,
	[ITEM_PACK_DIMENSION_OF_CHAOS_SNEAK_PEEK_PARTICIPATION_CARD] = 157,
	[ITEM_PACK_DIMENSION_OF_CHAOS__SPECIAL_EDITION] = 158,
	[ITEM_PACK_DINOSMASHER_S_FURY_STRUCTURE_DECK] = 159,
	[ITEM_PACK_DRAGONS_COLLIDE_STRUCTURE_DECK] = 160,
	[ITEM_PACK_DRAGONS_OF_LEGEND] = 161,
	[ITEM_PACK_DRAGONS_OF_LEGEND_2] = 162,
	[ITEM_PACK_DRAGONS_OF_LEGEND__THE_COMPLETE_SERIES] = 163,
	[ITEM_PACK_DRAGONS_OF_LEGEND__UNLEASHED] = 164,
	[ITEM_PACK_DRAGUNITY_LEGION_STRUCTURE_DECK] = 165,
	[ITEM_PACK_DUEL_DEVASTATOR] = 166,
	[ITEM_PACK_DUEL_DISK___YUSEI_VERSION] = 167,
	[ITEM_PACK_DUEL_MASTER_S_GUIDE_PROMOTIONAL_CARDS] = 168,
	[ITEM_PACK_DUEL_OVERLOAD] = 169,
	[ITEM_PACK_DUEL_POWER] = 170,
	[ITEM_PACK_DUEL_TERMINAL___PREVIEW_WAVE_1] = 171,
	[ITEM_PACK_DUEL_TERMINAL___PREVIEW_WAVE_2] = 172,
	[ITEM_PACK_DUEL_TERMINAL_1] = 173,
	[ITEM_PACK_DUEL_TERMINAL_2] = 174,
	[ITEM_PACK_DUEL_TERMINAL_3] = 175,
	[ITEM_PACK_DUEL_TERMINAL_4] = 176,
	[ITEM_PACK_DUEL_TERMINAL_5] = 177,
	[ITEM_PACK_DUEL_TERMINAL_5A] = 178,
	[ITEM_PACK_DUEL_TERMINAL_5B] = 179,
	[ITEM_PACK_DUEL_TERMINAL_6] = 180,
	[ITEM_PACK_DUEL_TERMINAL_6A] = 181,
	[ITEM_PACK_DUEL_TERMINAL_6B] = 182,
	[ITEM_PACK_DUEL_TERMINAL_7] = 183,
	[ITEM_PACK_DUEL_TERMINAL_7A] = 184,
	[ITEM_PACK_DUEL_TERMINAL_7B] = 185,
	[ITEM_PACK_DUELIST_ALLIANCE] = 186,
	[ITEM_PACK_DUELIST_ALLIANCE_SNEAK_PEEK_PARTICIPATION_CARD] = 187,
	[ITEM_PACK_DUELIST_ALLIANCE__DELUXE_EDITION] = 188,
	[ITEM_PACK_DUELIST_LEAGUE_13_PARTICIPATION_CARDS] = 189,
	[ITEM_PACK_DUELIST_LEAGUE_14_PARTICIPATION_CARDS] = 190,
	[ITEM_PACK_DUELIST_LEAGUE_15_PARTICIPATION_CARDS] = 191,
	[ITEM_PACK_DUELIST_LEAGUE_16_PARTICIPATION_CARDS] = 192,
	[ITEM_PACK_DUELIST_LEAGUE_17_PARTICIPATION_CARDS] = 193,
	[ITEM_PACK_DUELIST_LEAGUE_18_PARTICIPATION_CARDS] = 194,
	[ITEM_PACK_DUELIST_LEAGUE_2_PARTICIPATION_CARDS] = 195,
	[ITEM_PACK_DUELIST_LEAGUE_2010_PARTICIPATION_CARDS] = 196,
	[ITEM_PACK_DUELIST_LEAGUE_3_PARTICIPATION_CARDS] = 197,
	[ITEM_PACK_DUELIST_LEAGUE_DEMO_2010] = 198,
	[ITEM_PACK_DUELIST_LEAGUE_SERIES_1_PARTICIPATION_CARDS] = 199,
	[ITEM_PACK_DUELIST_LEAGUE_SERIES_10_PARTICIPATION_CARD] = 200,
	[ITEM_PACK_DUELIST_LEAGUE_SERIES_2_PARTICIPATION_CARDS] = 201,
	[ITEM_PACK_DUELIST_LEAGUE_SERIES_3_PARTICIPATION_CARD] = 202,
	[ITEM_PACK_DUELIST_LEAGUE_SERIES_4_PARTICIPATION_CARD] = 203,
	[ITEM_PACK_DUELIST_LEAGUE_SERIES_5_PARTICIPATION_CARD] = 204,
	[ITEM_PACK_DUELIST_LEAGUE_SERIES_6_PARTICIPATION_CARD] = 205,
	[ITEM_PACK_DUELIST_LEAGUE_SERIES_7_PARTICIPATION_CARD] = 206,
	[ITEM_PACK_DUELIST_LEAGUE_SERIES_8_PARTICIPATION_CARD] = 207,
	[ITEM_PACK_DUELIST_LEAGUE_SERIES_9_PARTICIPATION_CARD] = 208,
	[ITEM_PACK_DUELIST_NEXUS] = 209,
	[ITEM_PACK_DUELIST_PACK_COLLECTION_TIN_2008] = 210,
	[ITEM_PACK_DUELIST_PACK_COLLECTION_TIN_2009] = 211,
	[ITEM_PACK_DUELIST_PACK_COLLECTION_TIN_2010] = 212,
	[ITEM_PACK_DUELIST_PACK_COLLECTION_TIN_2011] = 213,
	[ITEM_PACK_DUELIST_PACK_COLLECTION_TIN__JADEN_YUKI] = 214,
	[ITEM_PACK_DUELIST_PACK__ASTER_PHOENIX] = 215,
	[ITEM_PACK_DUELIST_PACK__BATTLE_CITY] = 216,
	[ITEM_PACK_DUELIST_PACK__CHAZZ_PRINCETON] = 217,
	[ITEM_PACK_DUELIST_PACK__CROW] = 218,
	[ITEM_PACK_DUELIST_PACK__DIMENSIONAL_GUARDIANS] = 219,
	[ITEM_PACK_DUELIST_PACK__JADEN_YUKI] = 220,
	[ITEM_PACK_DUELIST_PACK__JADEN_YUKI_2] = 221,
	[ITEM_PACK_DUELIST_PACK__JADEN_YUKI_3] = 222,
	[ITEM_PACK_DUELIST_PACK__JESSE_ANDERSON] = 223,
	[ITEM_PACK_DUELIST_PACK__KAIBA] = 224,
	[ITEM_PACK_DUELIST_PACK__RIVALS_OF_THE_PHARAOH] = 225,
	[ITEM_PACK_DUELIST_PACK__SPECIAL_EDITION] = 226,
	[ITEM_PACK_DUELIST_PACK__YUGI] = 227,
	[ITEM_PACK_DUELIST_PACK__YUSEI] = 228,
	[ITEM_PACK_DUELIST_PACK__YUSEI_2] = 229,
	[ITEM_PACK_DUELIST_PACK__YUSEI_3] = 230,
	[ITEM_PACK_DUELIST_PACK__ZANE_TRUESDALE] = 231,
	[ITEM_PACK_DUELIST_REVOLUTION] = 232,
	[ITEM_PACK_DUELIST_REVOLUTION_SNEAK_PEEK_PARTICIPATION_CARD] = 233,
	[ITEM_PACK_DUELIST_REVOLUTION__SPECIAL_EDITION] = 234,
	[ITEM_PACK_DUELIST_SAGA] = 235,
	[ITEM_PACK_DUELIST_S_ADVANCE] = 236,
	[ITEM_PACK_EGYPTIAN_GOD_DECK__OBELISK_THE_TORMENTOR] = 237,
	[ITEM_PACK_EGYPTIAN_GOD_DECK__SLIFER_THE_SKY_DRAGON] = 238,
	[ITEM_PACK_ELEMENTAL_ENERGY] = 239,
	[ITEM_PACK_ELEMENTAL_ENERGY_SNEAK_PEEK_PARTICIPATION_CARD] = 240,
	[ITEM_PACK_ELEMENTAL_ENERGY__SPECIAL_EDITION] = 241,
	[ITEM_PACK_EMPEROR_OF_DARKNESS_STRUCTURE_DECK] = 242,
	[ITEM_PACK_ENEMY_OF_JUSTICE] = 243,
	[ITEM_PACK_ENEMY_OF_JUSTICE_SNEAK_PEEK_PARTICIPATION_CARD] = 244,
	[ITEM_PACK_ETERNITY_CODE] = 245,
	[ITEM_PACK_ETERNITY_CODE_PREMIERE__PROMOTIONAL_CARD] = 246,
	[ITEM_PACK_EVENT_PACK_SPEED_DUEL] = 247,
	[ITEM_PACK_EXCLUSIVE_PACK] = 248,
	[ITEM_PACK_EXTREME_FORCE] = 249,
	[ITEM_PACK_EXTREME_FORCE_SNEAK_PEEK_PARTICIPATION_CARD] = 250,
	[ITEM_PACK_EXTREME_FORCE_SPECIAL_EDITION] = 251,
	[ITEM_PACK_EXTREME_VICTORY] = 252,
	[ITEM_PACK_EXTREME_VICTORY_SNEAK_PEEK_PARTICIPATION_CARD] = 253,
	[ITEM_PACK_FIRE_FISTS__SPECIAL_EDITION] = 254,
	[ITEM_PACK_FISTS_OF_THE_GADGETS] = 255,
	[ITEM_PACK_FLAMES_OF_DESTRUCTION] = 256,
	[ITEM_PACK_FLAMES_OF_DESTRUCTION_SNEAK_PEEK_PARTICIPATION_CARD] = 257,
	[ITEM_PACK_FLAMES_OF_DESTRUCTION_SPECIAL_EDITION] = 258,
	[ITEM_PACK_FLAMING_ETERNITY] = 259,
	[ITEM_PACK_FLAMING_ETERNITY_SNEAK_PEEK_PARTICIPATION_CARD] = 260,
	[ITEM_PACK_FORBIDDEN_LEGACY] = 261,
	[ITEM_PACK_FORCE_OF_THE_BREAKER] = 262,
	[ITEM_PACK_FORCE_OF_THE_BREAKER_SNEAK_PEEK_PARTICIPATION_CARD] = 263,
	[ITEM_PACK_FORCE_OF_THE_BREAKER__SPECIAL_EDITION] = 264,
	[ITEM_PACK_FUSION_ENFORCERS] = 265,
	[ITEM_PACK_GX_NEXT_GENERATION] = 266,
	[ITEM_PACK_GALACTIC_OVERLORD] = 267,
	[ITEM_PACK_GALACTIC_OVERLORD_SNEAK_PEEK_PARTICIPATION_CARD] = 268,
	[ITEM_PACK_GATES_OF_THE_UNDERWORLD_STRUCTURE_DECK] = 269,
	[ITEM_PACK_GEARGIA_RAMPAGE_STRUCTURE_DECK] = 270,
	[ITEM_PACK_GENERATION_FORCE] = 271,
	[ITEM_PACK_GENERATION_FORCE_SNEAK_PEEK_PARTICIPATION_CARD] = 272,
	[ITEM_PACK_GENERATION_FORCE__SPECIAL_EDITION] = 273,
	[ITEM_PACK_GENESIS_IMPACT] = 274,
	[ITEM_PACK_GHOSTS_FROM_THE_PAST] = 275,
	[ITEM_PACK_GHOSTS_FROM_THE_PAST__THE_2ND_HAUNTING] = 276,
	[ITEM_PACK_GLADIATOR_S_ASSAULT] = 277,
	[ITEM_PACK_GLADIATOR_S_ASSAULT_SNEAK_PEEK_PARTICIPATION_CARD] = 278,
	[ITEM_PACK_GLADIATOR_S_ASSAULT__SPECIAL_EDITION] = 279,
	[ITEM_PACK_GOLD_SERIES] = 280,
	[ITEM_PACK_GOLD_SERIES_2009] = 281,
	[ITEM_PACK_GOLD_SERIES_3] = 282,
	[ITEM_PACK_GOLD_SERIES_4__PYRAMIDS_EDITION] = 283,
	[ITEM_PACK_GOLD_SERIES__HAUNTED_MINE] = 284,
	[ITEM_PACK_HERO_STRIKE_STRUCTURE_DECK] = 285,
	[ITEM_PACK_HIDDEN_ARSENAL] = 286,
	[ITEM_PACK_HIDDEN_ARSENAL_2] = 287,
	[ITEM_PACK_HIDDEN_ARSENAL_3] = 288,
	[ITEM_PACK_HIDDEN_ARSENAL_4__TRISHULA_S_TRIUMPH] = 289,
	[ITEM_PACK_HIDDEN_ARSENAL_5__STEELSWARM_INVASION] = 290,
	[ITEM_PACK_HIDDEN_ARSENAL_5__STEELSWARM_INVASION__SPECIAL_EDITION] = 291,
	[ITEM_PACK_HIDDEN_ARSENAL_6__OMEGA_XYZ] = 292,
	[ITEM_PACK_HIDDEN_ARSENAL_7__KNIGHT_OF_STARS] = 293,
	[ITEM_PACK_HIDDEN_ARSENAL__CHAPTER_1] = 294,
	[ITEM_PACK_HIDDEN_ARSENAL__SPECIAL_EDITION] = 295,
	[ITEM_PACK_HIDDEN_SUMMONERS] = 296,
	[ITEM_PACK_HIGH_SPEED_RIDERS] = 297,
	[ITEM_PACK_HOBBY_LEAGUE_1_PARTICIPATION_CARDS_A] = 298,
	[ITEM_PACK_HOBBY_LEAGUE_1_PARTICIPATION_CARDS_B] = 299,
	[ITEM_PACK_HOBBY_LEAGUE_1_PARTICIPATION_CARDS_C] = 300,
	[ITEM_PACK_HOBBY_LEAGUE_2_PARTICIPATION_CARD_A] = 301,
	[ITEM_PACK_HOBBY_LEAGUE_2_PARTICIPATION_CARD_B] = 302,
	[ITEM_PACK_HOBBY_LEAGUE_2_PARTICIPATION_CARD_C] = 303,
	[ITEM_PACK_HOBBY_LEAGUE_2_PARTICIPATION_CARD_D] = 304,
	[ITEM_PACK_HOBBY_LEAGUE_2_PARTICIPATION_CARD_E] = 305,
	[ITEM_PACK_HOBBY_LEAGUE_2_PARTICIPATION_CARD_F] = 306,
	[ITEM_PACK_HOBBY_LEAGUE_3_PARTICIPATION_CARD_A] = 307,
	[ITEM_PACK_HOBBY_LEAGUE_3_PARTICIPATION_CARD_B] = 308,
	[ITEM_PACK_HOBBY_LEAGUE_3_PARTICIPATION_CARD_C] = 309,
	[ITEM_PACK_HOBBY_LEAGUE_3_PARTICIPATION_CARD_D] = 310,
	[ITEM_PACK_HOBBY_LEAGUE_3_PARTICIPATION_CARD_E] = 311,
	[ITEM_PACK_HOBBY_LEAGUE_3_PARTICIPATION_CARD_F] = 312,
	[ITEM_PACK_HOBBY_LEAGUE_3_PARTICIPATION_CARD_G] = 313,
	[ITEM_PACK_HOBBY_LEAGUE_4_PARTICIPATION_CARD_A] = 314,
	[ITEM_PACK_HOBBY_LEAGUE_4_PARTICIPATION_CARD_B] = 315,
	[ITEM_PACK_HOBBY_LEAGUE_4_PARTICIPATION_CARD_C] = 316,
	[ITEM_PACK_HOBBY_LEAGUE_4_PARTICIPATION_CARD_D] = 317,
	[ITEM_PACK_HOBBY_LEAGUE_4_PARTICIPATION_CARD_E] = 318,
	[ITEM_PACK_HOBBY_LEAGUE_4_PARTICIPATION_CARD_F] = 319,
	[ITEM_PACK_HOBBY_LEAGUE_5_PARTICIPATION_CARD_A] = 320,
	[ITEM_PACK_HOBBY_LEAGUE_5_PARTICIPATION_CARD_B] = 321,
	[ITEM_PACK_HOBBY_LEAGUE_5_PARTICIPATION_CARD_C] = 322,
	[ITEM_PACK_HOBBY_LEAGUE_5_PARTICIPATION_CARD_D] = 323,
	[ITEM_PACK_HOBBY_LEAGUE_5_PARTICIPATION_CARD_E] = 324,
	[ITEM_PACK_HOBBY_LEAGUE_5_PARTICIPATION_CARD_F] = 325,
	[ITEM_PACK_HOBBY_LEAGUE_6_PARTICIPATION_CARD_A] = 326,
	[ITEM_PACK_HOBBY_LEAGUE_6_PARTICIPATION_CARD_B] = 327,
	[ITEM_PACK_HOBBY_LEAGUE_6_PARTICIPATION_CARD_C] = 328,
	[ITEM_PACK_HOBBY_LEAGUE_6_PARTICIPATION_CARD_D] = 329,
	[ITEM_PACK_HOBBY_LEAGUE_6_PARTICIPATION_CARD_E] = 330,
	[ITEM_PACK_HOBBY_LEAGUE_6_PARTICIPATION_CARD_F] = 331,
	[ITEM_PACK_HOBBY_LEAGUE_7_PARTICIPATION_CARD_A] = 332,
	[ITEM_PACK_HOBBY_LEAGUE_7_PARTICIPATION_CARD_B] = 333,
	[ITEM_PACK_HOBBY_LEAGUE_7_PARTICIPATION_CARD_C] = 334,
	[ITEM_PACK_HOBBY_LEAGUE_7_PARTICIPATION_CARD_D] = 335,
	[ITEM_PACK_HOBBY_LEAGUE_7_PARTICIPATION_CARD_E] = 336,
	[ITEM_PACK_HOBBY_LEAGUE_7_PARTICIPATION_CARD_F] = 337,
	[ITEM_PACK_IGNITION_ASSAULT] = 338,
	[ITEM_PACK_IGNITION_ASSAULT_SNEAK_PEEK_PARTICIPATION_CARD] = 339,
	[ITEM_PACK_IGNITION_ASSAULT_SPECIAL_EDITION] = 340,
	[ITEM_PACK_INVASION_OF_CHAOS] = 341,
	[ITEM_PACK_INVASION_OF_CHAOS__SPECIAL_EDITION] = 342,
	[ITEM_PACK_INVASION__VENGEANCE] = 343,
	[ITEM_PACK_INVASION__VENGEANCE_SNEAK_PEEK_PARTICIPATION_CARD] = 344,
	[ITEM_PACK_INVASION__VENGEANCE__SPECIAL_EDITION] = 345,
	[ITEM_PACK_JUDGMENT_OF_THE_LIGHT] = 346,
	[ITEM_PACK_JUDGMENT_OF_THE_LIGHT_SNEAK_PEEK_PARTICIPATION_CARD] = 347,
	[ITEM_PACK_JUDGMENT_OF_THE_LIGHT__DELUXE_EDITION] = 348,
	[ITEM_PACK_KC_GRAND_TOURNAMENT_2021_PRIZE_CARD] = 349,
	[ITEM_PACK_KC_GRAND_TOURNAMENT_PRIZE_CARD] = 350,
	[ITEM_PACK_KIDS_WB_DUEL_OF_DESTINY_PROMOTIONAL_CARD] = 351,
	[ITEM_PACK_KING_S_COURT] = 352,
	[ITEM_PACK_LABYRINTH_OF_NIGHTMARE] = 353,
	[ITEM_PACK_LEGACY_OF_DARKNESS] = 354,
	[ITEM_PACK_LEGACY_OF_DESTRUCTION] = 355,
	[ITEM_PACK_LEGACY_OF_THE_VALIANT] = 356,
	[ITEM_PACK_LEGACY_OF_THE_VALIANT_SNEAK_PEEK_PARTICIPATION_CARD] = 357,
	[ITEM_PACK_LEGACY_OF_THE_VALIANT__DELUXE_EDITION] = 358,
	[ITEM_PACK_LEGEND_OF_BLUE_EYES_WHITE_DRAGON] = 359,
	[ITEM_PACK_LEGENDARY_COLLECTION] = 360,
	[ITEM_PACK_LEGENDARY_COLLECTION_2__THE_DUEL_ACADEMY_YEARS] = 361,
	[ITEM_PACK_LEGENDARY_COLLECTION_2__THE_DUEL_ACADEMY_YEARS_MEGA_PACK] = 362,
	[ITEM_PACK_LEGENDARY_COLLECTION_3__YUGI_S_WORLD] = 363,
	[ITEM_PACK_LEGENDARY_COLLECTION_3__YUGI_S_WORLD_MEGA_PACK] = 364,
	[ITEM_PACK_LEGENDARY_COLLECTION_4__JOEY_S_WORLD] = 365,
	[ITEM_PACK_LEGENDARY_COLLECTION_4__JOEY_S_WORLD_MEGA_PACK] = 366,
	[ITEM_PACK_LEGENDARY_COLLECTION_5D_S] = 367,
	[ITEM_PACK_LEGENDARY_COLLECTION_5D_S_MEGA_PACK] = 368,
	[ITEM_PACK_LEGENDARY_COLLECTION_KAIBA] = 369,
	[ITEM_PACK_LEGENDARY_COLLECTION_KAIBA_MEGA_PACK] = 370,
	[ITEM_PACK_LEGENDARY_COLLECTION__25TH_ANNIVERSARY_EDITION] = 371,
	[ITEM_PACK_LEGENDARY_DECKS_II] = 372,
	[ITEM_PACK_LEGENDARY_DRAGON_DECKS] = 373,
	[ITEM_PACK_LEGENDARY_DUELISTS] = 374,
	[ITEM_PACK_LEGENDARY_DUELISTS__ANCIENT_MILLENNIUM] = 375,
	[ITEM_PACK_LEGENDARY_DUELISTS__DUELS_FROM_THE_DEEP] = 376,
	[ITEM_PACK_LEGENDARY_DUELISTS__IMMORTAL_DESTINY] = 377,
	[ITEM_PACK_LEGENDARY_DUELISTS__MAGICAL_HERO] = 378,
	[ITEM_PACK_LEGENDARY_DUELISTS__RAGE_OF_RA] = 379,
	[ITEM_PACK_LEGENDARY_DUELISTS__SEASON_1] = 380,
	[ITEM_PACK_LEGENDARY_DUELISTS__SEASON_2] = 381,
	[ITEM_PACK_LEGENDARY_DUELISTS__SEASON_3] = 382,
	[ITEM_PACK_LEGENDARY_DUELISTS__SISTERS_OF_THE_ROSE] = 383,
	[ITEM_PACK_LEGENDARY_DUELISTS__SOULBURNING_VOLCANO] = 384,
	[ITEM_PACK_LEGENDARY_DUELISTS__SYNCHRO_STORM] = 385,
	[ITEM_PACK_LEGENDARY_DUELISTS__WHITE_DRAGON_ABYSS] = 386,
	[ITEM_PACK_LEGENDARY_HERO_DECKS] = 387,
	[ITEM_PACK_LIGHT_AND_DARKNESS_POWER_PACK] = 388,
	[ITEM_PACK_LIGHT_OF_DESTRUCTION] = 389,
	[ITEM_PACK_LIGHT_OF_DESTRUCTION_SNEAK_PEEK_PARTICIPATION_CARD] = 390,
	[ITEM_PACK_LIGHT_OF_DESTRUCTION__SPECIAL_EDITION] = 391,
	[ITEM_PACK_LIGHTNING_OVERDRIVE] = 392,
	[ITEM_PACK_LIGHTNING_OVERDRIVE_PREMIERE__PROMOTIONAL_CARD] = 393,
	[ITEM_PACK_LIMITED_EDITION_1] = 394,
	[ITEM_PACK_LORD_OF_THE_TACHYON_GALAXY] = 395,
	[ITEM_PACK_LORD_OF_THE_TACHYON_GALAXY_SNEAK_PEEK_PARTICIPATION_CARD] = 396,
	[ITEM_PACK_LOST_SANCTUARY_STRUCTURE_DECK] = 397,
	[ITEM_PACK_MACHINA_MAYHEM_STRUCTURE_DECK] = 398,
	[ITEM_PACK_MACHINE_REACTOR_STRUCTURE_DECK] = 399,
	[ITEM_PACK_MAGIC_RULER] = 400,
	[ITEM_PACK_MAGICIAN_S_FORCE] = 401,
	[ITEM_PACK_MAGNIFICENT_MAVENS] = 402,
	[ITEM_PACK_MAKE_A_WISH_FOUNDATION_PROMOTIONAL_CARD] = 403,
	[ITEM_PACK_MASTER_COLLECTION_VOLUME_1] = 404,
	[ITEM_PACK_MASTER_COLLECTION_VOLUME_2] = 405,
	[ITEM_PACK_MASTER_OF_PENDULUM_STRUCTURE_DECK] = 406,
	[ITEM_PACK_MATTEL_ACTION_FIGURE_PROMOTIONAL_CARDS__SERIES_1] = 407,
	[ITEM_PACK_MATTEL_ACTION_FIGURE_PROMOTIONAL_CARDS__SERIES_2] = 408,
	[ITEM_PACK_MATTEL_ACTION_FIGURE_PROMOTIONAL_CARDS__SERIES_3] = 409,
	[ITEM_PACK_MAXIMUM_CRISIS] = 410,
	[ITEM_PACK_MAXIMUM_CRISIS_SNEAK_PEEK_PARTICIPATION_CARD] = 411,
	[ITEM_PACK_MAXIMUM_CRISIS__SPECIAL_EDITION] = 412,
	[ITEM_PACK_MAXIMUM_GOLD] = 413,
	[ITEM_PACK_MAXIMUM_GOLD__EL_DORADO] = 414,
	[ITEM_PACK_MAZE_OF_MEMORIES] = 415,
	[ITEM_PACK_MAZE_OF_MILLENNIA] = 416,
	[ITEM_PACK_MAZE_OF_THE_MASTER] = 417,
	[ITEM_PACK_MCDONALD_S_PROMOTIONAL_CARDS] = 418,
	[ITEM_PACK_MCDONALD_S_PROMOTIONAL_CARDS_2] = 419,
	[ITEM_PACK_METAL_RAIDERS] = 420,
	[ITEM_PACK_MILLENNIUM_PACK] = 421,
	[ITEM_PACK_MOVIE_PACK] = 422,
	[ITEM_PACK_MYSTIC_FIGHTERS] = 423,
	[ITEM_PACK_NOBLE_KNIGHTS_OF_THE_ROUND_TABLE_BOX_SET] = 424,
	[ITEM_PACK_NOBLE_KNIGHTS_OF_THE_ROUND_TABLE_POWER_UP_PACK] = 425,
	[ITEM_PACK_NUMBER_HUNTERS] = 426,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_1] = 427,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_10] = 428,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_10__POR_] = 429,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_11] = 430,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_11__POR_] = 431,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_12] = 432,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_12__POR_] = 433,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_13] = 434,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_13__POR_] = 435,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_14] = 436,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_14__POR_] = 437,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_15] = 438,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_15__POR_] = 439,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_16] = 440,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_16__POR_] = 441,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_17] = 442,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_17__POR_] = 443,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_18] = 444,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_18__POR_] = 445,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_19] = 446,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_19__POR_] = 447,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_2] = 448,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_20] = 449,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_21] = 450,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_22] = 451,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_23] = 452,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_24] = 453,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_25] = 454,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_26] = 455,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_27] = 456,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_28] = 457,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_3] = 458,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_4] = 459,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_5] = 460,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_6] = 461,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_7] = 462,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_7__POR_] = 463,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_8] = 464,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_8__POR_] = 465,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_9] = 466,
	[ITEM_PACK_OTS_TOURNAMENT_PACK_9__POR_] = 467,
	[ITEM_PACK_ONSLAUGHT_OF_THE_FIRE_KINGS_STRUCTURE_DECK] = 468,
	[ITEM_PACK_ORDER_OF_CHAOS] = 469,
	[ITEM_PACK_ORDER_OF_CHAOS_SNEAK_PEEK_PARTICIPATION_CARD] = 470,
	[ITEM_PACK_ORDER_OF_CHAOS__SPECIAL_EDITION] = 471,
	[ITEM_PACK_PALLADIUM_ORACLE_MAHAD_SWEEPSTAKES] = 472,
	[ITEM_PACK_PENDULUM_DOMINATION_STRUCTURE_DECK] = 473,
	[ITEM_PACK_PENDULUM_EVOLUTION] = 474,
	[ITEM_PACK_PHANTOM_DARKNESS] = 475,
	[ITEM_PACK_PHANTOM_DARKNESS_SNEAK_PEEK_PARTICIPATION_CARD] = 476,
	[ITEM_PACK_PHANTOM_DARKNESS__SPECIAL_EDITION] = 477,
	[ITEM_PACK_PHANTOM_NIGHTMARE] = 478,
	[ITEM_PACK_PHANTOM_RAGE] = 479,
	[ITEM_PACK_PHANTOM_RAGE_PREMIERE__PROMOTIONAL_CARD] = 480,
	[ITEM_PACK_PHARAOH_TOUR_2005_PROMOTIONAL_CARDS] = 481,
	[ITEM_PACK_PHARAOH_TOUR_2006_PROMOTIONAL_CARDS] = 482,
	[ITEM_PACK_PHARAOH_TOUR_2007_PROMOTIONAL_CARDS] = 483,
	[ITEM_PACK_PHARAOH_S_SERVANT] = 484,
	[ITEM_PACK_PHARAONIC_GUARDIAN] = 485,
	[ITEM_PACK_PHOTON_HYPERNOVA] = 486,
	[ITEM_PACK_PHOTON_SHOCKWAVE] = 487,
	[ITEM_PACK_PHOTON_SHOCKWAVE_SNEAK_PEEK_PARTICIPATION_CARD] = 488,
	[ITEM_PACK_POWER_OF_THE_DUELIST] = 489,
	[ITEM_PACK_POWER_OF_THE_DUELIST_SNEAK_PEEK_PARTICIPATION_CARD] = 490,
	[ITEM_PACK_POWER_OF_THE_ELEMENTS] = 491,
	[ITEM_PACK_PREMIUM_COLLECTION_TIN] = 492,
	[ITEM_PACK_PREMIUM_GOLD] = 493,
	[ITEM_PACK_PREMIUM_GOLD__INFINITE_GOLD] = 494,
	[ITEM_PACK_PREMIUM_GOLD__RETURN_OF_THE_BLING] = 495,
	[ITEM_PACK_PREMIUM_PACK__TCG_] = 496,
	[ITEM_PACK_PREMIUM_PACK_2__TCG_] = 497,
	[ITEM_PACK_PRIMAL_ORIGIN] = 498,
	[ITEM_PACK_PRIMAL_ORIGIN_PLUS] = 499,
	[ITEM_PACK_PRIMAL_ORIGIN_SNEAK_PEEK_PARTICIPATION_CARD] = 500,
	[ITEM_PACK_PRIMAL_ORIGIN__DELUXE_EDITION] = 501,
	[ITEM_PACK_QUARTER_CENTURY_BONANZA] = 502,
	[ITEM_PACK_QUARTER_CENTURY_STAMPEDE] = 503,
	[ITEM_PACK_RA_YELLOW_MEGA_PACK] = 504,
	[ITEM_PACK_RA_YELLOW_MEGA_PACK__SPECIAL_EDITION] = 505,
	[ITEM_PACK_RAGE_OF_THE_ABYSS] = 506,
	[ITEM_PACK_RAGING_BATTLE] = 507,
	[ITEM_PACK_RAGING_BATTLE_SNEAK_PEEK_PARTICIPATION_CARD] = 508,
	[ITEM_PACK_RAGING_BATTLE__SPECIAL_EDITION] = 509,
	[ITEM_PACK_RAGING_TEMPEST] = 510,
	[ITEM_PACK_RAGING_TEMPEST_SNEAK_PEEK_PARTICIPATION_CARD] = 511,
	[ITEM_PACK_RAGING_TEMPEST__SPECIAL_EDITION] = 512,
	[ITEM_PACK_REALM_OF_LIGHT_STRUCTURE_DECK] = 513,
	[ITEM_PACK_REALM_OF_THE_SEA_EMPEROR_STRUCTURE_DECK] = 514,
	[ITEM_PACK_REMOTE_DUEL_AT_HOME_SWEEPSTAKES] = 515,
	[ITEM_PACK_RETRO_PACK] = 516,
	[ITEM_PACK_RETRO_PACK_2] = 517,
	[ITEM_PACK_RETURN_OF_THE_DUELIST] = 518,
	[ITEM_PACK_RETURN_OF_THE_DUELIST_SNEAK_PEEK_PARTICIPATION_CARD] = 519,
	[ITEM_PACK_RETURN_OF_THE_DUELIST__SPECIAL_EDITION] = 520,
	[ITEM_PACK_RISE_OF_DESTINY] = 521,
	[ITEM_PACK_RISE_OF_DESTINY__SPECIAL_EDITION] = 522,
	[ITEM_PACK_RISE_OF_THE_DRAGON_LORDS_STRUCTURE_DECK] = 523,
	[ITEM_PACK_RISE_OF_THE_DUELIST] = 524,
	[ITEM_PACK_RISE_OF_THE_DUELIST_PREMIERE__PROMOTIONAL_CARD] = 525,
	[ITEM_PACK_RISE_OF_THE_TRUE_DRAGONS_STRUCTURE_DECK] = 526,
	[ITEM_PACK_RISING_RAMPAGE] = 527,
	[ITEM_PACK_RISING_RAMPAGE_SNEAK_PEEK_PARTICIPATION_CARD] = 528,
	[ITEM_PACK_RISING_RAMPAGE_SPECIAL_EDITION] = 529,
	[ITEM_PACK_SJ_JUMP_PACK_SPRING_2020_PROMOTIONAL_CARD] = 530,
	[ITEM_PACK_SABER_FORCE_STARTER_DECK] = 531,
	[ITEM_PACK_SAGA_OF_BLUE_EYES_WHITE_DRAGON_STRUCTURE_DECK] = 532,
	[ITEM_PACK_SAMURAI_ASSAULT] = 533,
	[ITEM_PACK_SAMURAI_WARLORDS_STRUCTURE_DECK] = 534,
	[ITEM_PACK_SAN_DIEGO_COMIC_CON_PROMOTIONAL_CARDS] = 535,
	[ITEM_PACK_SAVAGE_STRIKE] = 536,
	[ITEM_PACK_SAVAGE_STRIKE_SNEAK_PEEK_PARTICIPATION_CARD] = 537,
	[ITEM_PACK_SAVAGE_STRIKE_SPECIAL_EDITION] = 538,
	[ITEM_PACK_SECRET_SLAYERS] = 539,
	[ITEM_PACK_SECRETS_OF_ETERNITY] = 540,
	[ITEM_PACK_SECRETS_OF_ETERNITY_SNEAK_PEEK_PARTICIPATION_CARD] = 541,
	[ITEM_PACK_SECRETS_OF_ETERNITY__SUPER_EDITION] = 542,
	[ITEM_PACK_SHADOW_SPECTERS] = 543,
	[ITEM_PACK_SHADOW_SPECTERS_SNEAK_PEEK_PARTICIPATION_CARD] = 544,
	[ITEM_PACK_SHADOW_SPECTERS__SPECIAL_EDITION] = 545,
	[ITEM_PACK_SHADOW_OF_INFINITY] = 546,
	[ITEM_PACK_SHADOW_OF_INFINITY_SNEAK_PEEK_PARTICIPATION_CARD] = 547,
	[ITEM_PACK_SHADOW_OF_INFINITY__SPECIAL_EDITION] = 548,
	[ITEM_PACK_SHADOWS_IN_VALHALLA] = 549,
	[ITEM_PACK_SHINING_VICTORIES] = 550,
	[ITEM_PACK_SHINING_VICTORIES_SNEAK_PEEK_PARTICIPATION_CARD] = 551,
	[ITEM_PACK_SHINING_VICTORIES__SPECIAL_EDITION] = 552,
	[ITEM_PACK_SHONEN_JUMP_2007_SUBSCRIPTION_BONUS] = 553,
	[ITEM_PACK_SHONEN_JUMP_CHAMPIONSHIP_2004_PRIZE_CARD] = 554,
	[ITEM_PACK_SHONEN_JUMP_CHAMPIONSHIP_2005_PRIZE_CARD] = 555,
	[ITEM_PACK_SHONEN_JUMP_CHAMPIONSHIP_2006_PRIZE_CARD] = 556,
	[ITEM_PACK_SHONEN_JUMP_CHAMPIONSHIP_2007_PRIZE_CARD_A] = 557,
	[ITEM_PACK_SHONEN_JUMP_CHAMPIONSHIP_2007_PRIZE_CARD_B] = 558,
	[ITEM_PACK_SHONEN_JUMP_CHAMPIONSHIP_2008_PRIZE_CARD] = 559,
	[ITEM_PACK_SHONEN_JUMP_CHAMPIONSHIP_2009_PRIZE_CARD] = 560,
	[ITEM_PACK_SHONEN_JUMP_DECEMBER_2010_SUBSCRIPTION_BONUS] = 561,
	[ITEM_PACK_SHONEN_JUMP_DECEMBER_2011_SUBSCRIPTION_BONUS] = 562,
	[ITEM_PACK_SHONEN_JUMP_FEBRUARY_2009_SUBSCRIPTION_BONUS] = 563,
	[ITEM_PACK_SHONEN_JUMP_JUNE_JULY_2011_SUBSCRIPTION_BONUS] = 564,
	[ITEM_PACK_SHONEN_JUMP_MARCH_2010_SUBSCRIPTION_BONUS] = 565,
	[ITEM_PACK_SHONEN_JUMP_MAY_2006_SUBSCRIPTION_BONUS] = 566,
	[ITEM_PACK_SHONEN_JUMP_MAY_2008_SUBSCRIPTION_BONUS] = 567,
	[ITEM_PACK_SHONEN_JUMP_MAY_2010_SUBSCRIPTION_BONUS] = 568,
	[ITEM_PACK_SHONEN_JUMP_SCHOLASTIC_EDITION_VOL__9__ISSUE_1_PROMOTIONAL_CARD] = 569,
	[ITEM_PACK_SHONEN_JUMP_VOL__1__ISSUE_1_PROMOTIONAL_CARD] = 570,
	[ITEM_PACK_SHONEN_JUMP_VOL__10__ISSUE_1_PROMOTIONAL_CARD] = 571,
	[ITEM_PACK_SHONEN_JUMP_VOL__10__ISSUE_3_PROMOTIONAL_CARD] = 572,
	[ITEM_PACK_SHONEN_JUMP_VOL__10__ISSUE_4_PROMOTIONAL_CARD] = 573,
	[ITEM_PACK_SHONEN_JUMP_VOL__2__ISSUE_1_PROMOTIONAL_CARD] = 574,
	[ITEM_PACK_SHONEN_JUMP_VOL__3__ISSUE_1_PROMOTIONAL_CARD] = 575,
	[ITEM_PACK_SHONEN_JUMP_VOL__4__ISSUE_1_PROMOTIONAL_CARD] = 576,
	[ITEM_PACK_SHONEN_JUMP_VOL__4__ISSUE_11_PROMOTIONAL_CARD] = 577,
	[ITEM_PACK_SHONEN_JUMP_VOL__4__ISSUE_12_PROMOTIONAL_CARD] = 578,
	[ITEM_PACK_SHONEN_JUMP_VOL__5__ISSUE_1_PROMOTIONAL_CARD] = 579,
	[ITEM_PACK_SHONEN_JUMP_VOL__5__ISSUE_11_PROMOTIONAL_CARD] = 580,
	[ITEM_PACK_SHONEN_JUMP_VOL__5__ISSUE_4_PROMOTIONAL_CARD] = 581,
	[ITEM_PACK_SHONEN_JUMP_VOL__5__ISSUE_6_PROMOTIONAL_CARD] = 582,
	[ITEM_PACK_SHONEN_JUMP_VOL__5__ISSUE_9_PROMOTIONAL_CARD] = 583,
	[ITEM_PACK_SHONEN_JUMP_VOL__6__ISSUE_1_PROMOTIONAL_CARD] = 584,
	[ITEM_PACK_SHONEN_JUMP_VOL__6__ISSUE_12_PROMOTIONAL_CARD] = 585,
	[ITEM_PACK_SHONEN_JUMP_VOL__6__ISSUE_3_PROMOTIONAL_CARD] = 586,
	[ITEM_PACK_SHONEN_JUMP_VOL__6__ISSUE_5_PROMOTIONAL_CARD] = 587,
	[ITEM_PACK_SHONEN_JUMP_VOL__6__ISSUE_9_PROMOTIONAL_CARD] = 588,
	[ITEM_PACK_SHONEN_JUMP_VOL__7__ISSUE_1_PROMOTIONAL_CARD] = 589,
	[ITEM_PACK_SHONEN_JUMP_VOL__7__ISSUE_11_PROMOTIONAL_CARD] = 590,
	[ITEM_PACK_SHONEN_JUMP_VOL__7__ISSUE_3_PROMOTIONAL_CARD] = 591,
	[ITEM_PACK_SHONEN_JUMP_VOL__7__ISSUE_6_PROMOTIONAL_CARD] = 592,
	[ITEM_PACK_SHONEN_JUMP_VOL__7__ISSUE_9_PROMOTIONAL_CARD] = 593,
	[ITEM_PACK_SHONEN_JUMP_VOL__8__ISSUE_1_PROMOTIONAL_CARD] = 594,
	[ITEM_PACK_SHONEN_JUMP_VOL__8__ISSUE_11_PROMOTIONAL_CARD] = 595,
	[ITEM_PACK_SHONEN_JUMP_VOL__8__ISSUE_3_PROMOTIONAL_CARD] = 596,
	[ITEM_PACK_SHONEN_JUMP_VOL__8__ISSUE_5_PROMOTIONAL_CARD] = 597,
	[ITEM_PACK_SHONEN_JUMP_VOL__8__ISSUE_7_PROMOTIONAL_CARD] = 598,
	[ITEM_PACK_SHONEN_JUMP_VOL__8__ISSUE_9_PROMOTIONAL_CARD] = 599,
	[ITEM_PACK_SHONEN_JUMP_VOL__9__ISSUE_1_PROMOTIONAL_CARD] = 600,
	[ITEM_PACK_SHONEN_JUMP_VOL__9__ISSUE_10_PROMOTIONAL_CARD] = 601,
	[ITEM_PACK_SHONEN_JUMP_VOL__9__ISSUE_3_PROMOTIONAL_CARD] = 602,
	[ITEM_PACK_SHONEN_JUMP_VOL__9__ISSUE_4_PROMOTIONAL_CARD] = 603,
	[ITEM_PACK_SHONEN_JUMP_VOL__9__ISSUE_6_PROMOTIONAL_CARD] = 604,
	[ITEM_PACK_SHONEN_JUMP_VOL__9__ISSUE_8_PROMOTIONAL_CARD] = 605,
	[ITEM_PACK_SOUL_FUSION] = 606,
	[ITEM_PACK_SOUL_FUSION_SNEAK_PEEK_PARTICIPATION_CARD] = 607,
	[ITEM_PACK_SOUL_FUSION_SPECIAL_EDITION] = 608,
	[ITEM_PACK_SOUL_OF_THE_DUELIST] = 609,
	[ITEM_PACK_SPACE_TIME_SHOWDOWN_POWER_UP_PACK] = 610,
	[ITEM_PACK_SPEED_DUEL_DEMO_DECK] = 611,
	[ITEM_PACK_SPEED_DUEL_DEMO_DECK_2020] = 612,
	[ITEM_PACK_SPEED_DUEL_GX__DUEL_ACADEMY_BOX] = 613,
	[ITEM_PACK_SPEED_DUEL_GX__DUELISTS_OF_SHADOWS] = 614,
	[ITEM_PACK_SPEED_DUEL_GX__MIDTERM_PARADOX] = 615,
	[ITEM_PACK_SPEED_DUEL_STARTER_DECKS__DESTINY_MASTERS] = 616,
	[ITEM_PACK_SPEED_DUEL_STARTER_DECKS__DUELISTS_OF_TOMORROW] = 617,
	[ITEM_PACK_SPEED_DUEL_STARTER_DECKS__MATCH_OF_THE_MILLENNIUM] = 618,
	[ITEM_PACK_SPEED_DUEL_STARTER_DECKS__TWISTED_NIGHTMARES] = 619,
	[ITEM_PACK_SPEED_DUEL_STARTER_DECKS__ULTIMATE_PREDATORS] = 620,
	[ITEM_PACK_SPEED_DUEL_TOURNAMENT_PACK_1] = 621,
	[ITEM_PACK_SPEED_DUEL_TOURNAMENT_PACK_2] = 622,
	[ITEM_PACK_SPEED_DUEL_TOURNAMENT_PACK_3] = 623,
	[ITEM_PACK_SPEED_DUEL_TOURNAMENT_PACK_4] = 624,
	[ITEM_PACK_SPEED_DUEL_TOURNAMENT_PACK_5] = 625,
	[ITEM_PACK_SPEED_DUEL_TOURNAMENT_PACK_6] = 626,
	[ITEM_PACK_SPEED_DUEL__ARENA_OF_LOST_SOULS] = 627,
	[ITEM_PACK_SPEED_DUEL__ATTACK_FROM_THE_DEEP] = 628,
	[ITEM_PACK_SPEED_DUEL__BATTLE_CITY_BOX] = 629,
	[ITEM_PACK_SPEED_DUEL__SCARS_OF_BATTLE] = 630,
	[ITEM_PACK_SPEED_DUEL__SCARS_OF_BATTLE_LAUNCH_EVENT_PARTICIPATION_CARD] = 631,
	[ITEM_PACK_SPEED_DUEL__STREETS_OF_BATTLE_CITY] = 632,
	[ITEM_PACK_SPEED_DUEL__TRIALS_OF_THE_KINGDOM] = 633,
	[ITEM_PACK_SPEED_DUEL__TRIALS_OF_THE_KINGDOM_SNEAK_PEEK_PARTICIPATION_CARDS] = 634,
	[ITEM_PACK_SPELL_RULER] = 635,
	[ITEM_PACK_SPELLCASTER_S_COMMAND_STRUCTURE_DECK] = 636,
	[ITEM_PACK_SPELLCASTER_S_COMMAND_STRUCTURE_DECK__SPECIAL_EDITION] = 637,
	[ITEM_PACK_SPIRIT_WARRIORS] = 638,
	[ITEM_PACK_STAR_PACK_2013] = 639,
	[ITEM_PACK_STAR_PACK_2014] = 640,
	[ITEM_PACK_STAR_PACK_ARC_V] = 641,
	[ITEM_PACK_STAR_PACK_BATTLE_ROYAL] = 642,
	[ITEM_PACK_STAR_PACK_VRAINS] = 643,
	[ITEM_PACK_STARDUST_OVERDRIVE] = 644,
	[ITEM_PACK_STARDUST_OVERDRIVE_SNEAK_PEEK_PARTICIPATION_CARD] = 645,
	[ITEM_PACK_STARDUST_OVERDRIVE__SPECIAL_EDITION] = 646,
	[ITEM_PACK_STARSTRIKE_BLAST] = 647,
	[ITEM_PACK_STARSTRIKE_BLAST_SNEAK_PEEK_PARTICIPATION_CARD] = 648,
	[ITEM_PACK_STARTER_DECK_2006] = 649,
	[ITEM_PACK_STARTER_DECK_2006__SPECIAL_EDITION] = 650,
	[ITEM_PACK_STARTER_DECK__CODEBREAKER] = 651,
	[ITEM_PACK_STARTER_DECK__DAWN_OF_THE_XYZ] = 652,
	[ITEM_PACK_STARTER_DECK__DUELIST_TOOLBOX] = 653,
	[ITEM_PACK_STARTER_DECK__JADEN_YUKI] = 654,
	[ITEM_PACK_STARTER_DECK__JOEY] = 655,
	[ITEM_PACK_STARTER_DECK__KAIBA] = 656,
	[ITEM_PACK_STARTER_DECK__KAIBA_EVOLUTION] = 657,
	[ITEM_PACK_STARTER_DECK__KAIBA_RELOADED] = 658,
	[ITEM_PACK_STARTER_DECK__LINK_STRIKE] = 659,
	[ITEM_PACK_STARTER_DECK__PEGASUS] = 660,
	[ITEM_PACK_STARTER_DECK__SYRUS_TRUESDALE] = 661,
	[ITEM_PACK_STARTER_DECK__XYZ_SYMPHONY] = 662,
	[ITEM_PACK_STARTER_DECK__YU_GI_OH__5D_S] = 663,
	[ITEM_PACK_STARTER_DECK__YU_GI_OH__5D_S_2009] = 664,
	[ITEM_PACK_STARTER_DECK__YUGI] = 665,
	[ITEM_PACK_STARTER_DECK__YUGI_EVOLUTION] = 666,
	[ITEM_PACK_STARTER_DECK__YUGI_RELOADED] = 667,
	[ITEM_PACK_STARTER_DECK__YUYA] = 668,
	[ITEM_PACK_STORM_OF_RAGNAROK] = 669,
	[ITEM_PACK_STORM_OF_RAGNAROK_SNEAK_PEEK_PARTICIPATION_CARD] = 670,
	[ITEM_PACK_STORM_OF_RAGNAROK__SPECIAL_EDITION] = 671,
	[ITEM_PACK_STRIKE_OF_NEOS] = 672,
	[ITEM_PACK_STRIKE_OF_NEOS_SNEAK_PEEK_PARTICIPATION_CARD] = 673,
	[ITEM_PACK_STRIKE_OF_NEOS__SPECIAL_EDITION] = 674,
	[ITEM_PACK_STRUCTURE_DECK__ALBAZ_STRIKE] = 675,
	[ITEM_PACK_STRUCTURE_DECK__BEWARE_OF_TRAPTRIX] = 676,
	[ITEM_PACK_STRUCTURE_DECK__BLAZE_OF_DESTRUCTION] = 677,
	[ITEM_PACK_STRUCTURE_DECK__BLUE_EYES_WHITE_DESTINY] = 678,
	[ITEM_PACK_STRUCTURE_DECK__CYBER_STRIKE] = 679,
	[ITEM_PACK_STRUCTURE_DECK__CYBERSE_LINK] = 680,
	[ITEM_PACK_STRUCTURE_DECK__DARK_WORLD] = 681,
	[ITEM_PACK_STRUCTURE_DECK__DELUXE_EDITION] = 682,
	[ITEM_PACK_STRUCTURE_DECK__DINOSAUR_S_RAGE] = 683,
	[ITEM_PACK_STRUCTURE_DECK__DINOSAUR_S_RAGE_SPECIAL_SET] = 684,
	[ITEM_PACK_STRUCTURE_DECK__DRAGON_S_ROAR] = 685,
	[ITEM_PACK_STRUCTURE_DECK__FIRE_KINGS] = 686,
	[ITEM_PACK_STRUCTURE_DECK__FREEZING_CHAINS] = 687,
	[ITEM_PACK_STRUCTURE_DECK__FURY_FROM_THE_DEEP] = 688,
	[ITEM_PACK_STRUCTURE_DECK__INVINCIBLE_FORTRESS] = 689,
	[ITEM_PACK_STRUCTURE_DECK__LAIR_OF_DARKNESS] = 690,
	[ITEM_PACK_STRUCTURE_DECK__LEGEND_OF_THE_CRYSTAL_BEASTS] = 691,
	[ITEM_PACK_STRUCTURE_DECK__LORD_OF_THE_STORM] = 692,
	[ITEM_PACK_STRUCTURE_DECK__MACHINE_RE_VOLT] = 693,
	[ITEM_PACK_STRUCTURE_DECK__MARIK__TCG_] = 694,
	[ITEM_PACK_STRUCTURE_DECK__MECHANIZED_MADNESS] = 695,
	[ITEM_PACK_STRUCTURE_DECK__ORDER_OF_THE_SPELLCASTERS] = 696,
	[ITEM_PACK_STRUCTURE_DECK__POWERCODE_LINK] = 697,
	[ITEM_PACK_STRUCTURE_DECK__ROKKET_REVOLT] = 698,
	[ITEM_PACK_STRUCTURE_DECK__SACRED_BEASTS] = 699,
	[ITEM_PACK_STRUCTURE_DECK__SETO_KAIBA] = 700,
	[ITEM_PACK_STRUCTURE_DECK__SHADDOLL_SHOWDOWN] = 701,
	[ITEM_PACK_STRUCTURE_DECK__SOULBURNER] = 702,
	[ITEM_PACK_STRUCTURE_DECK__SPELLCASTER_S_JUDGMENT] = 703,
	[ITEM_PACK_STRUCTURE_DECK__SPIRIT_CHARMERS] = 704,
	[ITEM_PACK_STRUCTURE_DECK__THE_CRIMSON_KING] = 705,
	[ITEM_PACK_STRUCTURE_DECK__WARRIOR_S_TRIUMPH] = 706,
	[ITEM_PACK_STRUCTURE_DECK__WAVE_OF_LIGHT] = 707,
	[ITEM_PACK_STRUCTURE_DECK__YUGI_MUTO] = 708,
	[ITEM_PACK_STRUCTURE_DECK__ZOMBIE_HORDE] = 709,
	[ITEM_PACK_STRUCTURE_DECK__ZOMBIE_MADNESS] = 710,
	[ITEM_PACK_SUMMONED_SKULL_SAMPLE_PROMOTIONAL_CARD] = 711,
	[ITEM_PACK_SUPER_STARTER_POWER_UP_PACK] = 712,
	[ITEM_PACK_SUPER_STARTER__SPACE_TIME_SHOWDOWN] = 713,
	[ITEM_PACK_SUPER_STARTER__V_FOR_VICTORY] = 714,
	[ITEM_PACK_SUPREME_DARKNESS] = 715,
	[ITEM_PACK_SWEDISH_SHONEN_JUMP_2004__ISSUE_2_PROMOTIONAL_CARD] = 716,
	[ITEM_PACK_SWEDISH_SHONEN_JUMP_2005__ISSUE_12_PROMOTIONAL_CARD] = 717,
	[ITEM_PACK_SYNCHRON_EXTREME_STRUCTURE_DECK] = 718,
	[ITEM_PACK_TACTICAL_EVOLUTION] = 719,
	[ITEM_PACK_TACTICAL_EVOLUTION_SNEAK_PEEK_PARTICIPATION_CARD] = 720,
	[ITEM_PACK_TACTICAL_EVOLUTION__SPECIAL_EDITION] = 721,
	[ITEM_PACK_TACTICAL_MASTERS] = 722,
	[ITEM_PACK_THE_DARK_EMPEROR_STRUCTURE_DECK] = 723,
	[ITEM_PACK_THE_DARK_ILLUSION] = 724,
	[ITEM_PACK_THE_DARK_ILLUSION_SNEAK_PEEK_PARTICIPATION_CARD] = 725,
	[ITEM_PACK_THE_DARK_ILLUSION__SPECIAL_EDITION] = 726,
	[ITEM_PACK_THE_DUELIST_GENESIS] = 727,
	[ITEM_PACK_THE_DUELIST_GENESIS_SNEAK_PEEK_PARTICIPATION_CARD] = 728,
	[ITEM_PACK_THE_DUELIST_GENESIS__SPECIAL_EDITION] = 729,
	[ITEM_PACK_THE_GRAND_CREATORS] = 730,
	[ITEM_PACK_THE_INFINITE_FORBIDDEN] = 731,
	[ITEM_PACK_THE_INFINITY_CHASERS] = 732,
	[ITEM_PACK_THE_LOST_ART_PROMOTION__SERIES_] = 733,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2020_D] = 734,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2020_E] = 735,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2020_F] = 736,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2020_G] = 737,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2020_H] = 738,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2020_I] = 739,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2020_J] = 740,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2020_K] = 741,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2020_L] = 742,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2020_M] = 743,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2020_N] = 744,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2020_O] = 745,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2020_P] = 746,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2020_Q] = 747,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2020_R] = 748,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2021_A] = 749,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2021_B] = 750,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2021_C] = 751,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2021_D] = 752,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2021_E] = 753,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2021_F] = 754,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2021_G] = 755,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2021_H] = 756,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2021_I] = 757,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2021_J] = 758,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2021_K] = 759,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2021_L] = 760,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2022] = 761,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2022_G] = 762,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2022_K] = 763,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2023] = 764,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2023_E] = 765,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2023_F] = 766,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2023_G] = 767,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2023_H] = 768,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2023_I] = 769,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2024] = 770,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2024_A] = 771,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2024_B] = 772,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2024_C] = 773,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_2024_H] = 774,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_A] = 775,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_B] = 776,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_C] = 777,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_D] = 778,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_E] = 779,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_F] = 780,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_G] = 781,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_H] = 782,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_I] = 783,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_J] = 784,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_K] = 785,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_L] = 786,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_M] = 787,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_N] = 788,
	[ITEM_PACK_THE_LOST_ART_PROMOTION_O] = 789,
	[ITEM_PACK_THE_LOST_MILLENNIUM] = 790,
	[ITEM_PACK_THE_LOST_MILLENNIUM_SNEAK_PEEK_PARTICIPATION_CARD] = 791,
	[ITEM_PACK_THE_LOST_MILLENNIUM__SPECIAL_EDITION] = 792,
	[ITEM_PACK_THE_NEW_CHALLENGERS] = 793,
	[ITEM_PACK_THE_NEW_CHALLENGERS_SNEAK_PEEK_PARTICIPATION_CARD] = 794,
	[ITEM_PACK_THE_NEW_CHALLENGERS__SUPER_EDITION] = 795,
	[ITEM_PACK_THE_POT_COLLECTION] = 796,
	[ITEM_PACK_THE_SECRET_FORCES] = 797,
	[ITEM_PACK_THE_SHINING_DARKNESS] = 798,
	[ITEM_PACK_THE_SHINING_DARKNESS_SNEAK_PEEK_PARTICIPATION_CARD] = 799,
	[ITEM_PACK_TOON_CHAOS] = 800,
	[ITEM_PACK_TOURNAMENT_PACK_4] = 801,
	[ITEM_PACK_TOURNAMENT_PACK_5] = 802,
	[ITEM_PACK_TOURNAMENT_PACK_6] = 803,
	[ITEM_PACK_TOURNAMENT_PACK_7] = 804,
	[ITEM_PACK_TOURNAMENT_PACK_8] = 805,
	[ITEM_PACK_TOURNAMENT_PACK__1ST_SEASON] = 806,
	[ITEM_PACK_TOURNAMENT_PACK__2ND_SEASON] = 807,
	[ITEM_PACK_TOURNAMENT_PACK__3RD_SEASON] = 808,
	[ITEM_PACK_TRIALS_OF_THE_PHARAOH___MATCH_OF_THE_MILLENNIUM___TWISTED_NIGHTMARES_PROMOTIONAL_CARD] = 809,
	[ITEM_PACK_TRIALS_OF_THE_PHARAOH___SPEED_DUEL__BATTLE_CITY_BOX_PROMOTIONAL_CARD] = 810,
	[ITEM_PACK_TRIALS_OF_THE_PHARAOH___TRIALS_OF_THE_KINGDOM_PROMOTIONAL_CARD] = 811,
	[ITEM_PACK_TURBO_PACK__BOOSTER_EIGHT] = 812,
	[ITEM_PACK_TURBO_PACK__BOOSTER_FIVE] = 813,
	[ITEM_PACK_TURBO_PACK__BOOSTER_FOUR] = 814,
	[ITEM_PACK_TURBO_PACK__BOOSTER_ONE] = 815,
	[ITEM_PACK_TURBO_PACK__BOOSTER_SEVEN] = 816,
	[ITEM_PACK_TURBO_PACK__BOOSTER_SIX] = 817,
	[ITEM_PACK_TURBO_PACK__BOOSTER_THREE] = 818,
	[ITEM_PACK_TURBO_PACK__BOOSTER_TWO] = 819,
	[ITEM_PACK_TWILIGHT_EDITION] = 820,
	[ITEM_PACK_ULTIMATE_EDITION] = 821,
	[ITEM_PACK_ULTIMATE_EDITION_2] = 822,
	[ITEM_PACK_VALIANT_SMASHERS] = 823,
	[ITEM_PACK_WCS_2025_LIMITED_PACK] = 824,
	[ITEM_PACK_WSJ_JUMP_PACK_FALL_2016_PROMOTIONAL_CARD] = 825,
	[ITEM_PACK_WSJ_JUMP_PACK_FALL_2017_PROMOTIONAL_CARD] = 826,
	[ITEM_PACK_WSJ_JUMP_PACK_FALL_2018_PROMOTIONAL_CARD] = 827,
	[ITEM_PACK_WSJ_JUMP_PACK_SPRING_2016_PROMOTIONAL_CARD] = 828,
	[ITEM_PACK_WSJ_JUMP_PACK_SPRING_2017_PROMOTIONAL_CARD] = 829,
	[ITEM_PACK_WSJ_JUMP_PACK_SPRING_2018_PROMOTIONAL_CARD] = 830,
	[ITEM_PACK_WSJ_JUMP_PACK_SPRING_2019_PROMOTIONAL_CARD] = 831,
	[ITEM_PACK_WAR_OF_THE_GIANTS_REINFORCEMENTS] = 832,
	[ITEM_PACK_WAR_OF_THE_GIANTS__ROUND_2] = 833,
	[ITEM_PACK_WARRIORS__STRIKE_STRUCTURE_DECK] = 834,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_ALPHA_APRIL_2012_MEMBERSHIP_PROMOTIONAL_CARD] = 835,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_ALPHA_DECEMBER_2012_MEMBERSHIP_PROMOTIONAL_CARD] = 836,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_ALPHA_JULY_2012_MEMBERSHIP_PROMOTIONAL_CARD] = 837,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_ALPHA_SEPTEMBER_2012_MEMBERSHIP_PROMOTIONAL_CARD] = 838,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_APRIL_2015_MEMBERSHIP_PROMOTIONAL_CARD] = 839,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_APRIL_2016_MEMBERSHIP_PROMOTIONAL_CARD] = 840,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_APRIL_2017_MEMBERSHIP_PROMOTIONAL_CARD] = 841,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_APRIL_2018_MEMBERSHIP_PROMOTIONAL_CARD] = 842,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_AUGUST_2014_MEMBERSHIP_PROMOTIONAL_CARD] = 843,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_DECEMBER_2013_MEMBERSHIP_PROMOTIONAL_CARD] = 844,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_DECEMBER_2018_MEMBERSHIP_PROMOTIONAL_CARDS] = 845,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_FEBRUARY_2015_MEMBERSHIP_PROMOTIONAL_CARD] = 846,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_JANUARY_2016_MEMBERSHIP_PROMOTIONAL_CARD] = 847,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_JANUARY_2017_MEMBERSHIP_PROMOTIONAL_CARD] = 848,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_JANUARY_2018_MEMBERSHIP_PROMOTIONAL_CARD] = 849,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_JULY_2013_MEMBERSHIP_PROMOTIONAL_CARD] = 850,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_JULY_2015_MEMBERSHIP_PROMOTIONAL_CARD] = 851,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_JULY_2016_MEMBERSHIP_PROMOTIONAL_CARD] = 852,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_JULY_2017_MEMBERSHIP_PROMOTIONAL_CARD] = 853,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_JULY_2018_MEMBERSHIP_PROMOTIONAL_CARD] = 854,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_MARCH_2013_MEMBERSHIP_PROMOTIONAL_CARD] = 855,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_MARCH_2014_MEMBERSHIP_PROMOTIONAL_CARD] = 856,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_NOVEMBER_2014_MEMBERSHIP_PROMOTIONAL_CARD] = 857,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_NOVEMBER_2017_MEMBERSHIP_PROMOTIONAL_CARD] = 858,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_NOVEMBER_2018_MEMBERSHIP_PROMOTIONAL_CARD] = 859,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_OCTOBER_2015_MEMBERSHIP_PROMOTIONAL_CARD] = 860,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_OCTOBER_2016_MEMBERSHIP_PROMOTIONAL_CARD] = 861,
	[ITEM_PACK_WEEKLY_SHONEN_JUMP_SEPTEMBER_2013_MEMBERSHIP_PROMOTIONAL_CARD] = 862,
	[ITEM_PACK_WILD_SURVIVORS] = 863,
	[ITEM_PACK_WING_RAIDERS] = 864,
	[ITEM_PACK_WORLD_CHAMPIONSHIP_2010_CARD_PACK] = 865,
	[ITEM_PACK_WORLD_CHAMPIONSHIP_2011_CARD_PACK] = 866,
	[ITEM_PACK_WORLD_SUPERSTARS] = 867,
	[ITEM_PACK_X_SABER_POWER_UP] = 868,
	[ITEM_PACK_YU_GI_OH__3D_BONDS_BEYOND_TIME_DVD_PROMOTIONAL_CARD] = 869,
	[ITEM_PACK_YU_GI_OH__3D_BONDS_BEYOND_TIME_MOVIE_PACK] = 870,
	[ITEM_PACK_YU_GI_OH__3D_BONDS_BEYOND_TIME_THEATER_DISTRIBUTION_CARD] = 871,
	[ITEM_PACK_YU_GI_OH__5D_S_DUEL_TRANSER_PROMOTIONAL_CARDS] = 872,
	[ITEM_PACK_YU_GI_OH__5D_S_STARDUST_ACCELERATOR_PROMOTIONAL_CARDS] = 873,
	[ITEM_PACK_YU_GI_OH__5D_S_TAG_FORCE_4_PROMOTIONAL_CARDS] = 874,
	[ITEM_PACK_YU_GI_OH__5D_S_TAG_FORCE_5_PROMOTIONAL_CARDS] = 875,
	[ITEM_PACK_YU_GI_OH__5D_S_TAG_FORCE_5_PROMOTIONAL_CARDS] = 876,
	[ITEM_PACK_YU_GI_OH__5D_S_VOLUME_1_PROMOTIONAL_CARD] = 877,
	[ITEM_PACK_YU_GI_OH__5D_S_VOLUME_2_PROMOTIONAL_CARD] = 878,
	[ITEM_PACK_YU_GI_OH__5D_S_VOLUME_3_PROMOTIONAL_CARD] = 879,
	[ITEM_PACK_YU_GI_OH__5D_S_VOLUME_4_PROMOTIONAL_CARD] = 880,
	[ITEM_PACK_YU_GI_OH__5D_S_VOLUME_5_PROMOTIONAL_CARD] = 881,
	[ITEM_PACK_YU_GI_OH__5D_S_VOLUME_6_PROMOTIONAL_CARD] = 882,
	[ITEM_PACK_YU_GI_OH__5D_S_VOLUME_7_PROMOTIONAL_CARD] = 883,
	[ITEM_PACK_YU_GI_OH__5D_S_VOLUME_9_PROMOTIONAL_CARD] = 884,
	[ITEM_PACK_YU_GI_OH__5D_S_WHEELIE_BREAKERS_PROMOTIONAL_CARDS] = 885,
	[ITEM_PACK_YU_GI_OH__5D_S_WORLD_CHAMPIONSHIP_2009__STARDUST_ACCELERATOR_PROMOTIONAL_CARDS] = 886,
	[ITEM_PACK_YU_GI_OH__5D_S_WORLD_CHAMPIONSHIP_2010__REVERSE_OF_ARCADIA_PROMOTIONAL_CARDS] = 887,
	[ITEM_PACK_YU_GI_OH__5D_S_WORLD_CHAMPIONSHIP_2011__OVER_THE_NEXUS_PROMOTIONAL_CARDS] = 888,
	[ITEM_PACK_YU_GI_OH__5D_S_VOLUME_8_PROMOTIONAL_CARD] = 889,
	[ITEM_PACK_YU_GI_OH__7_TRIALS_TO_GLORY__WORLD_CHAMPIONSHIP_TOURNAMENT_2005_PROMOTIONAL_CARDS] = 890,
	[ITEM_PACK_YU_GI_OH__ARC_V_VOLUME_1_PROMOTIONAL_CARD] = 891,
	[ITEM_PACK_YU_GI_OH__ARC_V_VOLUME_2_PROMOTIONAL_CARD] = 892,
	[ITEM_PACK_YU_GI_OH__ARC_V_VOLUME_3_PROMOTIONAL_CARD] = 893,
	[ITEM_PACK_YU_GI_OH__ARC_V_VOLUME_4_PROMOTIONAL_CARD] = 894,
	[ITEM_PACK_YU_GI_OH__ARC_V_VOLUME_5_PROMOTIONAL_CARD] = 895,
	[ITEM_PACK_YU_GI_OH__ARC_V_VOLUME_6_PROMOTIONAL_CARD] = 896,
	[ITEM_PACK_YU_GI_OH__ARC_V_VOLUME_7_PROMOTIONAL_CARD] = 897,
	[ITEM_PACK_YU_GI_OH__ADVENT_CALENDAR] = 898,
	[ITEM_PACK_YU_GI_OH__ADVENT_CALENDAR__2018_] = 899,
	[ITEM_PACK_YU_GI_OH__ADVENT_CALENDAR__2019_] = 900,
	[ITEM_PACK_YU_GI_OH__CAPSULE_MONSTER_COLISEUM_PROMOTIONAL_CARDS] = 901,
	[ITEM_PACK_YU_GI_OH__CHAMPIONSHIP_SERIES_2010_PRIZE_CARDS] = 902,
	[ITEM_PACK_YU_GI_OH__CHAMPIONSHIP_SERIES_2011_PRIZE_CARD] = 903,
	[ITEM_PACK_YU_GI_OH__CHAMPIONSHIP_SERIES_2012_PRIZE_CARD] = 904,
	[ITEM_PACK_YU_GI_OH__CHAMPIONSHIP_SERIES_2013_PRIZE_CARD] = 905,
	[ITEM_PACK_YU_GI_OH__CHAMPIONSHIP_SERIES_2014_PRIZE_CARD] = 906,
	[ITEM_PACK_YU_GI_OH__CHAMPIONSHIP_SERIES_2015_PRIZE_CARD] = 907,
	[ITEM_PACK_YU_GI_OH__CHAMPIONSHIP_SERIES_2016_PRIZE_CARD] = 908,
	[ITEM_PACK_YU_GI_OH__CHAMPIONSHIP_SERIES_2017_PRIZE_CARD] = 909,
	[ITEM_PACK_YU_GI_OH__CHAMPIONSHIP_SERIES_2018_PRIZE_CARD] = 910,
	[ITEM_PACK_YU_GI_OH__CHAMPIONSHIP_SERIES_2019_PRIZE_CARD] = 911,
	[ITEM_PACK_YU_GI_OH__CHAMPIONSHIP_SERIES_2022_PRIZE_CARD] = 912,
	[ITEM_PACK_YU_GI_OH__CHAMPIONSHIP_SERIES_2023_PRIZE_CARD] = 913,
	[ITEM_PACK_YU_GI_OH__DARK_DUEL_STORIES_PROMOTIONAL_CARDS] = 914,
	[ITEM_PACK_YU_GI_OH__DAY_APRIL_2019_PROMOTIONAL_CARD] = 915,
	[ITEM_PACK_YU_GI_OH__DESTINY_BOARD_TRAVELER_PROMOTIONAL_CARDS] = 916,
	[ITEM_PACK_YU_GI_OH__DOUBLE_PACK_PROMOTIONAL_CARDS] = 917,
	[ITEM_PACK_YU_GI_OH__ELEMENTAL_HERO_COLLECTION_1] = 918,
	[ITEM_PACK_YU_GI_OH__ELEMENTAL_HERO_COLLECTION_2] = 919,
	[ITEM_PACK_YU_GI_OH__FORBIDDEN_MEMORIES_PROMOTIONAL_CARDS] = 920,
	[ITEM_PACK_YU_GI_OH__GX_CARD_ALMANAC_PROMOTIONAL_CARDS] = 921,
	[ITEM_PACK_YU_GI_OH__GX_DUEL_ACADEMY_PROMOTIONAL_CARDS] = 922,
	[ITEM_PACK_YU_GI_OH__GX_SPECIAL_EDITION] = 923,
	[ITEM_PACK_YU_GI_OH__GX_SPIRIT_CALLER_PROMOTIONAL_CARDS] = 924,
	[ITEM_PACK_YU_GI_OH__GX_TAG_FORCE_2_PROMOTIONAL_CARDS] = 925,
	[ITEM_PACK_YU_GI_OH__GX_TAG_FORCE_3_PROMOTIONAL_CARDS] = 926,
	[ITEM_PACK_YU_GI_OH__GX_TAG_FORCE_EVOLUTION_PROMOTIONAL_CARDS] = 927,
	[ITEM_PACK_YU_GI_OH__GX_TAG_FORCE_PROMOTIONAL_CARDS] = 928,
	[ITEM_PACK_YU_GI_OH__GX_ULTIMATE_BEGINNER_S_PACK] = 929,
	[ITEM_PACK_YU_GI_OH__GX_VOLUME_1_PROMOTIONAL_CARD] = 930,
	[ITEM_PACK_YU_GI_OH__GX_VOLUME_2_PROMOTIONAL_CARD] = 931,
	[ITEM_PACK_YU_GI_OH__GX_VOLUME_3_PROMOTIONAL_CARD] = 932,
	[ITEM_PACK_YU_GI_OH__GX_VOLUME_4_PROMOTIONAL_CARD] = 933,
	[ITEM_PACK_YU_GI_OH__GX_VOLUME_5_PROMOTIONAL_CARD] = 934,
	[ITEM_PACK_YU_GI_OH__GX_VOLUME_6_PROMOTIONAL_CARD] = 935,
	[ITEM_PACK_YU_GI_OH__GX_VOLUME_7_PROMOTIONAL_CARD] = 936,
	[ITEM_PACK_YU_GI_OH__GX_VOLUME_8_PROMOTIONAL_CARD] = 937,
	[ITEM_PACK_YU_GI_OH__GX_VOLUME_9_PROMOTIONAL_CARD] = 938,
	[ITEM_PACK_YU_GI_OH__LEGACY_OF_THE_DUELIST__LINK_EVOLUTION_PROMOTIONAL_CARDS] = 939,
	[ITEM_PACK_YU_GI_OH__NIGHTMARE_TROUBADOUR_PROMOTIONAL_CARDS] = 940,
	[ITEM_PACK_YU_GI_OH__POWER_OF_CHAOS__JOEY_THE_PASSION_PROMOTIONAL_CARDS] = 941,
	[ITEM_PACK_YU_GI_OH__POWER_OF_CHAOS__KAIBA_THE_REVENGE_PROMOTIONAL_CARDS] = 942,
	[ITEM_PACK_YU_GI_OH__POWER_OF_CHAOS__YUGI_THE_DESTINY_PROMOTIONAL_CARDS] = 943,
	[ITEM_PACK_YU_GI_OH__R_VOLUME_1_PROMOTIONAL_CARD] = 944,
	[ITEM_PACK_YU_GI_OH__R_VOLUME_3_PROMOTIONAL_CARD] = 945,
	[ITEM_PACK_YU_GI_OH__R_VOLUME_4_PROMOTIONAL_CARD] = 946,
	[ITEM_PACK_YU_GI_OH__R_VOLUME_5_PROMOTIONAL_CARD] = 947,
	[ITEM_PACK_YU_GI_OH__RESHEF_OF_DESTRUCTION_PROMOTIONAL_CARDS] = 948,
	[ITEM_PACK_YU_GI_OH__TCG_REMOTE_DUEL_EXTRAVAGANZA_PARTICIPATION_CARD] = 949,
	[ITEM_PACK_YU_GI_OH__THE_DARK_SIDE_OF_DIMENSIONS_BLU_RAY___DVD_PROMOTIONAL_CARD] = 950,
	[ITEM_PACK_YU_GI_OH__THE_DARK_SIDE_OF_DIMENSIONS_MOVIE_PACK] = 951,
	[ITEM_PACK_YU_GI_OH__THE_DARK_SIDE_OF_DIMENSIONS_MOVIE_PACK_SECRET_EDITION] = 952,
	[ITEM_PACK_YU_GI_OH__THE_DARK_SIDE_OF_DIMENSIONS_MOVIE_PACK_SPECIAL_EDITION] = 953,
	[ITEM_PACK_YU_GI_OH__THE_DARK_SIDE_OF_DIMENSIONS_MOVIE_PACK__GOLD_EDITION] = 954,
	[ITEM_PACK_YU_GI_OH__THE_DARK_SIDE_OF_DIMENSIONS_THEATER_DISTRIBUTION_CARDS] = 955,
	[ITEM_PACK_YU_GI_OH__THE_DAWN_OF_DESTINY_PROMOTIONAL_CARDS] = 956,
	[ITEM_PACK_YU_GI_OH__THE_DUELISTS_OF_THE_ROSES_PROMOTIONAL_CARDS] = 957,
	[ITEM_PACK_YU_GI_OH__THE_ETERNAL_DUELIST_SOUL_PROMOTIONAL_CARDS] = 958,
	[ITEM_PACK_YU_GI_OH__THE_FALSEBOUND_KINGDOM_PROMOTIONAL_CARDS] = 959,
	[ITEM_PACK_YU_GI_OH__THE_SACRED_CARDS_PROMOTIONAL_CARDS] = 960,
	[ITEM_PACK_YU_GI_OH__TRADING_CARD_GAME_TOUR_2004_PROMOTIONAL_CARD] = 961,
	[ITEM_PACK_YU_GI_OH__ULTIMATE_MASTERS__WORLD_CHAMPIONSHIP_TOURNAMENT_2006_PROMOTIONAL_CARDS] = 962,
	[ITEM_PACK_YU_GI_OH__WORLD_CHAMPIONSHIP_2004_PRIZE_CARDS] = 963,
	[ITEM_PACK_YU_GI_OH__WORLD_CHAMPIONSHIP_2005_PRIZE_CARDS] = 964,
	[ITEM_PACK_YU_GI_OH__WORLD_CHAMPIONSHIP_2006_PRIZE_CARDS] = 965,
	[ITEM_PACK_YU_GI_OH__WORLD_CHAMPIONSHIP_2007_PRIZE_CARDS] = 966,
	[ITEM_PACK_YU_GI_OH__WORLD_CHAMPIONSHIP_2007_PROMOTIONAL_CARDS] = 967,
	[ITEM_PACK_YU_GI_OH__WORLD_CHAMPIONSHIP_2008_PROMOTIONAL_CARDS] = 968,
	[ITEM_PACK_YU_GI_OH__WORLD_CHAMPIONSHIP_2017_PRIZE_CARDS] = 969,
	[ITEM_PACK_YU_GI_OH__WORLD_CHAMPIONSHIP_2018_PRIZE_CARDS] = 970,
	[ITEM_PACK_YU_GI_OH__WORLD_CHAMPIONSHIP_2019_JAPANESE_NATIONAL_QUALIFIERS_PRIZE_CARDS] = 971,
	[ITEM_PACK_YU_GI_OH__WORLD_CHAMPIONSHIP_QUALIFIER_NATIONAL_CHAMPIONSHIPS_2011_PRIZE_CARDS] = 972,
	[ITEM_PACK_YU_GI_OH__WORLD_CHAMPIONSHIP_TOURNAMENT_2004_PROMOTIONAL_CARDS] = 973,
	[ITEM_PACK_YU_GI_OH__WORLDWIDE_EDITION__STAIRWAY_TO_THE_DESTINED_DUEL_PROMOTIONAL_CARDS] = 974,
	[ITEM_PACK_YU_GI_OH__ZEXAL_VOLUME_1_PROMOTIONAL_CARD] = 975,
	[ITEM_PACK_YU_GI_OH__ZEXAL_VOLUME_2_PROMOTIONAL_CARD] = 976,
	[ITEM_PACK_YU_GI_OH__ZEXAL_VOLUME_3_PROMOTIONAL_CARD] = 977,
	[ITEM_PACK_YU_GI_OH__ZEXAL_VOLUME_4_PROMOTIONAL_CARD] = 978,
	[ITEM_PACK_YU_GI_OH__ZEXAL_VOLUME_5_PROMOTIONAL_CARD] = 979,
	[ITEM_PACK_YU_GI_OH__ZEXAL_VOLUME_6_PROMOTIONAL_CARD] = 980,
	[ITEM_PACK_YU_GI_OH__ZEXAL_VOLUME_7_PROMOTIONAL_CARD] = 981,
	[ITEM_PACK_YU_GI_OH__ZEXAL_VOLUME_8_PROMOTIONAL_CARD] = 982,
	[ITEM_PACK_YU_GI_OH__ZEXAL_VOLUME_9_PROMOTIONAL_CARD] = 983,
	[ITEM_PACK_YU_GI_OH__ZEXAL_WORLD_DUEL_CARNIVAL_PROMOTIONAL_CARDS] = 984,
	[ITEM_PACK_YU_GI_OH__AT_HOME_SWEEPSTAKES] = 985,
	[ITEM_PACK_YUGI___KAIBA_COLLECTOR_BOX] = 986,
	[ITEM_PACK_YUGI_S_LEGENDARY_DECKS] = 987,
	[ITEM_PACK_ZEXAL_COLLECTION_TIN] = 988,
	[ITEM_PACK_ZOMBIE_WORLD_STRUCTURE_DECK] = 989,

extern const u8 gCardDescription_4StarredLadybugofDoom[];
extern const u8 gCardDescription_7ColoredFish[];
extern const u8 gCardDescription_ALegendaryOcean[];
extern const u8 gCardDescription_AbyssSoldier[];
extern const u8 gCardDescription_AirknightParshath[];
extern const u8 gCardDescription_AmazonessArcher[];
extern const u8 gCardDescription_AmphibiousBugrothMK3[];
extern const u8 gCardDescription_AntiSpellFragrance[];
extern const u8 gCardDescription_AquaMadoor[];
extern const u8 gCardDescription_AquaSpirit[];
extern const u8 gCardDescription_ArchfiendSoldier[];
extern const u8 gCardDescription_ArsenalBug[];
extern const u8 gCardDescription_ArsenalSummoner[];
extern const u8 gCardDescription_AsuraPriest[];
extern const u8 gCardDescription_AxeofDespair[];
extern const u8 gCardDescription_BanisheroftheLight[];
extern const u8 gCardDescription_BarrelBehindtheDoor[];
extern const u8 gCardDescription_BattleFootballer[];
extern const u8 gCardDescription_BattleOx[];
extern const u8 gCardDescription_BazootheSoulEater[];
extern const u8 gCardDescription_BerserkGorilla[];
extern const u8 gCardDescription_Bickuribox[];
extern const u8 gCardDescription_BigBangShot[];
extern const u8 gCardDescription_BigShieldGardna[];
extern const u8 gCardDescription_BigTuskedMammoth[];
extern const u8 gCardDescription_BlackIllusionRitual[];
extern const u8 gCardDescription_BlackLusterSoldierEnvoyoftheBeginning[];
extern const u8 gCardDescription_BlackPendant[];
extern const u8 gCardDescription_BlackSkullDragon[];
extern const u8 gCardDescription_BladeKnight[];
extern const u8 gCardDescription_BlastwithChain[];
extern const u8 gCardDescription_BlazingInpachi[];
extern const u8 gCardDescription_BlindlyLoyalGoblin[];
extern const u8 gCardDescription_BlockAttack[];
extern const u8 gCardDescription_BlowbackDragon[];
extern const u8 gCardDescription_BlueEyesUltimateDragon[];
extern const u8 gCardDescription_BlueEyesWhiteDragon[];
extern const u8 gCardDescription_BookofLife[];
extern const u8 gCardDescription_BookofMoon[];
extern const u8 gCardDescription_BookofTaiyou[];
extern const u8 gCardDescription_BottomlessTrapHole[];
extern const u8 gCardDescription_Bowganian[];
extern const u8 gCardDescription_BrainControl[];
extern const u8 gCardDescription_BreakertheMagicalWarrior[];
extern const u8 gCardDescription_BrowwHuntsmanofDarkWorld[];
extern const u8 gCardDescription_BrronMadKingofDarkWorld[];
extern const u8 gCardDescription_BusterBlader[];
extern const u8 gCardDescription_ByserShock[];
extern const u8 gCardDescription_CalloftheHaunted[];
extern const u8 gCardDescription_CannonSoldier[];
extern const u8 gCardDescription_CardDestruction[];
extern const u8 gCardDescription_CastleofDarkIllusions[];
extern const u8 gCardDescription_CastleWalls[];
extern const u8 gCardDescription_CatapultTurtle[];
extern const u8 gCardDescription_Ceasefire[];
extern const u8 gCardDescription_ChainDisappearance[];
extern const u8 gCardDescription_ChainEnergy[];
extern const u8 gCardDescription_ChainsawInsect[];
extern const u8 gCardDescription_ChangeofHeart[];
extern const u8 gCardDescription_ChaosEmperorDragonEnvoyoftheEnd[];
extern const u8 gCardDescription_ChaosSorcerer[];
extern const u8 gCardDescription_CharcoalInpachi[];
extern const u8 gCardDescription_ChirontheMage[];
extern const u8 gCardDescription_CipherSoldier[];
extern const u8 gCardDescription_ColdWave[];
extern const u8 gCardDescription_CommandKnight[];
extern const u8 gCardDescription_CompulsoryEvacuationDevice[];
extern const u8 gCardDescription_Confiscation[];
extern const u8 gCardDescription_CrassClown[];
extern const u8 gCardDescription_CreatureSwap[];
extern const u8 gCardDescription_CrushCardVirus[];
extern const u8 gCardDescription_CursedSealoftheForbiddenSpell[];
extern const u8 gCardDescription_CyberDragon[];
extern const u8 gCardDescription_CyberEndDragon[];
extern const u8 gCardDescription_CyberHarpieLady[];
extern const u8 gCardDescription_CyberJar[];
extern const u8 gCardDescription_CyberTwinDragon[];
extern const u8 gCardDescription_CyberStein[];
extern const u8 gCardDescription_DDAssailant[];
extern const u8 gCardDescription_DDCrazyBeast[];
extern const u8 gCardDescription_DDSurvivor[];
extern const u8 gCardDescription_DDTrainer[];
extern const u8 gCardDescription_DDWarriorLady[];
extern const u8 gCardDescription_DarkBlade[];
extern const u8 gCardDescription_DarkBladetheDragonKnight[];
extern const u8 gCardDescription_DarkDeal[];
extern const u8 gCardDescription_DarkElf[];
extern const u8 gCardDescription_DarkHole[];
extern const u8 gCardDescription_DarkMagicCurtain[];
extern const u8 gCardDescription_DarkMagician[];
extern const u8 gCardDescription_DarkMagicianofChaos[];
extern const u8 gCardDescription_DarkMimicLV1[];
extern const u8 gCardDescription_DarkMimicLV3[];
extern const u8 gCardDescription_DarkPaladin[];
extern const u8 gCardDescription_DarkRulerHaDes[];
extern const u8 gCardDescription_DarkScorpionChicktheYellow[];
extern const u8 gCardDescription_DarkScorpionClifftheTrapRemover[];
extern const u8 gCardDescription_DarkWorldLightning[];
extern const u8 gCardDescription_DeSpell[];
extern const u8 gCardDescription_DeckDevastationVirus[];
extern const u8 gCardDescription_DekoichitheBattlechantedLocomotive[];
extern const u8 gCardDescription_DelinquentDuo[];
extern const u8 gCardDescription_DesDendle[];
extern const u8 gCardDescription_DesKoala[];
extern const u8 gCardDescription_DesLacooda[];
extern const u8 gCardDescription_DesWombat[];
extern const u8 gCardDescription_DesertSunlight[];
extern const u8 gCardDescription_DianKetotheCureMaster[];
extern const u8 gCardDescription_DimensionFusion[];
extern const u8 gCardDescription_DonZaloog[];
extern const u8 gCardDescription_DoomDozer[];
extern const u8 gCardDescription_DoomcaliberKnight[];
extern const u8 gCardDescription_DraggedDownintotheGrave[];
extern const u8 gCardDescription_DragonsMirror[];
extern const u8 gCardDescription_DragonsRage[];
extern const u8 gCardDescription_DreamClown[];
extern const u8 gCardDescription_Drillroid[];
extern const u8 gCardDescription_DropOff[];
extern const u8 gCardDescription_DunamesDarkWitch[];
extern const u8 gCardDescription_DustTornado[];
extern const u8 gCardDescription_EarthboundSpirit[];
extern const u8 gCardDescription_ElectricSnake[];
extern const u8 gCardDescription_ElementalHEROClayman[];
extern const u8 gCardDescription_ElementalHEROFlameWingman[];
extern const u8 gCardDescription_ElementalHEROWildheart[];
extern const u8 gCardDescription_EmergencyProvisions[];
extern const u8 gCardDescription_EmissaryoftheAfterlife[];
extern const u8 gCardDescription_EnemyController[];
extern const u8 gCardDescription_ExarionUniverse[];
extern const u8 gCardDescription_Exchange[];
extern const u8 gCardDescription_ExchangeoftheSpirit[];
extern const u8 gCardDescription_ExiledForce[];
extern const u8 gCardDescription_ExodiatheForbiddenOne[];
extern const u8 gCardDescription_FakeTrap[];
extern const u8 gCardDescription_FamiliarPossessedAussa[];
extern const u8 gCardDescription_FamiliarPossessedEria[];
extern const u8 gCardDescription_FamiliarPossessedHiita[];
extern const u8 gCardDescription_FamiliarPossessedWynn[];
extern const u8 gCardDescription_FiberJar[];
extern const u8 gCardDescription_FinalFlame[];
extern const u8 gCardDescription_Fissure[];
extern const u8 gCardDescription_FlameSwordsman[];
extern const u8 gCardDescription_FlyingKamakiri1[];
extern const u8 gCardDescription_FusilierDragontheDualModeBeast[];
extern const u8 gCardDescription_Gagagigo[];
extern const u8 gCardDescription_GaiaPower[];
extern const u8 gCardDescription_GaiatheDragonChampion[];
extern const u8 gCardDescription_GatlingDragon[];
extern const u8 gCardDescription_GearGolemtheMovingFortress[];
extern const u8 gCardDescription_GearfriedtheIronKnight[];
extern const u8 gCardDescription_GeminiElf[];
extern const u8 gCardDescription_GiantGerm[];
extern const u8 gCardDescription_GiantOrc[];
extern const u8 gCardDescription_GiantRat[];
extern const u8 gCardDescription_GiantRedSeasnake[];
extern const u8 gCardDescription_GiantSoldierofStone[];
extern const u8 gCardDescription_GiantTrunade[];
extern const u8 gCardDescription_GigaTechWolf[];
extern const u8 gCardDescription_Gigantes[];
extern const u8 gCardDescription_GilGarth[];
extern const u8 gCardDescription_Gilasaurus[];
extern const u8 gCardDescription_GoblinAttackForce[];
extern const u8 gCardDescription_GoblinEliteAttackForce[];
extern const u8 gCardDescription_Gokipon[];
extern const u8 gCardDescription_GolemSentry[];
extern const u8 gCardDescription_GoraTurtle[];
extern const u8 gCardDescription_GracefulCharity[];
extern const u8 gCardDescription_GravekeepersAssailant[];
extern const u8 gCardDescription_GravekeepersGuard[];
extern const u8 gCardDescription_GravekeepersSpearSoldier[];
extern const u8 gCardDescription_GravekeepersSpy[];
extern const u8 gCardDescription_GravekeepersWatcher[];
extern const u8 gCardDescription_GravityBind[];
extern const u8 gCardDescription_GreatWhite[];
extern const u8 gCardDescription_GuardianSphinx[];
extern const u8 gCardDescription_GyakuGirePanda[];
extern const u8 gCardDescription_GyakutennoMegami[];
extern const u8 gCardDescription_HallowedLifeBarrier[];
extern const u8 gCardDescription_HaneHane[];
extern const u8 gCardDescription_HarpiesFeatherDuster[];
extern const u8 gCardDescription_HeavyStorm[];
extern const u8 gCardDescription_Hieracosphinx[];
extern const u8 gCardDescription_HornofHeaven[];
extern const u8 gCardDescription_HowlingInsect[];
extern const u8 gCardDescription_HumanoidSlime[];
extern const u8 gCardDescription_Hydrogeddon[];
extern const u8 gCardDescription_HyperHammerhead[];
extern const u8 gCardDescription_ImperialOrder[];
extern const u8 gCardDescription_InabaWhiteRabbit[];
extern const u8 gCardDescription_IndomitableFighterLeiLei[];
extern const u8 gCardDescription_InjectionFairyLily[];
extern const u8 gCardDescription_Inpachi[];
extern const u8 gCardDescription_InsectKnight[];
extern const u8 gCardDescription_IslandTurtle[];
extern const u8 gCardDescription_JarofGreed[];
extern const u8 gCardDescription_Jinzo[];
extern const u8 gCardDescription_JiraiGumo[];
extern const u8 gCardDescription_JowgentheSpiritualist[];
extern const u8 gCardDescription_JudgeMan[];
extern const u8 gCardDescription_JustDesserts[];
extern const u8 gCardDescription_KaiserSeaHorse[];
extern const u8 gCardDescription_KarmaCut[];
extern const u8 gCardDescription_KingDragun[];
extern const u8 gCardDescription_KingoftheSwamp[];
extern const u8 gCardDescription_KingTigerWanghu[];
extern const u8 gCardDescription_Kuriboh[];
extern const u8 gCardDescription_KycootheGhostDestroyer[];
extern const u8 gCardDescription_LaJinntheMysticalGenieoftheLamp[];
extern const u8 gCardDescription_LabyrinthTank[];
extern const u8 gCardDescription_LadyNinjaYae[];
extern const u8 gCardDescription_LastWill[];
extern const u8 gCardDescription_LeftArmoftheForbiddenOne[];
extern const u8 gCardDescription_LeftLegoftheForbiddenOne[];
extern const u8 gCardDescription_LegendaryJujitsuMaster[];
extern const u8 gCardDescription_LevelLimitAreaB[];
extern const u8 gCardDescription_LeviaDragonDaedalus[];
extern const u8 gCardDescription_LightofIntervention[];
extern const u8 gCardDescription_LightningVortex[];
extern const u8 gCardDescription_LimiterRemoval[];
extern const u8 gCardDescription_LusterDragon[];
extern const u8 gCardDescription_MadDogofDarkness[];
extern const u8 gCardDescription_MagePower[];
extern const u8 gCardDescription_MagicCylinder[];
extern const u8 gCardDescription_MagicJammer[];
extern const u8 gCardDescription_MagicalDimension[];
extern const u8 gCardDescription_MagicalMerchant[];
extern const u8 gCardDescription_MagicalScientist[];
extern const u8 gCardDescription_MagicianofFaith[];
extern const u8 gCardDescription_MagiciansCircle[];
extern const u8 gCardDescription_MagiciansValkyria[];
extern const u8 gCardDescription_MaidenoftheAqua[];
extern const u8 gCardDescription_MakyuratheDestructor[];
extern const u8 gCardDescription_ManEaterBug[];
extern const u8 gCardDescription_ManjuoftheTenThousandHands[];
extern const u8 gCardDescription_ManticoreofDarkness[];
extern const u8 gCardDescription_MaraudingCaptain[];
extern const u8 gCardDescription_MaskofDarkness[];
extern const u8 gCardDescription_MaskofRestrict[];
extern const u8 gCardDescription_MaskedDragon[];
extern const u8 gCardDescription_MaskedSorcerer[];
extern const u8 gCardDescription_MatazatheZapper[];
extern const u8 gCardDescription_Mechanicalchaser[];
extern const u8 gCardDescription_Megamorph[];
extern const u8 gCardDescription_MermaidKnight[];
extern const u8 gCardDescription_MessengerofPeace[];
extern const u8 gCardDescription_MetalReflectSlime[];
extern const u8 gCardDescription_Metamorphosis[];
extern const u8 gCardDescription_MilusRadiant[];
extern const u8 gCardDescription_Minar[];
extern const u8 gCardDescription_MindControl[];
extern const u8 gCardDescription_MineGolem[];
extern const u8 gCardDescription_MiracleRestoring[];
extern const u8 gCardDescription_MirageDragon[];
extern const u8 gCardDescription_MirageofNightmare[];
extern const u8 gCardDescription_MirrorForce[];
extern const u8 gCardDescription_MoaiInterceptorCannons[];
extern const u8 gCardDescription_MobiustheFrostMonarch[];
extern const u8 gCardDescription_MonsterGate[];
extern const u8 gCardDescription_MonsterReborn[];
extern const u8 gCardDescription_MonsterReincarnation[];
extern const u8 gCardDescription_MorphingJar[];
extern const u8 gCardDescription_MotherGrizzly[];
extern const u8 gCardDescription_MukaMuka[];
extern const u8 gCardDescription_MysticSwordsmanLV2[];
extern const u8 gCardDescription_MysticSwordsmanLV4[];
extern const u8 gCardDescription_MysticTomato[];
extern const u8 gCardDescription_MysticalElf[];
extern const u8 gCardDescription_MysticalSpaceTyphoon[];
extern const u8 gCardDescription_MystikWok[];
extern const u8 gCardDescription_Necrovalley[];
extern const u8 gCardDescription_NeedleCeiling[];
extern const u8 gCardDescription_NekoManeKing[];
extern const u8 gCardDescription_NeoBug[];
extern const u8 gCardDescription_NeotheMagicSwordsman[];
extern const u8 gCardDescription_Newdoria[];
extern const u8 gCardDescription_NightAssailant[];
extern const u8 gCardDescription_NightmareWheel[];
extern const u8 gCardDescription_NightmaresSteelcage[];
extern const u8 gCardDescription_NimbleMomonga[];
extern const u8 gCardDescription_NinKenDog[];
extern const u8 gCardDescription_NinjaGrandmasterSasuke[];
extern const u8 gCardDescription_NoblemanofCrossout[];
extern const u8 gCardDescription_NoblemanofExtermination[];
extern const u8 gCardDescription_OfferingstotheDoomed[];
extern const u8 gCardDescription_OjamaKing[];
extern const u8 gCardDescription_OjamaTrio[];
extern const u8 gCardDescription_Ookazi[];
extern const u8 gCardDescription_OppressedPeople[];
extern const u8 gCardDescription_Opticlops[];
extern const u8 gCardDescription_PainfulChoice[];
extern const u8 gCardDescription_PaladinofWhiteDragon[];
extern const u8 gCardDescription_PenguinKnight[];
extern const u8 gCardDescription_PhoenixWingWindBlast[];
extern const u8 gCardDescription_PikerusCircleofEnchantment[];
extern const u8 gCardDescription_PinchHopper[];
extern const u8 gCardDescription_PitchBlackPowerStone[];
extern const u8 gCardDescription_PoisonoftheOldMan[];
extern const u8 gCardDescription_Polymerization[];
extern const u8 gCardDescription_PotofAvarice[];
extern const u8 gCardDescription_PotofGenerosity[];
extern const u8 gCardDescription_PotofGreed[];
extern const u8 gCardDescription_PrematureBurial[];
extern const u8 gCardDescription_PreventRat[];
extern const u8 gCardDescription_PrickleFairy[];
extern const u8 gCardDescription_PrincessofTsurugi[];
extern const u8 gCardDescription_ProtectoroftheSanctuary[];
extern const u8 gCardDescription_PyramidTurtle[];
extern const u8 gCardDescription_Raigeki[];
extern const u8 gCardDescription_RaigekiBreak[];
extern const u8 gCardDescription_ReaperontheNightmare[];
extern const u8 gCardDescription_Reasoning[];
extern const u8 gCardDescription_RecklessGreed[];
extern const u8 gCardDescription_ReflectBounder[];
extern const u8 gCardDescription_ReinforcementoftheArmy[];
extern const u8 gCardDescription_Reinforcements[];
extern const u8 gCardDescription_Relinquished[];
extern const u8 gCardDescription_Reload[];
extern const u8 gCardDescription_RemoveTrap[];
extern const u8 gCardDescription_RescueCat[];
extern const u8 gCardDescription_ReturnfromtheDifferentDimension[];
extern const u8 gCardDescription_RightArmoftheForbiddenOne[];
extern const u8 gCardDescription_RightLegoftheForbiddenOne[];
extern const u8 gCardDescription_RingofDestruction[];
extern const u8 gCardDescription_RisingAirCurrent[];
extern const u8 gCardDescription_RobbinGoblin[];
extern const u8 gCardDescription_RouletteBarrel[];
extern const u8 gCardDescription_RoyalDecree[];
extern const u8 gCardDescription_RoyalMagicalLibrary[];
extern const u8 gCardDescription_RoyalOppression[];
extern const u8 gCardDescription_RushRecklessly[];
extern const u8 gCardDescription_RyuKokki[];
extern const u8 gCardDescription_SaberBeetle[];
extern const u8 gCardDescription_SacredCrane[];
extern const u8 gCardDescription_SacredPhoenixofNephthys[];
extern const u8 gCardDescription_SakuretsuArmor[];
extern const u8 gCardDescription_Salvage[];
extern const u8 gCardDescription_SandMoth[];
extern const u8 gCardDescription_Sangan[];
extern const u8 gCardDescription_SasukeSamurai[];
extern const u8 gCardDescription_SasukeSamurai4[];
extern const u8 gCardDescription_Scapegoat[];
extern const u8 gCardDescription_SeaSerpentWarriorofDarkness[];
extern const u8 gCardDescription_SecondCoinToss[];
extern const u8 gCardDescription_SecretBarrel[];
extern const u8 gCardDescription_SelfDestructButton[];
extern const u8 gCardDescription_SerialSpell[];
extern const u8 gCardDescription_SerpentinePrincess[];
extern const u8 gCardDescription_SevenToolsoftheBandit[];
extern const u8 gCardDescription_ShiningAngel[];
extern const u8 gCardDescription_Shrink[];
extern const u8 gCardDescription_SillvaWarlordofDarkWorld[];
extern const u8 gCardDescription_Silpheed[];
extern const u8 gCardDescription_SinisterSerpent[];
extern const u8 gCardDescription_SkillDrain[];
extern const u8 gCardDescription_SkilledDarkMagician[];
extern const u8 gCardDescription_SkilledWhiteMagician[];
extern const u8 gCardDescription_SkullDogMarron[];
extern const u8 gCardDescription_SkullLair[];
extern const u8 gCardDescription_SkyScout[];
extern const u8 gCardDescription_SlateWarrior[];
extern const u8 gCardDescription_SmashingGround[];
extern const u8 gCardDescription_SnatchSteal[];
extern const u8 gCardDescription_SolemnJudgment[];
extern const u8 gCardDescription_SolemnWishes[];
extern const u8 gCardDescription_SoulExchange[];
extern const u8 gCardDescription_SoulTiger[];
extern const u8 gCardDescription_SpearCretin[];
extern const u8 gCardDescription_SpearDragon[];
extern const u8 gCardDescription_SpellCanceller[];
extern const u8 gCardDescription_SpellReproduction[];
extern const u8 gCardDescription_SpiritoftheHarp[];
extern const u8 gCardDescription_SpiritReaper[];
extern const u8 gCardDescription_SpiritualEarthArtKurogane[];
extern const u8 gCardDescription_SpiritualWaterArtAoi[];
extern const u8 gCardDescription_SpiritualWindArtMiyabi[];
extern const u8 gCardDescription_Spiritualism[];
extern const u8 gCardDescription_StealthBird[];
extern const u8 gCardDescription_StoneStatueoftheAztecs[];
extern const u8 gCardDescription_StopDefense[];
extern const u8 gCardDescription_SummonedSkull[];
extern const u8 gCardDescription_SwarmofLocusts[];
extern const u8 gCardDescription_SwarmofScarabs[];
extern const u8 gCardDescription_SwordsofRevealingLight[];
extern const u8 gCardDescription_Terraforming[];
extern const u8 gCardDescription_TheBigMarchofAnimals[];
extern const u8 gCardDescription_TheDragonDwellingintheCave[];
extern const u8 gCardDescription_TheFiendMegacyber[];
extern const u8 gCardDescription_TheForcefulSentry[];
extern const u8 gCardDescription_TheForgivingMaiden[];
extern const u8 gCardDescription_TheLastWarriorfromAnotherPlanet[];
extern const u8 gCardDescription_TheLittleSwordsmanofAile[];
extern const u8 gCardDescription_TheWickedWormBeast[];
extern const u8 gCardDescription_ThestalostheFirestormMonarch[];
extern const u8 gCardDescription_ThousandEyesRestrict[];
extern const u8 gCardDescription_ThreateningRoar[];
extern const u8 gCardDescription_ThrowstoneUnit[];
extern const u8 gCardDescription_ThunderDragon[];
extern const u8 gCardDescription_ThunderNyanNyan[];
extern const u8 gCardDescription_TimeSeal[];
extern const u8 gCardDescription_ToonCannonSoldier[];
extern const u8 gCardDescription_ToonDarkMagicianGirl[];
extern const u8 gCardDescription_ToonGeminiElf[];
extern const u8 gCardDescription_ToonGoblinAttackForce[];
extern const u8 gCardDescription_ToonMaskedSorcerer[];
extern const u8 gCardDescription_ToonTableofContents[];
extern const u8 gCardDescription_TorrentialTribute[];
extern const u8 gCardDescription_TrapDustshoot[];
extern const u8 gCardDescription_TrapHole[];
extern const u8 gCardDescription_TrapMaster[];
extern const u8 gCardDescription_TreebornFrog[];
extern const u8 gCardDescription_TremendousFire[];
extern const u8 gCardDescription_TribeInfectingVirus[];
extern const u8 gCardDescription_TributetotheDoomed[];
extern const u8 gCardDescription_Tsukuyomi[];
extern const u8 gCardDescription_TwinHeadedBehemoth[];
extern const u8 gCardDescription_TwinHeadedThunderDragon[];
extern const u8 gCardDescription_UltimateInsectLV3[];
extern const u8 gCardDescription_UltimateInsectLV5[];
extern const u8 gCardDescription_UltimateInsectLV7[];
extern const u8 gCardDescription_UltimateOffering[];
extern const u8 gCardDescription_UnitedWeStand[];
extern const u8 gCardDescription_UpstartGoblin[];
extern const u8 gCardDescription_VampireLord[];
extern const u8 gCardDescription_VorseRaider[];
extern const u8 gCardDescription_Waboku[];
extern const u8 gCardDescription_WallofIllusion[];
extern const u8 gCardDescription_WallofRevealingLight[];
extern const u8 gCardDescription_WaveMotionCannon[];
extern const u8 gCardDescription_WhiteDragonRitual[];
extern const u8 gCardDescription_WhiteMagicalHat[];
extern const u8 gCardDescription_WidespreadRuin[];
extern const u8 gCardDescription_WitchoftheBlackForest[];
extern const u8 gCardDescription_XHeadCannon[];
extern const u8 gCardDescription_XingZhenHu[];
extern const u8 gCardDescription_YataGarasu[];
extern const u8 gCardDescription_YomiShip[];
extern const u8 gCardDescription_ZaborgtheThunderMonarch[];
extern const u8 gCardDescription_ZombyratheDark[];
extern const u8 gCardDescription_ZureKnightofDarkWorld[];
extern const u8 gCardDescription_AmazonessSpiritualist[];
extern const u8 gCardDescription_ArchfiendCavalry[];
extern const u8 gCardDescription_ArchfiendHeiress[];
extern const u8 gCardDescription_ArchfiendInterceptor[];
extern const u8 gCardDescription_BakutheBeastNinja[];
extern const u8 gCardDescription_BeginningKnight[];
extern const u8 gCardDescription_BeiigeVanguardofDarkWorld[];
extern const u8 gCardDescription_BerlineththeFirestormVassal[];
extern const u8 gCardDescription_BlackDragonsChick[];
extern const u8 gCardDescription_BlackMetalDragon[];
extern const u8 gCardDescription_BlueFlameSwordsman[];
extern const u8 gCardDescription_BoneArchfiend[];
extern const u8 gCardDescription_ChronicleSorceress[];
extern const u8 gCardDescription_CyberDragonDrei[];
extern const u8 gCardDescription_CyberDragonVier[];
extern const u8 gCardDescription_CyberDragonZwei[];
extern const u8 gCardDescription_CyberLarva[];
extern const u8 gCardDescription_DefenderofNephthys[];
extern const u8 gCardDescription_DictatorofD[];
extern const u8 gCardDescription_DimensionConjurer[];
extern const u8 gCardDescription_DiscipleofNephthys[];
extern const u8 gCardDescription_DupeFrog[];
extern const u8 gCardDescription_EidostheUnderworldSquire[];
extern const u8 gCardDescription_ElementalHEROBlazeman[];
extern const u8 gCardDescription_ElementalHEROWoodsman[];
extern const u8 gCardDescription_EnvoyofChaos[];
extern const u8 gCardDescription_EveningTwilightKnight[];
extern const u8 gCardDescription_FightingFlameSwordsman[];
extern const u8 gCardDescription_FlipFlopFrog[];
extern const u8 gCardDescription_FusionDevourer[];
extern const u8 gCardDescription_GearfriedtheRedEyesIronKnight[];
extern const u8 gCardDescription_GemKnightQuartz[];
extern const u8 gCardDescription_GentaGatemanofDarkWorld[];
extern const u8 gCardDescription_GoblinPotholeSquad[];
extern const u8 gCardDescription_GreenNinja[];
extern const u8 gCardDescription_GrenTacticianofDarkWorld[];
extern const u8 gCardDescription_HandofNephthys[];
extern const u8 gCardDescription_IceKnight[];
extern const u8 gCardDescription_KagerotheCannonNinja[];
extern const u8 gCardDescription_Kaibaman[];
extern const u8 gCardDescription_KeeperofDragonMagic[];
extern const u8 gCardDescription_KeeperoftheShrine[];
extern const u8 gCardDescription_LancerArchfiend[];
extern const u8 gCardDescription_LordofD[];
extern const u8 gCardDescription_LuciustheShadowVassal[];
extern const u8 gCardDescription_MadArchfiend[];
extern const u8 gCardDescription_MagiciansRobe[];
extern const u8 gCardDescription_MagiciansRod[];
extern const u8 gCardDescription_MagiciansSouls[];
extern const u8 gCardDescription_Magikuriboh[];
extern const u8 gCardDescription_MaskedNinjaEbisu[];
extern const u8 gCardDescription_MatriarchofNephthys[];
extern const u8 gCardDescription_MitsutheInsectNinja[];
extern const u8 gCardDescription_MysticalElfWhiteLightning[];
extern const u8 gCardDescription_NinjaGrandmasterHanzo[];
extern const u8 gCardDescription_ParlHermitofDarkWorld[];
extern const u8 gCardDescription_RedEyesBabyDragon[];
extern const u8 gCardDescription_RedEyesRetroDragon[];
extern const u8 gCardDescription_RedEyesWyvern[];
extern const u8 gCardDescription_Relinkuriboh[];
extern const u8 gCardDescription_Ronintoadin[];
extern const u8 gCardDescription_SalamandratheFlyingFlameDragon[];
extern const u8 gCardDescription_ScarrScoutofDarkWorld[];
extern const u8 gCardDescription_SenjuoftheThousandHands[];
extern const u8 gCardDescription_SkilledRedMagician[];
extern const u8 gCardDescription_SnowwUnlightofDarkWorld[];
extern const u8 gCardDescription_SonicBird[];
extern const u8 gCardDescription_SphereKuriboh[];
extern const u8 gCardDescription_Substitoad[];
extern const u8 gCardDescription_SuperSoldierSoul[];
extern const u8 gCardDescription_SwapFrog[];
extern const u8 gCardDescription_TADPOLE[];
extern const u8 gCardDescription_TheBlackStoneofLegend[];
extern const u8 gCardDescription_TheDarkHexSealedFusion[];
extern const u8 gCardDescription_TheEarthHexSealedFusion[];
extern const u8 gCardDescription_TheLightHexSealedFusion[];
extern const u8 gCardDescription_ThunderDragonmatrix[];
extern const u8 gCardDescription_ThunderSeaHorse[];
extern const u8 gCardDescription_TobaritheSkyNinja[];
extern const u8 gCardDescription_Tradetoad[];
extern const u8 gCardDescription_TraptrixArachnocampa[];
extern const u8 gCardDescription_TraptrixAtrax[];
extern const u8 gCardDescription_TraptrixDionaea[];
extern const u8 gCardDescription_TraptrixGenlisea[];
extern const u8 gCardDescription_TraptrixMantis[];
extern const u8 gCardDescription_TraptrixMyrmeleo[];
extern const u8 gCardDescription_TraptrixNepenthes[];
extern const u8 gCardDescription_TraptrixPudica[];
extern const u8 gCardDescription_TraptrixVesiculo[];
extern const u8 gCardDescription_TwilightNinjaShingetsu[];
extern const u8 gCardDescription_UpstartGoldenNinja[];
extern const u8 gCardDescription_VisionHEROVyon[];
extern const u8 gCardDescription_Wroughtweiler[];
extern const u8 gCardDescription_YellowNinja[];
