#ifndef GUARD_YGO_H
#define GUARD_YGO_H

struct CardInfo
{
    /* 0x00 */ const u8 *name;
    /* 0x04 */ const u8 *nameShort;
    /* 0x08 */ const u8 *nameShortBag;
    /* 0x0C */ const u8 *description;
    /* 0x10 */ const u8 password[9];
    /* 0x1C */ const u32 *pic;
    /* 0x20 */ const u16 *pal;
    /* 0x24 */ const u32 *iconSquare;
    /* 0x2C */ const u32 *iconSmall;
    /* 0x20 */ const u32 *palIconSmall;
    /* 0x28 */ const u32 *iconTiny;
    /* 0x20 */ const u32 *palIconTiny;
    /* 0x30 */ u16 effects[8];
    /* 0x40 */ u32 type:5;
    /* 0x40 */ u32 attribute:3;
    /* 0x41 */ u32 level:4;
    /* 0x41 */ u32 atk:9;
    /* 0x42 */ u32 def:9;
    /* 0x44 */ u8 race;
    /* 0x46 */ u16 id;
    /* 0x48 */ u16 archetypesSeries[3];
    /* 0x50 */ u32 priceYK:10;
    /* 0x51 */ u32 priceCritter:10;
    /* 0x52 */ u32 priceTreasure:10;
    /* 0x54 */ u32 priceImperial:10;
    /* 0x55 */ u32 priceAndroid:10;
    /* 0x56 */ u32 priceJoeyPegasus:10;
    /* 0x58 */ u32 priceFiber:10;
    /* 0x59 */ u32 priceYata:10;
    /* 0x5A */ u32 priceScientist:10;
    /* 0x5C */ u32 priceVampire:10;
    /* 0x5D */ u32 priceChaos:10;
    /* 0x5E */ u32 priceWarrior:10;
    /* 0x60 */ u32 priceGoat:10;
    /* 0x61 */ u32 priceCyber:10;
    /* 0x62 */ u32 priceReaper:10;
    /* 0x64 */ u32 priceChaosReturn:10;
    /* 0x65 */ u32 priceDemise:10;
    /* 0x66 */ u32 priceTrooper:10;
    /* 0x68 */ u32 priceZombie:10;
    /* 0x69 */ u32 pricePerfectCircle:10;
    /* 0x6A */ u32 priceDADReturn:10;
    /* 0x6C */ u32 priceGladiator:10;
    /* 0x6D */ u32 priceTeleDAD:10;
    /* 0x6E */ u32 priceCat:10;
    /* 0x70 */ u32 priceEdison:10;
    /* 0x71 */ u32 priceFrog:10;
    /* 0x72 */ u32 priceStarstrike:10;
    /* 0x74 */ u32 priceTengu:10;
    /* 0x75 */ u32 priceDinoRabbit:10;
    /* 0x76 */ u32 priceWindUp:10;
    /* 0x78 */ u32 priceMiami:10;
    /* 0x79 */ u32 priceMeadowlands:10;
    /* 0x7A */ u32 priceBabyRuler:10;
    /* 0x7C */ u32 priceRavineRuler:10;
    /* 0x7D */ u32 priceFireWater:10;
    /* 0x7D */ u32 priceHAT:10;
    /* 0x7E */ u32 priceVegas:10;
    /* 0x80 */ u32 priceWCT06:10;
    /* 0x80 */ u32 priceCustom:10;
    /* 0x81 */ u32 priceVendor1:10;
    /* 0x82 */ u32 priceVendor2:10;
    /* 0x84 */ u32 priceVendor3:10;
    /* 0x50 */ u32 banYK:2;
    /* 0x51 */ u32 banCritter:2;
    /* 0x52 */ u32 banTreasure:2;
    /* 0x54 */ u32 banImperial:2;
    /* 0x55 */ u32 banAndroid:2;
    /* 0x56 */ u32 banJoeyPegasus:2;
    /* 0x58 */ u32 banFiber:2;
    /* 0x59 */ u32 banYata:2;
    /* 0x5A */ u32 banScientist:2;
    /* 0x5C */ u32 banVampire:2;
    /* 0x5D */ u32 banChaos:2;
    /* 0x5E */ u32 banWarrior:2;
    /* 0x60 */ u32 banGoat:2;
    /* 0x61 */ u32 banCyber:2;
    /* 0x62 */ u32 banReaper:2;
    /* 0x64 */ u32 banChaosReturn:2;
    /* 0x65 */ u32 banDemise:2;
    /* 0x66 */ u32 banTrooper:2;
    /* 0x68 */ u32 banZombie:2;
    /* 0x69 */ u32 banPerfectCircle:2;
    /* 0x6A */ u32 banDADReturn:2;
    /* 0x6C */ u32 banGladiator:2;
    /* 0x6D */ u32 banTeleDAD:2;
    /* 0x6E */ u32 banCat:2;
    /* 0x70 */ u32 banEdison:2;
    /* 0x71 */ u32 banFrog:2;
    /* 0x72 */ u32 banStarstrike:2;
    /* 0x74 */ u32 banTengu:2;
    /* 0x75 */ u32 banDinoRabbit:2;
    /* 0x76 */ u32 banWindUp:2;
    /* 0x78 */ u32 banMiami:2;
    /* 0x79 */ u32 banMeadowlands:2;
    /* 0x7A */ u32 banBabyRuler:2;
    /* 0x7C */ u32 banRavineRuler:2;
    /* 0x7D */ u32 banFireWater:2;
    /* 0x7D */ u32 banHAT:2;
    /* 0x7E */ u32 banVegas:2;
    /* 0x80 */ u32 banWCT06:2;
    /* 0x80 */ u32 banCustom:2;
    /* 0x81 */ u32 banVendor1:2;
    /* 0x82 */ u32 banVendor2:2;
    /* 0x84 */ u32 banVendor3:2;
};

struct PackContents
{
    u16 card;
    u8 rarity;
};

struct Pack
{
    const struct PackContents *pack;
    u16 length;
};

extern const struct Pack gPacks[];
extern const struct CardInfo gCardInfo[];
extern const u8 gCardDescription_4StarredLadybugofDoom[];
extern const u8 gCardDescription_7ColoredFish[];
extern const u8 gCardDescription_ALegendaryOcean[];
extern const u8 gCardDescription_AbyssSoldier[];
extern const u8 gCardDescription_AirknightParshath[];
extern const u8 gCardDescription_AmazonessArcher[];
extern const u8 gCardDescription_AmphibiousBugrothMK3[];
extern const u8 gCardDescription_AntiSpellFragrance[];
extern const u8 gCardDescription_AquaMadoor[];
extern const u8 gCardDescription_AquaSpirit[];
extern const u8 gCardDescription_ArchfiendSoldier[];
extern const u8 gCardDescription_ArsenalBug[];
extern const u8 gCardDescription_ArsenalSummoner[];
extern const u8 gCardDescription_AsuraPriest[];
extern const u8 gCardDescription_AxeofDespair[];
extern const u8 gCardDescription_BanisheroftheLight[];
extern const u8 gCardDescription_BarrelBehindtheDoor[];
extern const u8 gCardDescription_BattleFootballer[];
extern const u8 gCardDescription_BattleOx[];
extern const u8 gCardDescription_BazootheSoulEater[];
extern const u8 gCardDescription_BerserkGorilla[];
extern const u8 gCardDescription_Bickuribox[];
extern const u8 gCardDescription_BigBangShot[];
extern const u8 gCardDescription_BigShieldGardna[];
extern const u8 gCardDescription_BigTuskedMammoth[];
extern const u8 gCardDescription_BlackIllusionRitual[];
extern const u8 gCardDescription_BlackLusterSoldierEnvoyoftheBeginning[];
extern const u8 gCardDescription_BlackPendant[];
extern const u8 gCardDescription_BlackSkullDragon[];
extern const u8 gCardDescription_BladeKnight[];
extern const u8 gCardDescription_BlastwithChain[];
extern const u8 gCardDescription_BlazingInpachi[];
extern const u8 gCardDescription_BlindlyLoyalGoblin[];
extern const u8 gCardDescription_BlockAttack[];
extern const u8 gCardDescription_BlowbackDragon[];
extern const u8 gCardDescription_BlueEyesUltimateDragon[];
extern const u8 gCardDescription_BlueEyesWhiteDragon[];
extern const u8 gCardDescription_BookofLife[];
extern const u8 gCardDescription_BookofMoon[];
extern const u8 gCardDescription_BookofTaiyou[];
extern const u8 gCardDescription_BottomlessTrapHole[];
extern const u8 gCardDescription_Bowganian[];
extern const u8 gCardDescription_BrainControl[];
extern const u8 gCardDescription_BreakertheMagicalWarrior[];
extern const u8 gCardDescription_BrowwHuntsmanofDarkWorld[];
extern const u8 gCardDescription_BrronMadKingofDarkWorld[];
extern const u8 gCardDescription_BusterBlader[];
extern const u8 gCardDescription_ByserShock[];
extern const u8 gCardDescription_CalloftheHaunted[];
extern const u8 gCardDescription_CannonSoldier[];
extern const u8 gCardDescription_CardDestruction[];
extern const u8 gCardDescription_CastleofDarkIllusions[];
extern const u8 gCardDescription_CastleWalls[];
extern const u8 gCardDescription_CatapultTurtle[];
extern const u8 gCardDescription_Ceasefire[];
extern const u8 gCardDescription_ChainDisappearance[];
extern const u8 gCardDescription_ChainEnergy[];
extern const u8 gCardDescription_ChainsawInsect[];
extern const u8 gCardDescription_ChangeofHeart[];
extern const u8 gCardDescription_ChaosEmperorDragonEnvoyoftheEnd[];
extern const u8 gCardDescription_ChaosSorcerer[];
extern const u8 gCardDescription_CharcoalInpachi[];
extern const u8 gCardDescription_ChirontheMage[];
extern const u8 gCardDescription_CipherSoldier[];
extern const u8 gCardDescription_ColdWave[];
extern const u8 gCardDescription_CommandKnight[];
extern const u8 gCardDescription_CompulsoryEvacuationDevice[];
extern const u8 gCardDescription_Confiscation[];
extern const u8 gCardDescription_CrassClown[];
extern const u8 gCardDescription_CreatureSwap[];
extern const u8 gCardDescription_CrushCardVirus[];
extern const u8 gCardDescription_CursedSealoftheForbiddenSpell[];
extern const u8 gCardDescription_CyberDragon[];
extern const u8 gCardDescription_CyberEndDragon[];
extern const u8 gCardDescription_CyberHarpieLady[];
extern const u8 gCardDescription_CyberJar[];
extern const u8 gCardDescription_CyberTwinDragon[];
extern const u8 gCardDescription_CyberStein[];
extern const u8 gCardDescription_DDAssailant[];
extern const u8 gCardDescription_DDCrazyBeast[];
extern const u8 gCardDescription_DDSurvivor[];
extern const u8 gCardDescription_DDTrainer[];
extern const u8 gCardDescription_DDWarriorLady[];
extern const u8 gCardDescription_DarkBlade[];
extern const u8 gCardDescription_DarkBladetheDragonKnight[];
extern const u8 gCardDescription_DarkDeal[];
extern const u8 gCardDescription_DarkElf[];
extern const u8 gCardDescription_DarkHole[];
extern const u8 gCardDescription_DarkMagicCurtain[];
extern const u8 gCardDescription_DarkMagician[];
extern const u8 gCardDescription_DarkMagicianofChaos[];
extern const u8 gCardDescription_DarkMimicLV1[];
extern const u8 gCardDescription_DarkMimicLV3[];
extern const u8 gCardDescription_DarkPaladin[];
extern const u8 gCardDescription_DarkRulerHaDes[];
extern const u8 gCardDescription_DarkScorpionChicktheYellow[];
extern const u8 gCardDescription_DarkScorpionClifftheTrapRemover[];
extern const u8 gCardDescription_DarkWorldLightning[];
extern const u8 gCardDescription_DeSpell[];
extern const u8 gCardDescription_DeckDevastationVirus[];
extern const u8 gCardDescription_DekoichitheBattlechantedLocomotive[];
extern const u8 gCardDescription_DelinquentDuo[];
extern const u8 gCardDescription_DesDendle[];
extern const u8 gCardDescription_DesKoala[];
extern const u8 gCardDescription_DesLacooda[];
extern const u8 gCardDescription_DesWombat[];
extern const u8 gCardDescription_DesertSunlight[];
extern const u8 gCardDescription_DianKetotheCureMaster[];
extern const u8 gCardDescription_DimensionFusion[];
extern const u8 gCardDescription_DonZaloog[];
extern const u8 gCardDescription_DoomDozer[];
extern const u8 gCardDescription_DoomcaliberKnight[];
extern const u8 gCardDescription_DraggedDownintotheGrave[];
extern const u8 gCardDescription_DragonsMirror[];
extern const u8 gCardDescription_DragonsRage[];
extern const u8 gCardDescription_DreamClown[];
extern const u8 gCardDescription_Drillroid[];
extern const u8 gCardDescription_DropOff[];
extern const u8 gCardDescription_DunamesDarkWitch[];
extern const u8 gCardDescription_DustTornado[];
extern const u8 gCardDescription_EarthboundSpirit[];
extern const u8 gCardDescription_ElectricSnake[];
extern const u8 gCardDescription_ElementalHEROClayman[];
extern const u8 gCardDescription_ElementalHEROFlameWingman[];
extern const u8 gCardDescription_ElementalHEROWildheart[];
extern const u8 gCardDescription_EmergencyProvisions[];
extern const u8 gCardDescription_EmissaryoftheAfterlife[];
extern const u8 gCardDescription_EnemyController[];
extern const u8 gCardDescription_ExarionUniverse[];
extern const u8 gCardDescription_Exchange[];
extern const u8 gCardDescription_ExchangeoftheSpirit[];
extern const u8 gCardDescription_ExiledForce[];
extern const u8 gCardDescription_ExodiatheForbiddenOne[];
extern const u8 gCardDescription_FakeTrap[];
extern const u8 gCardDescription_FamiliarPossessedAussa[];
extern const u8 gCardDescription_FamiliarPossessedEria[];
extern const u8 gCardDescription_FamiliarPossessedHiita[];
extern const u8 gCardDescription_FamiliarPossessedWynn[];
extern const u8 gCardDescription_FiberJar[];
extern const u8 gCardDescription_FinalFlame[];
extern const u8 gCardDescription_Fissure[];
extern const u8 gCardDescription_FlameSwordsman[];
extern const u8 gCardDescription_FlyingKamakiri1[];
extern const u8 gCardDescription_FusilierDragontheDualModeBeast[];
extern const u8 gCardDescription_Gagagigo[];
extern const u8 gCardDescription_GaiaPower[];
extern const u8 gCardDescription_GaiatheDragonChampion[];
extern const u8 gCardDescription_GatlingDragon[];
extern const u8 gCardDescription_GearGolemtheMovingFortress[];
extern const u8 gCardDescription_GearfriedtheIronKnight[];
extern const u8 gCardDescription_GeminiElf[];
extern const u8 gCardDescription_GiantGerm[];
extern const u8 gCardDescription_GiantOrc[];
extern const u8 gCardDescription_GiantRat[];
extern const u8 gCardDescription_GiantRedSeasnake[];
extern const u8 gCardDescription_GiantSoldierofStone[];
extern const u8 gCardDescription_GiantTrunade[];
extern const u8 gCardDescription_GigaTechWolf[];
extern const u8 gCardDescription_Gigantes[];
extern const u8 gCardDescription_GilGarth[];
extern const u8 gCardDescription_Gilasaurus[];
extern const u8 gCardDescription_GoblinAttackForce[];
extern const u8 gCardDescription_GoblinEliteAttackForce[];
extern const u8 gCardDescription_Gokipon[];
extern const u8 gCardDescription_GolemSentry[];
extern const u8 gCardDescription_GoraTurtle[];
extern const u8 gCardDescription_GracefulCharity[];
extern const u8 gCardDescription_GravekeepersAssailant[];
extern const u8 gCardDescription_GravekeepersGuard[];
extern const u8 gCardDescription_GravekeepersSpearSoldier[];
extern const u8 gCardDescription_GravekeepersSpy[];
extern const u8 gCardDescription_GravekeepersWatcher[];
extern const u8 gCardDescription_GravityBind[];
extern const u8 gCardDescription_GreatWhite[];
extern const u8 gCardDescription_GuardianSphinx[];
extern const u8 gCardDescription_GyakuGirePanda[];
extern const u8 gCardDescription_GyakutennoMegami[];
extern const u8 gCardDescription_HallowedLifeBarrier[];
extern const u8 gCardDescription_HaneHane[];
extern const u8 gCardDescription_HarpiesFeatherDuster[];
extern const u8 gCardDescription_HeavyStorm[];
extern const u8 gCardDescription_Hieracosphinx[];
extern const u8 gCardDescription_HornofHeaven[];
extern const u8 gCardDescription_HowlingInsect[];
extern const u8 gCardDescription_HumanoidSlime[];
extern const u8 gCardDescription_Hydrogeddon[];
extern const u8 gCardDescription_HyperHammerhead[];
extern const u8 gCardDescription_ImperialOrder[];
extern const u8 gCardDescription_InabaWhiteRabbit[];
extern const u8 gCardDescription_IndomitableFighterLeiLei[];
extern const u8 gCardDescription_InjectionFairyLily[];
extern const u8 gCardDescription_Inpachi[];
extern const u8 gCardDescription_InsectKnight[];
extern const u8 gCardDescription_IslandTurtle[];
extern const u8 gCardDescription_JarofGreed[];
extern const u8 gCardDescription_Jinzo[];
extern const u8 gCardDescription_JiraiGumo[];
extern const u8 gCardDescription_JowgentheSpiritualist[];
extern const u8 gCardDescription_JudgeMan[];
extern const u8 gCardDescription_JustDesserts[];
extern const u8 gCardDescription_KaiserSeaHorse[];
extern const u8 gCardDescription_KarmaCut[];
extern const u8 gCardDescription_KingDragun[];
extern const u8 gCardDescription_KingoftheSwamp[];
extern const u8 gCardDescription_KingTigerWanghu[];
extern const u8 gCardDescription_Kuriboh[];
extern const u8 gCardDescription_KycootheGhostDestroyer[];
extern const u8 gCardDescription_LaJinntheMysticalGenieoftheLamp[];
extern const u8 gCardDescription_LabyrinthTank[];
extern const u8 gCardDescription_LadyNinjaYae[];
extern const u8 gCardDescription_LastWill[];
extern const u8 gCardDescription_LeftArmoftheForbiddenOne[];
extern const u8 gCardDescription_LeftLegoftheForbiddenOne[];
extern const u8 gCardDescription_LegendaryJujitsuMaster[];
extern const u8 gCardDescription_LevelLimitAreaB[];
extern const u8 gCardDescription_LeviaDragonDaedalus[];
extern const u8 gCardDescription_LightofIntervention[];
extern const u8 gCardDescription_LightningVortex[];
extern const u8 gCardDescription_LimiterRemoval[];
extern const u8 gCardDescription_LusterDragon[];
extern const u8 gCardDescription_MadDogofDarkness[];
extern const u8 gCardDescription_MagePower[];
extern const u8 gCardDescription_MagicCylinder[];
extern const u8 gCardDescription_MagicJammer[];
extern const u8 gCardDescription_MagicalDimension[];
extern const u8 gCardDescription_MagicalMerchant[];
extern const u8 gCardDescription_MagicalScientist[];
extern const u8 gCardDescription_MagicianofFaith[];
extern const u8 gCardDescription_MagiciansCircle[];
extern const u8 gCardDescription_MagiciansValkyria[];
extern const u8 gCardDescription_MaidenoftheAqua[];
extern const u8 gCardDescription_MakyuratheDestructor[];
extern const u8 gCardDescription_ManEaterBug[];
extern const u8 gCardDescription_ManjuoftheTenThousandHands[];
extern const u8 gCardDescription_ManticoreofDarkness[];
extern const u8 gCardDescription_MaraudingCaptain[];
extern const u8 gCardDescription_MaskofDarkness[];
extern const u8 gCardDescription_MaskofRestrict[];
extern const u8 gCardDescription_MaskedDragon[];
extern const u8 gCardDescription_MaskedSorcerer[];
extern const u8 gCardDescription_MatazatheZapper[];
extern const u8 gCardDescription_Mechanicalchaser[];
extern const u8 gCardDescription_Megamorph[];
extern const u8 gCardDescription_MermaidKnight[];
extern const u8 gCardDescription_MessengerofPeace[];
extern const u8 gCardDescription_MetalReflectSlime[];
extern const u8 gCardDescription_Metamorphosis[];
extern const u8 gCardDescription_MilusRadiant[];
extern const u8 gCardDescription_Minar[];
extern const u8 gCardDescription_MindControl[];
extern const u8 gCardDescription_MineGolem[];
extern const u8 gCardDescription_MiracleRestoring[];
extern const u8 gCardDescription_MirageDragon[];
extern const u8 gCardDescription_MirageofNightmare[];
extern const u8 gCardDescription_MirrorForce[];
extern const u8 gCardDescription_MoaiInterceptorCannons[];
extern const u8 gCardDescription_MobiustheFrostMonarch[];
extern const u8 gCardDescription_MonsterGate[];
extern const u8 gCardDescription_MonsterReborn[];
extern const u8 gCardDescription_MonsterReincarnation[];
extern const u8 gCardDescription_MorphingJar[];
extern const u8 gCardDescription_MotherGrizzly[];
extern const u8 gCardDescription_MukaMuka[];
extern const u8 gCardDescription_MysticSwordsmanLV2[];
extern const u8 gCardDescription_MysticSwordsmanLV4[];
extern const u8 gCardDescription_MysticTomato[];
extern const u8 gCardDescription_MysticalElf[];
extern const u8 gCardDescription_MysticalSpaceTyphoon[];
extern const u8 gCardDescription_MystikWok[];
extern const u8 gCardDescription_Necrovalley[];
extern const u8 gCardDescription_NeedleCeiling[];
extern const u8 gCardDescription_NekoManeKing[];
extern const u8 gCardDescription_NeoBug[];
extern const u8 gCardDescription_NeotheMagicSwordsman[];
extern const u8 gCardDescription_Newdoria[];
extern const u8 gCardDescription_NightAssailant[];
extern const u8 gCardDescription_NightmareWheel[];
extern const u8 gCardDescription_NightmaresSteelcage[];
extern const u8 gCardDescription_NimbleMomonga[];
extern const u8 gCardDescription_NinKenDog[];
extern const u8 gCardDescription_NinjaGrandmasterSasuke[];
extern const u8 gCardDescription_NoblemanofCrossout[];
extern const u8 gCardDescription_NoblemanofExtermination[];
extern const u8 gCardDescription_OfferingstotheDoomed[];
extern const u8 gCardDescription_OjamaKing[];
extern const u8 gCardDescription_OjamaTrio[];
extern const u8 gCardDescription_Ookazi[];
extern const u8 gCardDescription_OppressedPeople[];
extern const u8 gCardDescription_Opticlops[];
extern const u8 gCardDescription_PainfulChoice[];
extern const u8 gCardDescription_PaladinofWhiteDragon[];
extern const u8 gCardDescription_PenguinKnight[];
extern const u8 gCardDescription_PhoenixWingWindBlast[];
extern const u8 gCardDescription_PikerusCircleofEnchantment[];
extern const u8 gCardDescription_PinchHopper[];
extern const u8 gCardDescription_PitchBlackPowerStone[];
extern const u8 gCardDescription_PoisonoftheOldMan[];
extern const u8 gCardDescription_Polymerization[];
extern const u8 gCardDescription_PotofAvarice[];
extern const u8 gCardDescription_PotofGenerosity[];
extern const u8 gCardDescription_PotofGreed[];
extern const u8 gCardDescription_PrematureBurial[];
extern const u8 gCardDescription_PreventRat[];
extern const u8 gCardDescription_PrickleFairy[];
extern const u8 gCardDescription_PrincessofTsurugi[];
extern const u8 gCardDescription_ProtectoroftheSanctuary[];
extern const u8 gCardDescription_PyramidTurtle[];
extern const u8 gCardDescription_Raigeki[];
extern const u8 gCardDescription_RaigekiBreak[];
extern const u8 gCardDescription_ReaperontheNightmare[];
extern const u8 gCardDescription_Reasoning[];
extern const u8 gCardDescription_RecklessGreed[];
extern const u8 gCardDescription_ReflectBounder[];
extern const u8 gCardDescription_ReinforcementoftheArmy[];
extern const u8 gCardDescription_Reinforcements[];
extern const u8 gCardDescription_Relinquished[];
extern const u8 gCardDescription_Reload[];
extern const u8 gCardDescription_RemoveTrap[];
extern const u8 gCardDescription_RescueCat[];
extern const u8 gCardDescription_ReturnfromtheDifferentDimension[];
extern const u8 gCardDescription_RightArmoftheForbiddenOne[];
extern const u8 gCardDescription_RightLegoftheForbiddenOne[];
extern const u8 gCardDescription_RingofDestruction[];
extern const u8 gCardDescription_RisingAirCurrent[];
extern const u8 gCardDescription_RobbinGoblin[];
extern const u8 gCardDescription_RouletteBarrel[];
extern const u8 gCardDescription_RoyalDecree[];
extern const u8 gCardDescription_RoyalMagicalLibrary[];
extern const u8 gCardDescription_RoyalOppression[];
extern const u8 gCardDescription_RushRecklessly[];
extern const u8 gCardDescription_RyuKokki[];
extern const u8 gCardDescription_SaberBeetle[];
extern const u8 gCardDescription_SacredCrane[];
extern const u8 gCardDescription_SacredPhoenixofNephthys[];
extern const u8 gCardDescription_SakuretsuArmor[];
extern const u8 gCardDescription_Salvage[];
extern const u8 gCardDescription_SandMoth[];
extern const u8 gCardDescription_Sangan[];
extern const u8 gCardDescription_SasukeSamurai[];
extern const u8 gCardDescription_SasukeSamurai4[];
extern const u8 gCardDescription_Scapegoat[];
extern const u8 gCardDescription_SeaSerpentWarriorofDarkness[];
extern const u8 gCardDescription_SecondCoinToss[];
extern const u8 gCardDescription_SecretBarrel[];
extern const u8 gCardDescription_SelfDestructButton[];
extern const u8 gCardDescription_SerialSpell[];
extern const u8 gCardDescription_SerpentinePrincess[];
extern const u8 gCardDescription_SevenToolsoftheBandit[];
extern const u8 gCardDescription_ShiningAngel[];
extern const u8 gCardDescription_Shrink[];
extern const u8 gCardDescription_SillvaWarlordofDarkWorld[];
extern const u8 gCardDescription_Silpheed[];
extern const u8 gCardDescription_SinisterSerpent[];
extern const u8 gCardDescription_SkillDrain[];
extern const u8 gCardDescription_SkilledDarkMagician[];
extern const u8 gCardDescription_SkilledWhiteMagician[];
extern const u8 gCardDescription_SkullDogMarron[];
extern const u8 gCardDescription_SkullLair[];
extern const u8 gCardDescription_SkyScout[];
extern const u8 gCardDescription_SlateWarrior[];
extern const u8 gCardDescription_SmashingGround[];
extern const u8 gCardDescription_SnatchSteal[];
extern const u8 gCardDescription_SolemnJudgment[];
extern const u8 gCardDescription_SolemnWishes[];
extern const u8 gCardDescription_SoulExchange[];
extern const u8 gCardDescription_SoulTiger[];
extern const u8 gCardDescription_SpearCretin[];
extern const u8 gCardDescription_SpearDragon[];
extern const u8 gCardDescription_SpellCanceller[];
extern const u8 gCardDescription_SpellReproduction[];
extern const u8 gCardDescription_SpiritoftheHarp[];
extern const u8 gCardDescription_SpiritReaper[];
extern const u8 gCardDescription_SpiritualEarthArtKurogane[];
extern const u8 gCardDescription_SpiritualWaterArtAoi[];
extern const u8 gCardDescription_SpiritualWindArtMiyabi[];
extern const u8 gCardDescription_Spiritualism[];
extern const u8 gCardDescription_StealthBird[];
extern const u8 gCardDescription_StoneStatueoftheAztecs[];
extern const u8 gCardDescription_StopDefense[];
extern const u8 gCardDescription_SummonedSkull[];
extern const u8 gCardDescription_SwarmofLocusts[];
extern const u8 gCardDescription_SwarmofScarabs[];
extern const u8 gCardDescription_SwordsofRevealingLight[];
extern const u8 gCardDescription_Terraforming[];
extern const u8 gCardDescription_TheBigMarchofAnimals[];
extern const u8 gCardDescription_TheDragonDwellingintheCave[];
extern const u8 gCardDescription_TheFiendMegacyber[];
extern const u8 gCardDescription_TheForcefulSentry[];
extern const u8 gCardDescription_TheForgivingMaiden[];
extern const u8 gCardDescription_TheLastWarriorfromAnotherPlanet[];
extern const u8 gCardDescription_TheLittleSwordsmanofAile[];
extern const u8 gCardDescription_TheWickedWormBeast[];
extern const u8 gCardDescription_ThestalostheFirestormMonarch[];
extern const u8 gCardDescription_ThousandEyesRestrict[];
extern const u8 gCardDescription_ThreateningRoar[];
extern const u8 gCardDescription_ThrowstoneUnit[];
extern const u8 gCardDescription_ThunderDragon[];
extern const u8 gCardDescription_ThunderNyanNyan[];
extern const u8 gCardDescription_TimeSeal[];
extern const u8 gCardDescription_ToonCannonSoldier[];
extern const u8 gCardDescription_ToonDarkMagicianGirl[];
extern const u8 gCardDescription_ToonGeminiElf[];
extern const u8 gCardDescription_ToonGoblinAttackForce[];
extern const u8 gCardDescription_ToonMaskedSorcerer[];
extern const u8 gCardDescription_ToonTableofContents[];
extern const u8 gCardDescription_TorrentialTribute[];
extern const u8 gCardDescription_TrapDustshoot[];
extern const u8 gCardDescription_TrapHole[];
extern const u8 gCardDescription_TrapMaster[];
extern const u8 gCardDescription_TreebornFrog[];
extern const u8 gCardDescription_TremendousFire[];
extern const u8 gCardDescription_TribeInfectingVirus[];
extern const u8 gCardDescription_TributetotheDoomed[];
extern const u8 gCardDescription_Tsukuyomi[];
extern const u8 gCardDescription_TwinHeadedBehemoth[];
extern const u8 gCardDescription_TwinHeadedThunderDragon[];
extern const u8 gCardDescription_UltimateInsectLV3[];
extern const u8 gCardDescription_UltimateInsectLV5[];
extern const u8 gCardDescription_UltimateInsectLV7[];
extern const u8 gCardDescription_UltimateOffering[];
extern const u8 gCardDescription_UnitedWeStand[];
extern const u8 gCardDescription_UpstartGoblin[];
extern const u8 gCardDescription_VampireLord[];
extern const u8 gCardDescription_VorseRaider[];
extern const u8 gCardDescription_Waboku[];
extern const u8 gCardDescription_WallofIllusion[];
extern const u8 gCardDescription_WallofRevealingLight[];
extern const u8 gCardDescription_WaveMotionCannon[];
extern const u8 gCardDescription_WhiteDragonRitual[];
extern const u8 gCardDescription_WhiteMagicalHat[];
extern const u8 gCardDescription_WidespreadRuin[];
extern const u8 gCardDescription_WitchoftheBlackForest[];
extern const u8 gCardDescription_XHeadCannon[];
extern const u8 gCardDescription_XingZhenHu[];
extern const u8 gCardDescription_YataGarasu[];
extern const u8 gCardDescription_YomiShip[];
extern const u8 gCardDescription_ZaborgtheThunderMonarch[];
extern const u8 gCardDescription_ZombyratheDark[];
extern const u8 gCardDescription_ZureKnightofDarkWorld[];
extern const u8 gCardDescription_AmazonessSpiritualist[];
extern const u8 gCardDescription_AncientGearDragon[];
extern const u8 gCardDescription_AngmarltheFiendishMonarch[];
extern const u8 gCardDescription_ApprenticeIllusionMagician[];
extern const u8 gCardDescription_ArchfiendCavalry[];
extern const u8 gCardDescription_ArchfiendCommander[];
extern const u8 gCardDescription_ArchfiendGiant[];
extern const u8 gCardDescription_ArchfiendHeiress[];
extern const u8 gCardDescription_ArchfiendInterceptor[];
extern const u8 gCardDescription_ArchfiendofGilfer[];
extern const u8 gCardDescription_ArchfiendsAdvent[];
extern const u8 gCardDescription_BakutheBeastNinja[];
extern const u8 gCardDescription_BeginningKnight[];
extern const u8 gCardDescription_BeiigeVanguardofDarkWorld[];
extern const u8 gCardDescription_BerlineththeFirestormVassal[];
extern const u8 gCardDescription_BlackDragonsChick[];
extern const u8 gCardDescription_BlackMetalDragon[];
extern const u8 gCardDescription_BlueFlameSwordsman[];
extern const u8 gCardDescription_BoneArchfiend[];
extern const u8 gCardDescription_CaiustheShadowMonarch[];
extern const u8 gCardDescription_ChronicleSorceress[];
extern const u8 gCardDescription_CyberDragonDrei[];
extern const u8 gCardDescription_CyberDragonVier[];
extern const u8 gCardDescription_CyberDragonZwei[];
extern const u8 gCardDescription_CyberLarva[];
extern const u8 gCardDescription_CyberdarkWurm[];
extern const u8 gCardDescription_DarkMagicianGirl[];
extern const u8 gCardDescription_DarkMagicianGirltheMagiciansApprentice[];
extern const u8 gCardDescription_DefenderofNephthys[];
extern const u8 gCardDescription_DelgtheDarkMonarch[];
extern const u8 gCardDescription_DictatorofD[];
extern const u8 gCardDescription_DimensionConjurer[];
extern const u8 gCardDescription_DiscipleofNephthys[];
extern const u8 gCardDescription_DupeFrog[];
extern const u8 gCardDescription_EidostheUnderworldMonarch[];
extern const u8 gCardDescription_EidostheUnderworldSquire[];
extern const u8 gCardDescription_ElementalHEROBlazeman[];
extern const u8 gCardDescription_ElementalHEROWoodsman[];
extern const u8 gCardDescription_EnvoyofChaos[];
extern const u8 gCardDescription_EveningTwilightKnight[];
extern const u8 gCardDescription_FightingFlameSwordsman[];
extern const u8 gCardDescription_FlipFlopFrog[];
extern const u8 gCardDescription_FusionDevourer[];
extern const u8 gCardDescription_GearfriedtheRedEyesIronKnight[];
extern const u8 gCardDescription_GemKnightQuartz[];
extern const u8 gCardDescription_GentaGatemanofDarkWorld[];
extern const u8 gCardDescription_GiltiatheDKnightSoulSpear[];
extern const u8 gCardDescription_GoblinPotholeSquad[];
extern const u8 gCardDescription_GranmargtheRockMonarch[];
extern const u8 gCardDescription_GreenNinja[];
extern const u8 gCardDescription_GrenTacticianofDarkWorld[];
extern const u8 gCardDescription_HandofNephthys[];
extern const u8 gCardDescription_IceKnight[];
extern const u8 gCardDescription_InfernalqueenSalmon[];
extern const u8 gCardDescription_KagerotheCannonNinja[];
extern const u8 gCardDescription_Kaibaman[];
extern const u8 gCardDescription_KeeperofDragonMagic[];
extern const u8 gCardDescription_KeeperoftheShrine[];
extern const u8 gCardDescription_LancerArchfiend[];
extern const u8 gCardDescription_LesserFiend[];
extern const u8 gCardDescription_LordofD[];
extern const u8 gCardDescription_LucentNetherlordofDarkWorld[];
extern const u8 gCardDescription_LuciustheShadowVassal[];
extern const u8 gCardDescription_MadArchfiend[];
extern const u8 gCardDescription_MagiciansRobe[];
extern const u8 gCardDescription_MagiciansRod[];
extern const u8 gCardDescription_MagiciansSouls[];
extern const u8 gCardDescription_Magikuriboh[];
extern const u8 gCardDescription_MaskedNinjaEbisu[];
extern const u8 gCardDescription_MatriarchofNephthys[];
extern const u8 gCardDescription_MetalflameSwordsman[];
extern const u8 gCardDescription_MitsutheInsectNinja[];
extern const u8 gCardDescription_MysticalElfWhiteLightning[];
extern const u8 gCardDescription_NinjaGrandmasterHanzo[];
extern const u8 gCardDescription_ParlHermitofDarkWorld[];
extern const u8 gCardDescription_RedDragonNinja[];
extern const u8 gCardDescription_RedEyesBabyDragon[];
extern const u8 gCardDescription_RedEyesBlackMeteorDragon[];
extern const u8 gCardDescription_RedEyesRetroDragon[];
extern const u8 gCardDescription_RedEyesWyvern[];
extern const u8 gCardDescription_Relinkuriboh[];
extern const u8 gCardDescription_Ronintoadin[];
extern const u8 gCardDescription_SalamandratheFlyingFlameDragon[];
extern const u8 gCardDescription_ScarrScoutofDarkWorld[];
extern const u8 gCardDescription_SeniorSilverNinja[];
extern const u8 gCardDescription_SenjuoftheThousandHands[];
extern const u8 gCardDescription_SkilledRedMagician[];
extern const u8 gCardDescription_SnowwUnlightofDarkWorld[];
extern const u8 gCardDescription_SonicBird[];
extern const u8 gCardDescription_SphereKuriboh[];
extern const u8 gCardDescription_Substitoad[];
extern const u8 gCardDescription_SuperSoldierSoul[];
extern const u8 gCardDescription_SwapFrog[];
extern const u8 gCardDescription_TADPOLE[];
extern const u8 gCardDescription_Tenmataitei[];
extern const u8 gCardDescription_TheBlackStoneofLegend[];
extern const u8 gCardDescription_TheDarkHexSealedFusion[];
extern const u8 gCardDescription_TheEarthHexSealedFusion[];
extern const u8 gCardDescription_TheLightHexSealedFusion[];
extern const u8 gCardDescription_ThunderDragondark[];
extern const u8 gCardDescription_ThunderDragonhawk[];
extern const u8 gCardDescription_ThunderDragonmatrix[];
extern const u8 gCardDescription_ThunderDragonroar[];
extern const u8 gCardDescription_ThunderSeaHorse[];
extern const u8 gCardDescription_TlakalelHisMalevolentMajesty[];
extern const u8 gCardDescription_TobaritheSkyNinja[];
extern const u8 gCardDescription_Tradetoad[];
extern const u8 gCardDescription_TraptrixArachnocampa[];
extern const u8 gCardDescription_TraptrixAtrax[];
extern const u8 gCardDescription_TraptrixDionaea[];
extern const u8 gCardDescription_TraptrixGenlisea[];
extern const u8 gCardDescription_TraptrixMantis[];
extern const u8 gCardDescription_TraptrixMyrmeleo[];
extern const u8 gCardDescription_TraptrixNepenthes[];
extern const u8 gCardDescription_TraptrixPudica[];
extern const u8 gCardDescription_TraptrixVesiculo[];
extern const u8 gCardDescription_TwilightNinjaNichirintheChunin[];
extern const u8 gCardDescription_TwilightNinjaShingetsu[];
extern const u8 gCardDescription_UpstartGoldenNinja[];
extern const u8 gCardDescription_VisionHEROVyon[];
extern const u8 gCardDescription_Wroughtweiler[];
extern const u8 gCardDescription_YellowNinja[];
extern const u16 CardIdMapping[];
extern const u16 PackIdMapping[];

#endif // GUARD_YGO_H
