#include "global.h"
#include "ygo.h"
#include "constants/ygo.h"
#include "ygo_graphics.h"
#include "constants/items.h"

const u8 gCardDescription_7ColoredFish[] = _("A rare rainbow fish that has\nnever been caught by mortal\nman.");
const u8 gCardDescription_AquaMadoor[] = _("A wizard of the waters that\nconjures a liquid wall to\ncrush any enemies that oppose\nhim.");
const u8 gCardDescription_BattleOx[] = _("A monster with tremendous\npower, it destroys enemies\nwith a swing of its axe.");
const u8 gCardDescription_Bickuribox[] = _("Crass Clown + Dream Clown");
const u8 gCardDescription_BlackSkullDragon[] = _("Summoned Skull + Red-Eyes\nBlack Dragon(This card is\nalways treated as an Archfiend\ncard.)");
const u8 gCardDescription_BlueEyesWhiteDragon[] = _("This legendary dragon is a\npowerful engine of\ndestruction. Virtually\ninvincible, very few have\nfaced this awesome creature\nand lived to tell the tale.");
const u8 gCardDescription_CannonSoldier[] = _("You can Tribute 1 monster;\ninflict 500 damage to your\nopponent.");
const u8 gCardDescription_ChangeofHeart[] = _("Target 1 monster your opponent\ncontrols; take control of it\nuntil the End Phase.");
const u8 gCardDescription_CrassClown[] = _("When this card is changed from\nDefense Position to Attack\nPosition, return 1 monster on\nyour opponent's side of the\nfield to the owner's hand.");
const u8 gCardDescription_DarkElf[] = _("This card requires a cost of\n1000 of your own Life Points\nto attack.");
const u8 gCardDescription_DarkHole[] = _("Destroy all monsters on the\nfield.");
const u8 gCardDescription_DarkMagician[] = _("The ultimate wizard in terms\nof attack and defense.");
const u8 gCardDescription_DreamClown[] = _("When this card is changed from\nAttack Position to face-up\nDefense Position, select 1\nmonster your opponent controls\nand destroy it.");
const u8 gCardDescription_ExodiatheForbiddenOne[] = _("If you have Right Leg of the\nForbidden One, Left Leg of the\nForbidden One, Right Arm of\nthe Forbidden One and Left Arm\nof the Forbidden One in\naddition to this card in your\nhand, you win the Duel.");
const u8 gCardDescription_Fissure[] = _("Destroy the 1 face-up monster\nyour opponent controls that\nhas the lowest ATK (your\nchoice, if tied).");
const u8 gCardDescription_FlameSwordsman[] = _("Flame Manipulator + Masaki the\nLegendary Swordsman");
const u8 gCardDescription_GaiatheDragonChampion[] = _("Gaia The Fierce Knight + Curse\nof Dragon");
const u8 gCardDescription_GaiaTheFierceKnight[] = _("A knight whose horse travels\nfaster than the wind. His\nbattle-charge is a force to be\nreckoned with.");
const u8 gCardDescription_GiantSoldierofStone[] = _("A giant warrior made of stone.\nA punch from this creature has\nearth-shaking results.");
const u8 gCardDescription_GigaTechWolf[] = _("An iron wolf with razor-sharp\nfangs that can penetrate any\narmor.");
const u8 gCardDescription_HeavyStorm[] = _("Destroy all Spell and Trap\nCards on the field.");
const u8 gCardDescription_JiraiGumo[] = _("When this card declares an\nattack: Toss a coin and call\nit. If you call it wrong, lose\nhalf your Life Points.");
const u8 gCardDescription_JudgeMan[] = _("This club-wielding warrior\nbattles to the end and will\nnever surrender.");
const u8 gCardDescription_JustDesserts[] = _("Inflict 500 damage to your\nopponent for each monster they\ncontrol.");
const u8 gCardDescription_Kuriboh[] = _("During damage calculation, if\nyour opponent's monster\nattacks (Quick Effect): You\ncan discard this card; you\ntake no battle damage from\nthat battle.");
const u8 gCardDescription_LaJinntheMysticalGenieoftheLamp[] = _("A genie of the lamp that is at\nthe beck and call of its\nmaster.");
const u8 gCardDescription_LabyrinthTank[] = _("Giga-Tech Wolf + Cannon\nSoldier");
const u8 gCardDescription_LastWill[] = _("If a monster on your side of\nthe field was sent to your\nGraveyard this turn, you can\nSpecial Summon 1 monster with\nan ATK of 1500 points or less\nfrom your Deck once during\nthis turn. Then shuffle your\nDeck.");
const u8 gCardDescription_LeftArmoftheForbiddenOne[] = _("A forbidden left arm sealed by\nmagic. Whosoever breaks this\nseal will know infinite power.");
const u8 gCardDescription_LeftLegoftheForbiddenOne[] = _("A forbidden left leg sealed by\nmagic. Whosoever breaks this\nseal will know infinite power.");
const u8 gCardDescription_MagicJammer[] = _("When a Spell Card is\nactivated: Discard 1 card;\nnegate the activation, and if\nyou do, destroy it.");
const u8 gCardDescription_MagicianofFaith[] = _("FLIP: Target 1 Spell in your\nGY; add that target to your\nhand.");
const u8 gCardDescription_ManEaterBug[] = _("FLIP: Target 1 monster on the\nfield; destroy it.");
const u8 gCardDescription_MaskofDarkness[] = _("FLIP: Target 1 Trap in your\nGY; add that target to your\nhand.");
const u8 gCardDescription_MaskedSorcerer[] = _("When this card inflicts Battle\nDamage to your opponent's Life\nPoints, draw 1 card from your\nDeck.");
const u8 gCardDescription_MirrorForce[] = _("When an opponent's monster\ndeclares an attack: Destroy\nall your opponent's Attack\nPosition monsters.");
const u8 gCardDescription_MonsterReborn[] = _("Target 1 monster in either GY;\nSpecial Summon it.");
const u8 gCardDescription_MukaMuka[] = _("This card gains 300 ATK and\nDEF for each card in your\nhand.");
const u8 gCardDescription_MysticalElf[] = _("A delicate elf that lacks\noffense, but has a terrific\ndefense backed by mystical\npower.");
const u8 gCardDescription_NeotheMagicSwordsman[] = _("A dimensional drifter who not\nonly practices sorcery, but is\nalso a sword and martial arts\nmaster.");
const u8 gCardDescription_Ookazi[] = _("Inflict 800 damage to your\nopponent.");
const u8 gCardDescription_Polymerization[] = _("Fusion Summon 1 Fusion Monster\nfrom your Extra Deck, using\nmonsters from your hand or\nfield as Fusion Material.");
const u8 gCardDescription_PotofGreed[] = _("Draw 2 cards.");
const u8 gCardDescription_Raigeki[] = _("Destroy all monsters your\nopponent controls.");
const u8 gCardDescription_RedEyesBlackDragon[] = _("A ferocious dragon with a\ndeadly attack.");
const u8 gCardDescription_Reinforcements[] = _("Target 1 face-up monster on\nthe field; it gains 500 ATK\nuntil the end of this turn.");
const u8 gCardDescription_RightArmoftheForbiddenOne[] = _("A forbidden right arm sealed\nby magic. Whosoever breaks\nthis seal will know infinite\npower.");
const u8 gCardDescription_RightLegoftheForbiddenOne[] = _("A forbidden right leg sealed\nby magic. Whosoever breaks\nthis seal will know infinite\npower.");
const u8 gCardDescription_RobbinGoblin[] = _("Each time a monster you\ncontrol inflicts Battle Damage\nto your opponent, your\nopponent discards 1 random\ncard.");
const u8 gCardDescription_Sangan[] = _("If this card is sent from the\nfield to the GY: Add 1 monster\nwith 1500 or less ATK from\nyour Deck to your hand, but\nyou cannot activate cards, or\nthe effects of cards, with\nthat name for the rest of this\nturn. You can only use this\neffect of Sangan once per\nturn.");
const u8 gCardDescription_SevenToolsoftheBandit[] = _("When a Trap Card is activated:\nPay 1000 LP; negate the\nactivation, and if you do,\ndestroy it.");
const u8 gCardDescription_SkullKnight[] = _("Tainted Wisdom + Ancient Brain");
const u8 gCardDescription_SolemnJudgment[] = _("When a monster(s) would be\nSummoned, OR a Spell/Trap Card\nis activated: Pay half your\nLP; negate the Summon or\nactivation, and if you do,\ndestroy that card.");
const u8 gCardDescription_SoulExchange[] = _("Target 1 monster your opponent\ncontrols; this turn, if you\nTribute a monster, you must\nTribute that target, as if you\ncontrolled it. You cannot\nconduct your Battle Phase the\nturn you activate this card.");
const u8 gCardDescription_SummonedSkull[] = _("A fiend with dark powers for\nconfusing the enemy. Among the\nFiend-Type monsters, this\nmonster boasts considerable\nforce.(This card is always\ntreated as an Archfiend card.)");
const u8 gCardDescription_SwordsofRevealingLight[] = _("After this card's activation,\nit remains on the field, but\nyou must destroy it during the\nEnd Phase of your opponent's\n3rd turn. When this card is\nactivated: If your opponent\ncontrols a face-down monster,\nflip all monsters they control\nface-up. While this card is\nface-up on the field, your\nopponent's monsters cannot\ndeclare an attack.");
const u8 gCardDescription_ThunderDragon[] = _("You can discard this card; add\nup to 2 Thunder Dragon from\nyour Deck to your hand.");
const u8 gCardDescription_TrapHole[] = _("When your opponent Normal or\nFlip Summons 1 monster with\n1000 or more ATK: Target that\nmonster; destroy that target.");
const u8 gCardDescription_TributetotheDoomed[] = _("Discard 1 card, then target 1\nmonster on the field; destroy\nit.");
const u8 gCardDescription_TwinHeadedThunderDragon[] = _("Thunder Dragon + Thunder\nDragon");
const u8 gCardDescription_UltimateOffering[] = _("During your Main Phase or your\nopponent's Battle Phase: You\ncan pay 500 Life Points;\nimmediately after this effect\nresolves, Normal Summon/Set 1\nmonster.");
const u8 gCardDescription_Waboku[] = _("You take no battle damage from\nyour opponent's monsters this\nturn. Your monsters cannot be\ndestroyed by battle this turn.");
const u8 gCardDescription_WallofIllusion[] = _("If this card is attacked by a\nmonster, after damage\ncalculation: Return that\nmonster to the hand.");
const u8 gCardDescription_WhiteMagicalHat[] = _("When this card inflicts Battle\nDamage to your opponent's Life\nPoints, your opponent discards\n1 card randomly from his/her\nhand.");
const u8 gCardDescription_WitchoftheBlackForest[] = _("If this card is sent from the\nfield to the GY: Add 1 monster\nwith 1500 or less DEF from\nyour Deck to your hand, but\nyou cannot activate cards, or\nthe effects of cards, with\nthat name for the rest of this\nturn. You can only use this\neffect of Witch of the Black\nForest once per turn.");

const u8 CardIdMapping[] = 
{
    [ITEM_7_COLORED_FISH] = 1,
    [ITEM_AQUA_MADOOR] = 2,
    [ITEM_BATTLE_OX] = 3,
    [ITEM_BICKURIBOX] = 4,
    [ITEM_BLACK_SKULL_DRAGON] = 5,
    [ITEM_BLUE_EYES_WHITE_DRAGON] = 6,
    [ITEM_CANNON_SOLDIER] = 7,
    [ITEM_CHANGE_OF_HEART] = 8,
    [ITEM_CRASS_CLOWN] = 9,
    [ITEM_DARK_ELF] = 10,
    [ITEM_DARK_HOLE] = 11,
    [ITEM_DARK_MAGICIAN] = 12,
    [ITEM_DREAM_CLOWN] = 13,
    [ITEM_EXODIA_THE_FORBIDDEN_ONE] = 14,
    [ITEM_FISSURE] = 15,
    [ITEM_FLAME_SWORDSMAN] = 16,
    [ITEM_GAIA_THE_DRAGON_CHAMPION] = 17,
    [ITEM_GAIA_THE_FIERCE_KNIGHT] = 18,
    [ITEM_GIANT_SOLDIER_OF_STONE] = 19,
    [ITEM_GIGA_TECH_WOLF] = 20,
    [ITEM_HEAVY_STORM] = 21,
    [ITEM_JIRAI_GUMO] = 22,
    [ITEM_JUDGE_MAN] = 23,
    [ITEM_JUST_DESSERTS] = 24,
    [ITEM_KURIBOH] = 25,
    [ITEM_LA_JINN_THE_MYSTICAL_GENIE_OF_THE_LAMP] = 26,
    [ITEM_LABYRINTH_TANK] = 27,
    [ITEM_LAST_WILL] = 28,
    [ITEM_LEFT_ARM_OF_THE_FORBIDDEN_ONE] = 29,
    [ITEM_LEFT_LEG_OF_THE_FORBIDDEN_ONE] = 30,
    [ITEM_MAGIC_JAMMER] = 31,
    [ITEM_MAGICIAN_OF_FAITH] = 32,
    [ITEM_MAN_EATER_BUG] = 33,
    [ITEM_MASK_OF_DARKNESS] = 34,
    [ITEM_MASKED_SORCERER] = 35,
    [ITEM_MIRROR_FORCE] = 36,
    [ITEM_MONSTER_REBORN] = 37,
    [ITEM_MUKA_MUKA] = 38,
    [ITEM_MYSTICAL_ELF] = 39,
    [ITEM_NEO_THE_MAGIC_SWORDSMAN] = 40,
    [ITEM_OOKAZI] = 41,
    [ITEM_POLYMERIZATION] = 42,
    [ITEM_POT_OF_GREED] = 43,
    [ITEM_RAIGEKI] = 44,
    [ITEM_RED_EYES_BLACK_DRAGON] = 45,
    [ITEM_REINFORCEMENTS] = 46,
    [ITEM_RIGHT_ARM_OF_THE_FORBIDDEN_ONE] = 47,
    [ITEM_RIGHT_LEG_OF_THE_FORBIDDEN_ONE] = 48,
    [ITEM_ROBBIN_GOBLIN] = 49,
    [ITEM_SANGAN] = 50,
    [ITEM_SEVEN_TOOLS_OF_THE_BANDIT] = 51,
    [ITEM_SKULL_KNIGHT] = 52,
    [ITEM_SOLEMN_JUDGMENT] = 53,
    [ITEM_SOUL_EXCHANGE] = 54,
    [ITEM_SUMMONED_SKULL] = 55,
    [ITEM_SWORDS_OF_REVEALING_LIGHT] = 56,
    [ITEM_THUNDER_DRAGON] = 57,
    [ITEM_TRAP_HOLE] = 58,
    [ITEM_TRIBUTE_TO_THE_DOOMED] = 59,
    [ITEM_TWIN_HEADED_THUNDER_DRAGON] = 60,
    [ITEM_ULTIMATE_OFFERING] = 61,
    [ITEM_WABOKU] = 62,
    [ITEM_WALL_OF_ILLUSION] = 63,
    [ITEM_WHITE_MAGICAL_HAT] = 64,
    [ITEM_WITCH_OF_THE_BLACK_FOREST] = 65,
};
